### ISSUE TITLE
.NET Core support

### ISSUE THREAD

**Issue by saitolabs** [oracle/dotnet-db-samples#1]
Project Oracle.ManagedDataAccess is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0).

When a compatible version will be released?

**Comment by chadbr** [comment]
yes please

**Comment by vilinski** [comment]
+1

**Comment by joaocolombo** [comment]
+1

**Comment by alexkeh** [comment]
.NET Core 1.x will not be supported. .NET Core 2.0 will be. Oracle will release a managed ODP.NET beta around the end of this year.

http://www.oracle.com/technetwork/topics/dotnet/tech-info/odpnet-dotnet-core-sod-3628981.pdf
