### ISSUE TITLE
How to handle ExecuteNonQuery properly?

### ISSUE THREAD

**Issue by AlessHo** [oracle/dotnet-db-samples#10]
I am calling a stored procedure which has in and out parameters; I am confused a bit of how to check whether returned out is null or not using .net core2; Here is an example:

            String strErr = "";
            var prm = new OracleParameter();
            using (OracleConnection con = new OracleConnection(conString))
            {
                using (OracleCommand cmd = con.CreateCommand())
                {
                    try
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        con.Open();
                        cmd.CommandText = "PKG_WEB.CALL_US";
                        cmd.BindByName = true;

                        prm = new OracleParameter("P_ID", OracleDbType.NVarchar2);
                        prm.Direction = ParameterDirection.Input;
                        prm.Value = 1;
                        cmd.Parameters.Add(prm);

                        prm = new OracleParameter("P_MOBILE", OracleDbType.NVarchar2);
                        prm.Direction = ParameterDirection.Input;
                        prm.Value = 123;
                        cmd.Parameters.Add(prm);

                        prm = new OracleParameter("P_ERROR", OracleDbType.NVarchar2, 100);
                        prm.Direction = ParameterDirection.Output;
                        cmd.Parameters.Add(prm);

                        cmd.ExecuteNonQuery();

                       // here how can we check if returned P_ERROR param is null?
                       if (  //  P_ERROR  not null  ){
                            strErr = cmd.Parameters["P_ERROR"].Value.ToString();
                           // if condition was not added strErr wil be filled as "null"
                        }                        
                    }
                    catch (Exception ex)
                    {
                        //Console.WriteLine(ex.Message);
                    }
                    //Console.ReadLine();
                }
            }

I appreciate if you can post an example of ExecuteNonQuery on github same as ExecuteReader;

**Comment by alexkeh** [comment]
Try cmd.Parameters["P_ERROR"].Status == OracleParameterStatus.NullFetched;

**Comment by AlessHo** [comment]
It worked successfully, thank you
