### ISSUE TITLE
Bulk Insert EF core

### ISSUE THREAD

**Issue by deniscesar** [oracle/dotnet-db-samples#100]
Hello

Do we have any bulk insert functionality?

I tried to use Z.EntityFramework.Extensions but it has not worked well with the sequence generation using UseHiLo("SEQUENCE")

Also trying to use AddRange I have sequence integrity constraint error

**Comment by alexkeh** [comment]
Oracle BulkCopy is being added to the upcoming major ODP.NET release.

**Comment by deniscesar** [comment]
Thanks @alexkeh 

Taking advantage of this conversation can you tell me if HasComment is working for migrations?
I made use of HasComment and generated the migrations, but the column in the database was not commented.

**Comment by alexkeh** [comment]
@deniscesar I filed bug 31973396 to track this issue. Thanks for reporting.

**Comment by alexkeh** [comment]
You will need to have an [Oracle Support](https://support.oracle.com/portal/) account, which you may have to ask your DBA to get access to. From My Oracle Support, you will be able to track this bug.

**Comment by alexkeh** [comment]
A change in plan for Bulk Copy in managed ODP.NET and ODP.NET Core. We plan to deliver this feature **sooner** than the next major DB release now. It will be part of one our upcoming 19c releases on NuGet Gallery.

**Comment by alexkeh** [comment]
Bulk Copy is now available with ODP.NET 19.10 and higher. Download from NuGet Gallery:
- [Managed ODP.NET](https://www.nuget.org/packages/Oracle.ManagedDataAccess/)
- [ODP.NET Core](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/)

**Comment by alexkeh** [comment]
Bug 31973396 has been fixed in the Oracle EF Core 5.21.1 release.
