### ISSUE TITLE
System.Exception: 'TTC Error' - when reading CLOB

### ISSUE THREAD

**Issue by blancocardenas** [oracle/dotnet-db-samples#101]
### Database Version:
Oracle Database 10g Enterprise Edition Release 10.2.0.1.0 - 64bit
PL/SQL Release 10.2.0.1.0 - Production
CORE 10.2.0.1.0 Production
TNS for 64-bit Windows: Version 10.2.0.1.0 - Production
NLSRTL Version 10.2.0.1.0 - Production
### Reproducible in:
Oracle.ManagedDataAccess -- versions greater than 12.2.1100
Oracle.ManagedDataAccess.Core -- all
### Test code:
```
var tableName = "OracleBugTest";
OracleConfiguration.TraceLevel = 7;
OracleConfiguration.TraceFileLocation = ".";
var connString = "User Id=XXXXX;Password=XXXXX;Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=XXXXX)(PORT=XXXXX))(CONNECT_DATA=(SERVICE_NAME=XXXXX)))";
using (var connection = new OracleConnection(connString))
{
	connection.Open();
	using (var command = connection.CreateCommand())
	{
		try
		{
			command.CommandText = $@"CREATE TABLE {tableName} ( Text CLOB )";
			command.ExecuteNonQuery();
		}
		catch (OracleException e) when (e.Number == 955) { }

		command.CommandText = $@"INSERT INTO OracleBugTest (Text) VALUES ('SomeText')";
		command.ExecuteNonQuery();

		command.CommandText = "select * from OracleBugTest";

		using (var reader = command.ExecuteReader())
		{
			while (reader.Read())
			{
				Debug.WriteLine(reader.GetString(0));
			}
		}
	}
}
```
### Stacktrace
```
at OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 initialLOBFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired)
   at OracleInternal.ServiceObjects.OracleDataReaderImpl.FetchMoreRows(Int32 noOfRowsToFetch, Boolean fillReader, Boolean returnPSTypes)
   at Oracle.ManagedDataAccess.Client.OracleDataReader.Read()
   at Oracle10gBugTestCore.Program.Main(String[] args) in C:\Users\ecardenas\source\repos\Oracle10gBugTestCore\Oracle10gBugTestCore\Program.cs:line 38
```

[Oracle.ManagedDataAccess_19.9.0_TRACE.txt](https://github.com/oracle/dotnet-db-samples/files/5260541/Oracle.ManagedDataAccess_19.9.0_TRACE.txt)
[Oracle.ManagedDataAccess.Core_2.19.90_TRACE.txt](https://github.com/oracle/dotnet-db-samples/files/5260735/Oracle.ManagedDataAccess.Core_2.19.90_TRACE.txt)

**Comment by alexkeh** [comment]
Oracle Database 10.2 was desupported 10 years ago. ODP.NET 12.2 is compatible with Oracle DB 10.2 as long as you upgrade to the final patchset, 10.2.0.5. You are using 10.2.0.1.

**Comment by blancocardenas** [comment]
1. Is there any official note of which databases are supported or breaking change note ?
2. There is 10g specific code in the .NET and the .NET Core version see(m_isDb10gR2OrHigher). It does not seem to be that difficult to continue to support the 10g version. Are there any plans to make ODP.NET opensource ?
3. Apart from the age you can tell me why the support was dropped ?

**Comment by alexkeh** [comment]
Look at the beginning of Chapter 2 of the ODP.NET developer's guide version you are using for supported DB versions. Here's a link to the latest [ODP.NET 19c system requirements](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/InstallSystemRequirements.html#GUID-A6405CAD-C0E9-45E0-9C38-26B7ED214479).

There are no plans to open source ODP.NET.

It's a practice of the software industry to eventually drop support after a certain period of time. Older versions do not get new features. They do not support new OSes and are less likely to be certified with newer ISV apps. As a practical matter, all the OSes that Oracle DB 10.2 is certified with are no longer supported by their respective vendor. For example, the newest OS that DB 10.2 supports is Windows 2008, which MS no longer supports itself.
