### ISSUE TITLE
Column ambiguously defined ORA-00918

### ISSUE THREAD

**Issue by danko007** [oracle/dotnet-db-samples#103]
The code below results in 'Column ambiguously defined ORA-00918'
This occurs if version of Oracle.EntityFrameworkCore is 3.19.80
Worked well in Oracle.EntityFrameworkCore 2.19.90

`class Order{
public int Id{get;set;}
public DateTime? CompletionDate{get;set;}
public bool IsActive{
var now = DateTime.Now
return now<this.CompletionDate || CompletionDate==null;
}
}

class OrderDetail{
public int Id{get;set;}
public int OrderId{get;set;}
public Order Order{get;set;}
}

(from od in db.OrderDetails.Include(d=>d.Order)
select new {Id=od.Id, IsActive=od.Order.IsActive}).ToArray()`

**Comment by alexkeh** [comment]
Which DB version are you using? Also, when you moved from Oracle EF Core 2.19.90 to 3.19.80 did you also change the EF Core versions from 2.x to 3.1?

**Comment by danko007** [comment]
We have 12c, EE / 12.1.0.2.0.
As for EF Core version change-yes, I've changed it.

**Comment by alexkeh** [comment]
Yes, this is a known issue specifically with DB 12.1.x. The two ID columns are causing the issue. From the release notes:
```
Oracle Database 12.1 has the following limitation: if the select list contains columns with identical names and you specify the 
row limiting clause, then an ORA-00918 error occurs. This error occurs whether the identically named columns are in the same table or in different tables.

Let us suppose that database contains following two table definitions:
SQL> desc X;
 Name    Null?    Type
 ------- -------- ----------------------------
 COL1    NOT NULL NUMBER(10)
 COL2             NVARCHAR2(2000)

SQL> desc Y;
 Name    Null?    Type
 ------- -------- ----------------------------
 COL0    NOT NULL NUMBER(10)
 COL1             NUMBER(10)
 COL3             NVARCHAR2(2000)

Executing the following LINQ, for example, would generate a select query which would contain "COL1" column from both the tables.  
Hence, it would result in error ORA-00918:
dbContext.Y.Include(a => a.X).Skip(2).Take(3).ToList();
This error does not occur when using Oracle Database 11.2, 12.2, and higher versions.
```

**Comment by danko007** [comment]
Thank you for information. Are you going to fix it for 12.1? If so - is it a matter of weeks or months?

**Comment by alexkeh** [comment]
The DB server team has fixed this limitation in 12.2. I've asked and the fix is not planned to be backported to a 12.1 patch. The recommended solution is to upgrade to 12.2 or higher.

At a SQL level, there is a way to workaround the limitation by using aliases. Of course, this can't be done if you use LINQ.

**Comment by omon77** [comment]
You can avoid this bug, by configuring your db context to use SQL compatible with Oracle 11g, that doesn't have this bug:
`
            services.AddDbContext<yourDbContext>(options =>
                  options.UseOracle(yourDbConnectionString, b => b.UseOracleSQLCompatibility("11"))`

**Comment by kvansaders** [comment]
> @danko007
> You can avoid this bug, by configuring your db context to use SQL compatible with Oracle 11g, that doesn't have this bug:
> `services.AddDbContext<yourDbContext>(options => options.UseOracle(yourDbConnectionString, b => b.UseOracleSQLCompatibility("11"))`

This workaround did not fix the issue.

**Comment by dariusclinton** [comment]
> @danko007
> You can avoid this bug, by configuring your db context to use SQL compatible with Oracle 11g, that doesn't have this bug:
> `services.AddDbContext<yourDbContext>(options => options.UseOracle(yourDbConnectionString, b => b.UseOracleSQLCompatibility("11"))`

This worked for me. Thanks!

```
<PackageReference Include="Oracle.EntityFrameworkCore" Version="3.19.80" />
<PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.12" />
Oracle 12c EE
```

**Comment by kvansaders** [comment]
> > @danko007
> > You can avoid this bug, by configuring your db context to use SQL compatible with Oracle 11g, that doesn't have this bug:
> > `services.AddDbContext<yourDbContext>(options => options.UseOracle(yourDbConnectionString, b => b.UseOracleSQLCompatibility("11"))`
> 
> This worked for me. Thanks!
> 
> ```
> <PackageReference Include="Oracle.EntityFrameworkCore" Version="3.19.80" />
> <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.12" />
> Oracle 12c EE
> ```

Interesting that it worked for you.  I'm still getting the same error with Oracle 12.1.0.2
Running application is net5.0, 
within startup:
```
            services.AddDbContext<DNADbContext>(options =>
                options.UseOracle(
                    Configuration.GetConnectionString("DbContext"), b => b.UseOracleSQLCompatibility("11")
                ));
```

DBContext is within another library, netstandard2.1
```
<PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Oracle.EntityFrameworkCore" Version="5.21.1" />
  </ItemGroup>
```
I tried using the EF package versions you specified, still with no resolution.  When I repoint to a local 18XE though, it does work just fine.

**Comment by xXAvoraXx** [comment]
is there any solution?

**Comment by alexkeh** [comment]
@xXAvoraXx With DB 12.1 out of support, the recommended solution now is to upgrade to DB 19c or higher. That DB version has the bug fixed.

**Comment by xXAvoraXx** [comment]
@alexkeh The organization is not ready for the database upgrade yet, so I need a workaround.

**Comment by kvansaders** [comment]
> @alexkeh The organization is not ready for the database upgrade yet, so I need a workaround.

Fyi, I had this same issue 2 years ago and couldn't upgrade either. We purchased DevArt's Oracle provider for Entity Framework/ EF Core and it works on the older versions. You can reuse your existing code and just swap out the provider in startup.

https://www.devart.com/dotconnect/oracle/articles/efcore-database-first-net-core.html

**Comment by alexkeh** [comment]
@xXAvoraXx You can try @kvansaders suggestion.

The other possible workarounds have been discussed on this thread (i.e. change DB version, use UseOracleSQLCompatibility("11"))

**Comment by xXAvoraXx** [comment]
> @xXAvoraXx You can try @kvansaders suggestion.
> 
> The other possible workarounds have been discussed on this thread (i.e. change DB version, use UseOracleSQLCompatibility("11"))

not work
