### ISSUE TITLE
EF Core 3.1 migrations with Oracle 11g

### ISSUE THREAD

**Issue by BernhardNinaus** [oracle/dotnet-db-samples#104]
Hey.

I've encountered a problem while applying migrations with an identity column to a 11g database.
I used the "Key" annotation on the ID property. The resulting migrations is this for ID column:
```csharp
ID = table.Column<int>(nullable: false)
    .Annotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn),
````
  
  
Of course it will fail to apply to the databse because it's not supportet. However, I thought that registering my DbContext with:
```charp
    .UseOracleSQLCompatibility("11")
```
could mitigate/resolve this problem by alerting or some other action.

My solution to this problem is to change the automatic created migration by adding a Sequence and creating a Trigger which will change the ID value with sequence.nextval (when new.ID is null).
Seems to work just fine.

Is there another solution or am I doing something else wrong?

Thank you, best regards.

**Comment by alexkeh** [comment]
You shouldn't need to use the annotation. The sequence and trigger will be created automatically for an "ID" column once you set the compatibility level to 11.

**Comment by BernhardNinaus** [comment]
Thanks for this information, I'll try this tomorrow.
