### ISSUE TITLE
.NET 5 - ODP.NET type initializer throws exception when using DataSet or DataTable

### ISSUE THREAD

**Issue by tyler-shuhnicki** [oracle/dotnet-db-samples#109]
Hi there,

We are migrating our application from .NET Framework 4.8 to .NET 5, and moving toward serverless.

Our team is largely on preview version 4 of .NET 5, but one of our team members has upgraded to the latest release candidate. Oracle.ManagedDataAccess.Core is throwing a strange error, posted below. I was hoping this forum might be able to point me in the right direction for a solution, or another team to reach out to. I have made a post on the dotnet forum, which kicked the issue back to the Oracle side of things. Here's a link to that issue: https://github.com/dotnet/core/issues/5356

Thanks for your time!

InnerException = {"The type initializer for 'Oracle.ManagedDataAccess.Types.TimeStamp' threw an exception."} System.Private.CoreLib at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor) at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache) at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions) at System.Activator.CreateInstanceT at OracleInternal.ConnectionPool.PoolManager3.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPwd, OracleConnection connRefForCriteria, String instanceName, List1 switchFailedInstNames) at OracleInternal.ConnectionPool.PoolManager3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch) at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch) at OracleInternal.ConnectionPool.OracleConnectionDispenser3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria) at Oracle.ManagedDataAccess.Client.OracleConnection.Open() at Dapper.SqlMapper.d__1401.MoveNext() in /_/Dapper/SqlMapper.cs:line 1079 at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source) at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable1 commandTimeout, Nullable1 commandType) in /_/Dapper/SqlMapper.cs:line 721 at General.Data.AccountData.LoadAccount(RequestAccount request) in D:\GitLab\cfconnect-api-core\General\Data\AccountData.cs:line 333

**Comment by alexkeh** [comment]
Hi @tyler-shuhnicki 
I tried running a simple ODP.NET Core app with the latest .NET 5 RC2 SDK. I was able to connect without error. The only other time I can remember seeing a similar issue in the ODP.NET Core is when a customer tried to use [assembly trimming](https://github.com/oracle/dotnet-db-samples/issues/54). 

Does this error occur with a direct ODP.NET connection, not using Dapper?

You can try enabling ODP.NET tracing and send it to us dotnet_us(at)oracle.com and we can see if there's anything we can conclude from the trace.

Just include the following two lines in your code and set a directory location to write the trace to:
```
OracleConfiguration.TraceFileLocation = @"D:\traces";
OracleConfiguration.TraceLevel = 7;
```

**Comment by tyler-shuhnicki** [comment]
Hi @alexkeh, sorry for the later response!

We've enabled tracing, and I've sent it over to you. Your help would be greatly appreciated!

Thanks,
Tyler

**Comment by alexkeh** [comment]
It looks like the root cause is something in your stack is disabling the BinaryFormatter APIs, which have been obsoleted for .NET 5. To allow you to continue with the RC for now, [Here's a workaround](https://github.com/GrabYourPitchforks/docs/blob/bf_obsoletion_docs/docs/standard/serialization/resolving-binaryformatter-obsoletion-errors.md#obsoletion-of-binaryformatter-apis) that you can apply to your .csproj.

In the meantime, my team will work on a longer term solution for .NET 5.

**Comment by tyler-shuhnicki** [comment]
Alex,

Thanks a lot for your correspondence, this has been very helpful. Is there any way to specify which formatter is used on ODP.NET DB calls, or is the .csproj workaround the best case scenario for the moment?

Thanks again.
Tyler

**Comment by alexkeh** [comment]
@tyler-shuhnicki 
[MS documents a programmatic way to extend the list of allowed data types programmatically](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dataset-datatable-dataview/security-guidance#extend-programmatically-net-framework-net-core-net-50). Later on in the same document, it describes how to remove all type restrictions, which is easier if you have a lot of Oracle types you want to enable, but is a security issue.

**Comment by alexkeh** [comment]
@tyler-shuhnicki 
We've discussed the issue with the MS .NET team. This new behavior is expected. The .NET runtime change was made to improve app security. If developers want to use data provider specific types in DataSet/DataTable, then code changes are needed to allow those data types.

Oracle and Microsoft discussed ways to automate adding the Oracle data types without developers having to make config/code changes when upgrading to .NET 5. It is possible to do, but a race condition could occur. There's no way that a data provider by itself could guarantee avoiding the race condition. So, in the next ODP.NET version, which will officially support .NET 5, we will be adding a new Boolean property for developers to enable these provider types. A user set property will avoid the race condition.

We'll provide documentation on this new property in the next ODP.NET Core (19.10) release.

**Comment by MaherJendoubi** [comment]
Hi Alex,

Is (19.10) the next version of ODP.NET Core? Any idea about the release date?

Best,
Maher

**Comment by alexkeh** [comment]
We'll release ODP.NET Core 19.10 as soon as .NET 5 is certified with it. It make take a few days from when MS releases .NET 5. It may take longer. It depends whether we find any ODP.NET Core bugs running on that .NET 5 release. I anticipate it will take less than a month for ODP.NET Core 19.10 to be released from when .NET 5 is released.

ODP.NET Core 19.9 works right now with the .NET 5 RC 2 and will likely be fine with the .NET 5 for development and testing use.

**Comment by MaherJendoubi** [comment]
Thank you @alexkeh for your prompt reply. I am asked my first question because I am confused about the version of ODP.NET Core.
Here is why: The latest version is published as a nuget package that we could add it through the command **dotnet add package Oracle.ManagedDataAccess.Core --version 2.19.91** and I cannot find 19.9 version.

**Comment by alexkeh** [comment]
@MaherJendoubi ODP.NET Core 2.19.91 translates to ODP.NET Core 19.9.1. We have to fit Oracle versioning into the NuGet package versioning and the way .NET Core versions. The first version represents the minimum .NET Core version supported (for now) while the last two digits represent the Oracle software version.

The 19.9 version uses the version 2.19.90.

**Comment by oyzar** [comment]
It seems to me like the crash is coming because ODP is trying to load some resource that has been serialized binary. If the same information could be loaded without using resources (or by using xml or json instead), that migh 
help to work around the issue. https://github.com/dotnet/sdk/pull/12434#discussion_r453827187

**Comment by alexkeh** [comment]
ODP.NET 19.10 is now available with .NET Runtime 5 support and a new method, AddOracleTypesDeserialization, that supports deserializing ODP.NET data types from DataSet and DataTable. [Download ODP.NET Core](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/) from NuGet Gallery. 

Read more about how to use the new method and other new 19.10 features in [ODP.NET 19.10 Release blog post](https://medium.com/@alex.keh/announcing-odp-net-19-10-release-new-net-5-and-bulk-copy-support-be6f395155c9).

**Comment by tyler-shuhnicki** [comment]
@alexkeh Hi Alex,

Sorry to bring this thread back to life, but adding the line OracleConfiguration.AddOracleTypesDeserialization(); to the Startup.cs, Program.cs, or even before the call itself, still does not support serialization. Is there a specific usage that we are not doing correctly?

Thanks!
Tyler

**Comment by alexkeh** [comment]
@tyler-shuhnicki 
There are two different security changes in .NET 5 (and other recent .NET patches) MS made. 

1. Deserialization with DataSet/DataTable for ODP.NET types
2. BinaryFormatter serialization

The new AddOracleTypesDeserialization method addresses the first change. The second change currently can be resolved by setting in your .csproj:
`<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>`

My dev team is working on a fix that will not require making the above change. Disabling BinaryFormatter occurs by default for ASP.NET Core 5 apps, but not for other .NET 5 apps.

It's possible you are encountering the second issue.
