### ISSUE TITLE
Can we get an LDAP connection sample for ODP.NET Core?

### ISSUE THREAD

**Issue by Mmatiasn** [oracle/dotnet-db-samples#11]
Can we get an LDAP connection sample for ODP.NET Core? I read that it is supported but have failed to find any documentation related to this claim.

**Comment by alexkeh** [comment]
The current answer is no, which is what you will find in the ODP.NET Core beta documentation. .NET Standard does not support System.DirectoryServices, which means ODP.NET Core does not support it either. However, MS has released the Windows Compatibility Pack (WCP), which does support System.DirectoryServices on Windows only. No cross platform support, but gives you LDAP support if running on Windows.

Are you looking for Windows only LDAP support?

**Comment by Mmatiasn** [comment]
Hi alexkeh,

I'm looking for Windows only LDAP support.

**Comment by alexkeh** [comment]
Hi @terrajobst
I couldn't find provider writer specific information on what data providers should modify to use WCP for Windows LDAP support. Can you point me in the right direction?

**Comment by alexkeh** [comment]
It looks like we've found a solution without using WCP itself, just the necessary LDAP libraries. Closing this issue for now.

**Comment by Mmatiasn** [comment]
> It looks like we've found a solution without using WCP itself, just the necessary LDAP libraries. Closing this issue for now.

I'm sorry, where is this solution located at?

**Comment by alexkeh** [comment]
You should be able to incorporate System.DirectoryServices package into your ODP.NET Core project to use LDAP. Oracle is testing out this solution. We plan to certify this as a supported combination for the next ODP.NET Core release.

**Comment by StevenRasmussen** [comment]
I didn't see any examples of how to use LDAP with ODP.Net Core.  Can someone please point me to a working example? Thanks in advance.

**Comment by alexkeh** [comment]
@StevenRasmussen using LDAP with ODP.NET Core or any ODP.NET driver type is primarily a configuration operation.

The necessary .NET packages that need to be included here:
https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/featConnecting.html#GUID-48612E90-A2BB-4766-880A-097721E564F8
