### ISSUE TITLE
.Net Core 3.x and Java 11 support for Timesten ODP.Net provider

### ISSUE THREAD

**Issue by ozzioma** [oracle/dotnet-db-samples#110]
Hi guys,

I'm evaluating Timesten for a new solution, and we're looking at a Java or .Net Core implementation.
Searched all through the docs and can't find any pointer to .Net Core 3.x support for the latest TimesTen ScaleOut release.
Also Java 11 support.

Clarifications highly welcome.

Thanks

**Comment by alexkeh** [comment]
@ozzioma 
I will follow up with the TimesTen team, but I'm not personally aware they have supported .NET Core yet.

**Comment by ozzioma** [comment]
@alexkeh ok thanks.

**Comment by alexkeh** [comment]
Got a quick answer back from the team.

TimesTen supports Java 11 and unmanaged ODP.NET. So no, .NET Core support at this time.

**Comment by ozzioma** [comment]
Ok thanks. 
Any timeline for .Net Core support?

**Comment by alexkeh** [comment]
There is no public timeline yet.
