### ISSUE TITLE
[Question] why do you use reader.Dispose() ?

### ISSUE THREAD

**Issue by MaherJendoubi** [oracle/dotnet-db-samples#116]

**Comment by alexkeh** [comment]
It's always a good idea to close/dispose all objects created. Under high loads, the garbage collector may not dispose these objects in a fast enough manner, which leads to memory accumulation.

**Comment by MaherJendoubi** [comment]
`using var con = new OracleConnection(conString);
        using OracleCommand cmd = con.CreateCommand();
        try
        {
            con.Open();
            cmd.CommandText = "select count(*) from table_test";
            OracleDataReader reader = cmd.ExecuteReader();
            while (reader.Read()) { Console.WriteLine("result = " + reader.GetString(0)); }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
        }`

**Comment by MaherJendoubi** [comment]
I used the code that code and there is no need to dispose the reader since you are using using for OracleConnection and OracleCommand. I stressed that piece of code and it doesn't lead to memory accumulation.

**Comment by alexkeh** [comment]
In our sample code, we try to use recommended coding practices even if some of them may never be consequential.

Also, GC behavior can change release to release. How well it works in one release could change in the next release.

**Comment by sungam3r** [comment]
Obviously because `OracleDataReader` inherits [IDataReader](https://docs.microsoft.com/en-us/dotnet/api/system.data.idatareader?view=netstandard-2.0)

**Comment by MaherJendoubi** [comment]
Yes, but the using statement is doing a dispose https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement#remarks

**Comment by sungam3r** [comment]
In the example above, only two out of three objects are disposed. I don't understand what your link should demonstrate.

**Comment by MaherJendoubi** [comment]
The two objects that will be disposed are con and cmd. So, if cmd is disposed then reader will be disposed because
OracleDataReader reader = cmd.ExecuteReader();

**Comment by sungam3r** [comment]
This is in a single specific example. In general, these objects can exist indefinitely, especially a connection.

**Comment by sungam3r** [comment]
It is the responsibility of the caller to destroy objects when they are no longer required.

**Comment by MaherJendoubi** [comment]
I got it. thanks a lot @sungam3r and @alexkeh
