### ISSUE TITLE
NRE on DataAdapter.Update

### ISSUE THREAD

**Issue by wahmedswl** [oracle/dotnet-db-samples#119]
Hi, setting ```DataAdapter.UpdateBatchSize``` greater than Row count result in NRE. Is this by-design or anything missing?

Thanks

**Comment by alexkeh** [comment]
Which ODP.NET version and type do you experience this in: core, managed, or unmanaged?

**Comment by wahmedswl** [comment]
Hi, getting in Managed driver for .NetFramework. v4.122.10

![image](https://user-images.githubusercontent.com/15020561/98919653-e785f900-24f0-11eb-8284-356cee977cfc.png)

Thanks

**Comment by alexkeh** [comment]
@wahmedswl 
Thanks for reporting this error. I was able to reproduce it and filed bug 32149083 to track this issue.

**Comment by wahmedswl** [comment]
Thanks @alexkeh, looking forward to the fix. Is there any work-around?

**Comment by alexkeh** [comment]
You could track the number of rows modified and set your UpdateBatchSize to that value or lower.

**Comment by alexkeh** [comment]
This bug is fixed in managed ODP.NET 19.10.1.
