### ISSUE TITLE
 .NET Standard 2.0 support?

### ISSUE THREAD

**Issue by odyright** [oracle/dotnet-db-samples#12]

**Comment by alexkeh** [comment]
ODP.NET Core supports .NET Standard 2.0.

**Comment by odyright** [comment]
hello @alexkeh please could you give us a Tuto or a link of how to handle as well "ODP.NET" with ".NET Standard 2.0".. (best practice) ?
When i Added to my .NET Standard 2.0 project it gives: incompatibility in list of error's window.
best regards!

**Comment by alexkeh** [comment]
You should be able to create a Visual Studio .NET Standard class library project and then add the ODP.NET Core assembly to the project. What errors are you receiving?

**Comment by odyright** [comment]
Hello @alexkeh Sorry for the delay..
![incompatibility](https://user-images.githubusercontent.com/4316506/45265122-30842380-b436-11e8-9579-810ebb3383cf.png)

**Comment by alexkeh** [comment]
Your project includes managed ODP.NET, which does NOT support .NET Standard. Only ODP.NET Core does. Search for Oracle.ManagedDataAccess.Core. It's currently in beta, but will shortly be in production. ODP.NET Entity Framework Core beta will follow the ODP.NET Core production release.

**Comment by odyright** [comment]
Thank you for the precision

**Comment by odyright** [comment]
hello alex, i worked with what you provided above.. but i'm still stucked. 
the **ODP.NET Core** doesn't support the "**UseOracle()**" method/definition. for **DbContextOptionsBuilder**??
![oracleefcore](https://user-images.githubusercontent.com/4316506/45546693-91807280-b80d-11e8-8a25-48cd112f030d.PNG)

**Comment by alexkeh** [comment]
ODP.NET Core doesn't support EF Core APIs yet, which is why the method isn't currently supported. Please wait for the EF Core beta.

**Comment by odyright** [comment]
OOOOOOOOOOPPSSSSSS...! We love Oracle's stuff. But is there any other alternative?

**Comment by alexkeh** [comment]
If you need something right now, you can use the DevArt provider. https://www.nuget.org/packages/Devart.Data.Oracle.EFCore/

**Comment by odyright** [comment]
Thanks for the suggestion ..but devart had to be installed and it's not free.

**Comment by akghasemi** [comment]
HI, I have this problem also. the problem is that when you reference the library that you create from a .NET core application then it is fine but if you reference the library from a .NET framework application then oracle assembly returns Could not load file or assembly 'Oracle.ManagedDataAccess, Version=2.0.19.1, Culture=neutral, PublicKeyToken=89b483f429c47342' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.
If you say that oracle support .NET standard 2.0 then it should work in all frameworks that implement .NET standard 2.0 , for example .NET framework 4.7.1  implements .NET standard 2.0 , so why oracle Core doesn't support it?

**Comment by alexkeh** [comment]
@akghasemi 
Based on the public key token, you are using managed ODP.NET, which is not .NET Standard compliant. What you need is ODP.NET Core, which is .NET Standard 2.0 compliant. Here's where to download it from NuGet Gallery.

https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/

The namespace (Oracle.ManagedDataAccess) and assembly (Oracle.ManagedDataAccess.dll) for both providers ar the same. The important thing to look for when you download ODP.NET Core from NuGet is the name: Oracle.ManagedDataAccess.Core.

**Comment by akghasemi** [comment]
@alexkeh 

I am referencing the  Oracle.ManagedDataAccess.Core in project but the host application which references  these standard library is .NET framework so in the host application I am using Oracle.ManagedDataAccess but when I run the application and I try to access the methods from the standard library I get the error I have mentioned

**Comment by alexkeh** [comment]
My recommendation is to move to ODP.NET Core in your host app from managed ODP.NET. Both providers have virtually the same API set and functionality. Both providers essentially have the same code base.

**Comment by lasred** [comment]
@alexkeh 

Hi Alex,  I know you stated above that 'ODP.NET Core supports .NET Standard 2.0.'

**Comment by alexkeh** [comment]
ODP.NET Core does not support Entity Framework 6.

**Comment by lasred** [comment]
Right now, our target framework is Net Standard 2.0 which I understand isn't compatible with Oracle.ManagedDataAccess(From Oracle's library for Entity framework 6).

Is there another .Net standard we could target that would be compatible with Oracle.ManagedDataAccess.

The reason we want this compatibility is we want to build around a feature that is available in Entity Framework 6 - (Logging and Intercepting database operations) - https://docs.microsoft.com/en-us/ef/ef6/fundamentals/logging-and-interception

**Comment by alexkeh** [comment]
Unfortunately, we don't have another provider that is .NET Standard 2.0 compliant.

**Comment by lasred** [comment]
Thanks. Do you happen to have a list of .Net standards/frameworks that are compatible with Oracle.ManagedDataAccess?

**Comment by alexkeh** [comment]
ODP.NET Core is .NET Standard 2.0 compliant. Managed ODP.NET is for .NET FW only. It is not .NET Standard compliant.

**Comment by last-Programmer** [comment]
It is not .net standard 2.0 compliant. when i build it in the xmarin ios project i get error  ResourcePermissionBase Class link error which is only available in .net core. Please make odp .net core .net standard compliant.
