### ISSUE TITLE
PerformanceCounters for Linux

### ISSUE THREAD

**Issue by sungam3r** [oracle/dotnet-db-samples#123]
Hi. I'm trying to figure out if I can use something like Performance Counters for Oracle.ManagedDataAccess.Core on Linux. I'm interested in connection pooling counters:
![изображение](https://user-images.githubusercontent.com/21261007/99412866-3de6a380-2906-11eb-8513-46a117dbae65.png)

I see the use of Performance Counters APIs in the source code and was able to make sure it creates counters in PerfMon but it is all Windows story. Will this work on Linux? What tools should I use? Is there any documentation? Thanks for the advice.

**Comment by alexkeh** [comment]
No, ODP.NET performance counters are Windows only as noted in the [doc](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/featConnecting.html#GUID-4FA1C8D3-195B-4D7A-9E9D-9FB74C7F5312):

> ODP.NET performance counters are available on Windows platforms only.

The restriction lies with the underlying dependency of [System.Diagnostics.PerformanceCounter being Windows only](https://devblogs.microsoft.com/dotnet/announcing-the-windows-compatibility-pack-for-net-core/). When MS ports this class to Linux in .NET Core, ODP.NET Core will likely be able to do the same.

**Comment by sungam3r** [comment]
Thanks.

> When MS ports this class to Linux in .NET Core, ODP.NET Core will likely be able to do the same.

I think most likely this will never happen because they have developed a new replacement API - [Event Counters](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/event-counters):
> EventCounters were added as a cross-platform alternative to the "performance counters" of the .NET Framework on Windows.

`dotnet-counters` cross-platrofm tool works exactly with EventCounters. Do you have any plans to do real cross-platform monitoring?

**Comment by sungam3r** [comment]
Note that EventCounters APIs exist since .NET Standard 1.5

**Comment by alexkeh** [comment]
We'll take a look. 

On a side note: [SqlClient is still working on implementing EventCounters](https://github.com/dotnet/SqlClient/issues/523). They don't have a definitive planned delivery date yet.

**Comment by sungam3r** [comment]
Good. So you have an example.
