### ISSUE TITLE
New Sample Request: UPDATE .. RETURNING ... BULK COLLECT INTO

### ISSUE THREAD

**Issue by pburrows** [oracle/dotnet-db-samples#124]
Can you add an example of calling an UPDATE statement and returning the modified records using the RETURNING..BULK COLLECT INTO clause?

**Comment by alexkeh** [comment]
Here's [sample code](https://stackoverflow.com/questions/10124548/odp-net-update-returning-into-multiple-rows-parameter-type/10212178) showing ODP.NET with RETURNING BULK COLLECT INTO that a developer demonstrated on SO.
