### ISSUE TITLE
Oracle throws BinaryFormatter exception after upgrading to the latest version 2.19.100 at net5.0

### ISSUE THREAD

**Issue by zqlovejyc** [oracle/dotnet-db-samples#125]
When I use Dapper QueryFirstOrDefaultAsync<T> method, throw the following exception:

System.TypeInitializationException: The type initializer for 'OracleInternal.ServiceObjects.OracleConnectionImpl' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Oracle.ManagedDataAccess.Types.TimeStamp' threw an exception.
 ---> System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at OracleInternal.Common.OracleTimeZone.GetInstance()
   at Oracle.ManagedDataAccess.Types.TimeStamp..cctor()
   --- End of inner exception stack trace ---
   at Oracle.ManagedDataAccess.Types.TimeStamp.InitializelatestTZversion()
   at OracleInternal.ServiceObjects.OracleConnectionImpl..cctor()
   --- End of inner exception stack trace ---
   at OracleInternal.ServiceObjects.OracleConnectionImpl..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at OracleInternal.ConnectionPool.PoolManager`3.CreateNewPR(Int32 reqCount, Boolean bForPoolPopulation, ConnectionString csWithDiffOrNewPwd, OracleConnection connRefForCriteria, String instanceName, List`1 switchFailedInstNames)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()

**Comment by alexkeh** [comment]
[.NET 5.0 now limits which data types are allowed to be used in DataSet and DataTable by default](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dataset-datatable-dataview/security-guidance).

To let Oracle types be used in DataSet/DataTable, call the OracleConfiguration.AddOracleTypesDeserialization() method. If that doesn't work, can you share your project with me so that I can take a look at it?

Some more info about this new API is my [blog post on ODP.NET 19.10](https://medium.com/@alex.keh/announcing-odp-net-19-10-release-new-net-5-and-bulk-copy-support-be6f395155c9).

**Comment by zqlovejyc** [comment]
When I'm done with it OracleConfiguration.AddOracleTypesDeserialization (), still throw the above exception, but net3.1 is normal, using the Dapper QueryFirrstOrDefaultasync<T> method;

**Comment by GoLo1992** [comment]
> [.NET 5.0 now limits which data types are allowed to be used in DataSet and DataTable by default](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dataset-datatable-dataview/security-guidance).
> 
> To let Oracle types be used in DataSet/DataTable, call the OracleConfiguration.AddOracleTypesDeserialization() method. If that doesn't work, can you share your project with me so that I can take a look at it?
> 
> Some more info about this new API is my [blog post on ODP.NET 19.10](https://medium.com/@alex.keh/announcing-odp-net-19-10-release-new-net-5-and-bulk-copy-support-be6f395155c9).

I tried. It didn't work
My solution is:
Add the following lines of code to the csproj file:
<PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>
</PropertyGroup>

**Comment by zqlovejyc** [comment]
> > [.NET 5.0 now limits which data types are allowed to be used in DataSet and DataTable by default](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/dataset-datatable-dataview/security-guidance).
> > To let Oracle types be used in DataSet/DataTable, call the OracleConfiguration.AddOracleTypesDeserialization() method. If that doesn't work, can you share your project with me so that I can take a look at it?
> > Some more info about this new API is my [blog post on ODP.NET 19.10](https://medium.com/@alex.keh/announcing-odp-net-19-10-release-new-net-5-and-bulk-copy-support-be6f395155c9).
> 
> I tried. It didn't work
> My solution is:
> Add the following lines of code to the csproj file:
> `<PropertyGroup>`
> `<TargetFramework>net5.0</TargetFramework>`
> `<EnableUnsafeBinaryFormatterSerialization>true</EnableUnsafeBinaryFormatterSerialization>`
> `</PropertyGroup>`

I also used this solution

**Comment by alexkeh** [comment]
If someone can publish a project that reproduces the problem, the Oracle .NET team can debug it. You can also email the C# files to dotnet_us(at)oracle.com for us to receive them.

**Comment by zqlovejyc** [comment]
> If someone can publish a project that reproduces the problem, the Oracle .NET team can debug it. You can also email the C# files to dotnet_us(at)oracle.com for us to receive them.


[OracleTest.zip](https://github.com/oracle/dotnet-db-samples/files/5577039/OracleTest.zip)

**Comment by alexkeh** [comment]
@zqlovejyc 
Thanks! I'll take a look at this.

**Comment by alexkeh** [comment]
I can reproduce the problem with the test case. I filed bug 32184726 with the details. The Oracle .NET dev team will review the bug and investigate the root cause.

**Comment by alexkeh** [comment]
We're testing a likely fix for the issue. We plan to deliver a new ODP.NET Core version with the fix on NuGet Gallery in the very near future.

**Comment by alexkeh** [comment]
[ODP.NET Core 2.19.100](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.19.100) is now available on NuGet Gallery. It fixes the BinaryFormatter bug,.

**Comment by zqlovejyc** [comment]
> [ODP.NET Core 2.19.100](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.19.100) is now available on NuGet Gallery. It fixes the BinaryFormatter bug,.

Thank you very much.

**Comment by sungam3r** [comment]
@alexkeh Do you mean 2.19.101 ?

**Comment by alexkeh** [comment]
Yes, I meant [ODP.NET Core 2.19.101](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.19.101) has the fix. Sorry about that.

**Comment by mallsopmtool** [comment]
just fyi i was gooling as I had also received this error, but the reason was i had pasted an old supportedRuntime version in my app.config.
