### ISSUE TITLE
ManagedDataAccess — ExecuteStream vs ExecuteReader performance

### ISSUE THREAD

**Issue by tleb** [oracle/dotnet-db-samples#127]
Hi,

I have performance issues using the `Oracle.ManagedDataAccess.Core` NuGet package on NET5.0. Keeping the connection string & request the same, using `OracleCommand.ExecuteStream()` finishes in ~10s while iterating on the result using `OracleCommand.ExecuteReader()` finishes in ~300s. Using a DataSet & OracleDataAdapter is slow too. Here are the two sources (everything inbetween angle brackets are actual values):

```c#
// uses ExecuteStream()
using var conn = new OracleConnection(@"Data Source = (DESCRIPTION =
(ADDRESS = (PROTOCOL = TCP)(HOST = <HOST>)(PORT = <PORT>))
(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = <SERVICE_NAME>))
); User Id=<ID>; Password=<PW>;");
conn.Open();

OracleCommand cmd = new OracleCommand("SELECT <COLUMN> FROM <TABLE>", conn);
cmd.CommandType = CommandType.Text;

cmd.XmlCommandType = OracleXmlCommandType.Query;
using var stream = cmd.ExecuteStream();
using var fileStream = System.IO.File.OpenWrite("stream.txt");
stream.CopyTo(fileStream);
```

```c#
// uses ExecuteReader()
using var conn = new OracleConnection(@"Data Source = (DESCRIPTION =
(ADDRESS = (PROTOCOL = TCP)(HOST = <HOST>)(PORT = <PORT>))
(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = <SERVICE_NAME>))
); User Id=<ID>; Password=<PW>;");
conn.Open();

OracleCommand cmd = new OracleCommand("SELECT <COLUMN> FROM <TABLE>", conn);
cmd.CommandType = CommandType.Text;

ulong i = 0;
using (OracleDataReader reader = cmd.ExecuteReader())
{
    while (reader.Read())
        i++;
}
System.Diagnostics.Debug.WriteLine(i);
```

The table contains about 33k rows, the column selected contains strings that are of variable length but nothing above 100 characters of length. It takes about 33 seconds in Oracle SQL Developer for the same request.

I tried enabling tracing but no success. I set `OracleConfiguration.TraceLevel` and `TraceFileLocation` earlier in the program then check they have the right value just before `new OracleConnection()`, and they have but it does nothing. I set `TraceFileLocation` to a child name inside the project directory so no permission issues.

I also tried using `OracleDataAdapter` & `DataSet` but it is also really slow. Processing the query result using `ExecuteReader()` would be the ideal solution but I've run out of ideas to solve this performance issue. Any suggestions? Hoping I did not forget any information that could be useful to resolve this.

Thank you!

**Comment by alexkeh** [comment]
Is this a new issue when you upgraded the app to use .NET 5 or is this a brand new app? The performance issue could be due to how the data is retrieved and perhaps some data conversion that occurs. If you are selecting XmlTypes from the DB and they are being converted into .NET strings, then this conversion may be slow depending on the size of the data. With the streaming, you would be avoiding this conversion.

Having the trace would be helpful in identifying what activity ODP.NET is spending the most time on. I'm not sure why tracing isn't working. What OS are you running .NET Core on?

**Comment by alexkeh** [comment]
Soft closing issue for now. If there's additional info to add, I'll rep-open it.
