### ISSUE TITLE
WinForms designer, .Net5 and Oracle.ManagedDataAccess.Core - "does not have a site"

### ISSUE THREAD

**Issue by sapr9x3** [oracle/dotnet-db-samples#128]
If I create a new winforms project with .Net5
Then Install Oracle.ManagedDataAccess.Core. 
Then create a new form. 
Then drag OracleDataAdapter from toolbox and drop to the form. 
This new OracleDataAdapter does not appear in the designer.
Then I just try to save the form. 
I get an error message box 
> Component 'Oracle.ManagedDataAccess.Client.OracleDataAdapter' does not have a site.

Form files have not been saved.

**Comment by alexkeh** [comment]
@sapr9x3 I tested your instructions and I can replicate the issue. Let me follow up with  my team on this. 

cc: @christianshay

**Comment by alexkeh** [comment]
It looks like the Oracle.ManagedDataAccess objects you see in the designer belong to managed ODP.NET, not ODP.NET Core.

**Comment by sapr9x3** [comment]
Do you mean objects in the toolbox? I've checked "Choose Items" again. There was a strange fact - you are right, ManagedDataAccess (not .Core) was enabled, although I sure that I choosed .Core. 
Ok, let it be.
Currently, I get the stable result in "Choose Toolbox Items" 
![image](https://user-images.githubusercontent.com/32381969/101713782-11c4d980-3ae4-11eb-8c27-181b6d66346d.png).
Nothing changes:
> Component 'Oracle.ManagedDataAccess.Client.OracleDataAdapter' does not have a site.

I've almost upgraded a big winforms project from .Net Framework 4.8 to 5.0. All errors are fixed. Application works in runtime perfectly. I believe this is last problem, but I have no idea how to resolve it. 

There is yet another variation of this isuue. Any form in the project which contains an Oracle component, is not opened in the designer at all.

**Comment by sapr9x3** [comment]
Is there any news?

**Comment by sapr9x3** [comment]
Happy New Year  Oracle .Net Team! It is very important for me to get some information about this issue. Please, provide something. Thank you.

**Comment by alexkeh** [comment]
Hi @sapr9x3,

@christianshay and the ODT team is looking into this.

**Comment by alexkeh** [comment]
@sapr9x3 I got confirmation from the Oracle Developer Tools team that they are not supporting ODP.NET Core tool box controls.
