### ISSUE TITLE
Exception: use Oracle.ManagedDataAccess.Core (2.19.100) on asp.net api .net 5

### ISSUE THREAD

**Issue by thanhnamrei** [oracle/dotnet-db-samples#129]
I use this code but throw exception at oracle.Open() : System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation
```
var connectionString = "Data Source= xx";
var oracle = new OracleConnection();
oracle.ConnectionString = connectionString;
if (oracle.State == ConnectionState.Closed) oracle.Open();
 // TODO
oracle.Close();
```

**Comment by alexkeh** [comment]
Can you post the inner exception and full stack trace?

**Comment by alexkeh** [comment]
Closing for now. Will re-open if any new diagnostics or problem description is received.

**Comment by thanhnamrei** [comment]
![image](https://user-images.githubusercontent.com/62831022/103752699-9f8cd980-503c-11eb-820c-04c9a573b8cd.png)
![image](https://user-images.githubusercontent.com/62831022/103752780-baf7e480-503c-11eb-94ac-642e3a98d1bb.png)
![image](https://user-images.githubusercontent.com/62831022/103752941-eed30a00-503c-11eb-9017-48a8a85af79d.png)

**Comment by alexkeh** [comment]
This is the same issue as #125. We plan to deliver a fix this month.

**Comment by thanhnamrei** [comment]
thanks u
