### ISSUE TITLE
how to remove specific user sessions from oracle v$session table on dot net project logout

### ISSUE THREAD

**Issue by pravinkharawade** [oracle/dotnet-db-samples#13]
In our dot net project user wise connection string is there. If 100 dedicated DB users (ie different connection string) login on system then 100 sessions get created.

I have used ClearPool and ClearAllPools method in dot net but again 1 session get created because of pooling.

Currently pooling is true in connection string and i want to keep it true only, because of performance.

On User logout i want to clear all session from V$session table.

Here I am using Visual Studio 2013 with Asp.Net C#.

Database - Oracle Database 11g Enterprise Edition

Database Connection Using ODP.NET Driver(Oracle.DataAccess.Client).

Please suggest.

**Comment by alexkeh** [comment]
Same question was asked on an OTN forum: https://community.oracle.com/thread/4173429

Closing this issue since the conversation is continuing on OTN.
