### ISSUE TITLE
Ef Core db function mapping to Oracle contains

### ISSUE THREAD

**Issue by wireless90** [oracle/dotnet-db-samples#136]
Hi my oracle version is 12c release 12.1.0.2.0.

**Nugets**
Oracle ef core 3.19.80
Ef core 3.1.6

I tried mapping oracles in built to_date and LENGTH functions to ef core, they worked. However mapping Oracle's contains produces an sql which results in a "Invalid Relational Operator"

`SELECT * FROM TABLE WHERE CASE WHEN CONTAINS(NAME, 'ASD') THEN 1 ELSE 0 END > 0`

First I created a static function that maps to the signature of Oracle Contains.
```cs
public static class OracleDbFunctions
{
     public static int Contains(string column, string text)=> throw new NotSupportedException();
}

```
Then I register it in my dbcontext.
```cs
MethodInfo m = typeof(OracleDbFunctions).GetMethod(nameof(OracleDbFunctions.Contains));

modelBuilder
.HasDbFunction(m)
.HasName("CONTAINS")
.HasSchema("");
```

Then when I call it,
```cs 
var result = dbcontex.Animals.Where(x => OracleDbFunctions.Contains(x.Name, "ASD") > 0).ToList(); 
```

the above ef statement produces

`SELECT * FROM TABLE WHERE CASE WHEN CONTAINS(NAME, 'ASD') THEN 1 ELSE 0 END > 0`

which results in a

 "Invalid Relational Operator"

**Comment by alexkeh** [comment]
Thanks for reporting the issue. I've filed Bug 32350901 to track it. The Oracle team will review the problem.

**Comment by lhchew** [comment]
> Thanks for reporting the issue. I've filed Bug 32350901 to track it. The Oracle team will review the problem.

Hi Alex, any update on this bug?

**Comment by alexkeh** [comment]
@lhchew Since the bug was reported late in our current dev cycle, it is unlikely to make it into our upcoming release. We'll schedule bug fixes for our next patch release after Oracle EF Core 5 is released.

**Comment by alexkeh** [comment]
This bug has been fixed and will be delivered in the Oracle EF Core 21.3 release.
