### ISSUE TITLE
Is there a way to auto convert all Number(3,0) to Int16

### ISSUE THREAD

**Issue by mannok** [oracle/dotnet-db-samples#137]
Existing Fluent API/Data Annotation methods can only do it for specified column. Just like OP mentioned  [here](https://github.com/oracle/dotnet-db-samples/issues/60)

What I needed is a way to automatically map all Number(3,0) to Int16 (especially for the attributes of the entity, I hope that I can change those datatype from `byte` to `int`) to avoid casting problem. 

` modelBuilder.Entity<Item>().Property(t => t.ItemLoc).HasColumnType("NUMBER(5)");` has done nothing, `ItemLoc` is still `byte` after scaffolding again and this statement will be overwritten by scaffold.

Any help provided will be appreciated. Thanks!

**Comment by alexkeh** [comment]
Do you mean you want a NUMBER(3,0) to map to Int16 as the by convention mapping?

**Comment by mannok** [comment]
@alexkeh Thank you for promptly reply.

Yes, this is what I mean. (I have corrected my words)

**Comment by mannok** [comment]
Anyone can help me out?    My project stuck here... :(

**Comment by alexkeh** [comment]
Oracle EF Core doesn't have a current method to change data type mapping globally.

I'll leave the issue open for now in case anyone in the community has a proposed solution.

**Comment by mannok** [comment]
@alexkeh As a workaround, is there a way to change an existing entity's data type and run `Scaffold-DbContext` without overwritting the data type back to the default one?

**Comment by alexkeh** [comment]
I believe that is what Fluent API and Data Annotations are intended for if I understand your question correctly. They allow you to dictate what specific data type you want the DB to use for the .NET class' data type.

**Comment by mannok** [comment]
@alexkeh However, Seems that there isn't a function in Fluent API that allow me to amend a specific property's data type. Or did I miss it if they are really exist?

**Comment by alexkeh** [comment]
Sorry, I was thinking of migrations. I don't know if there's a way to limit what scaffolding overwrites. If there's a generic way to do this, most likely Oracle EF Core also supports it.

**Comment by mannok** [comment]
Migration works, but only for Code-First Approach. Any suggestion for DB first?

**Comment by alexkeh** [comment]
I can't think of any. However, I'm not an EF Core expert.

**Comment by mannok** [comment]
Besides, I think this may not caused by EF Core.   Seems that it is caused by ODP .NET Core. 

In .NET version, there is a edmmapping that we can configure in `app.config`. We can set how should db type map with entity type like [here](https://docs.oracle.com/database/121/ODPNT/entityDataTypeMapping.htm#ODPNT8300). Does .NET Core version of ODP .NET provide a way for us to do such configure? Thanks

**Comment by alexkeh** [comment]
Not in Oracle EF Core at this time.

**Comment by alexkeh** [comment]
I filed Bug/ER 32633191 to track this request.

Moving the discussion to #157 as it more succinctly and broadly covers this feature request. If the ER is completed, it would address the broader request for customized default mappings.
