### ISSUE TITLE
Add years with double fails in local nl-NL (Oracle EF Core Version 3.19.80)

### ISSUE THREAD

**Issue by anoordover** [oracle/dotnet-db-samples#139]
I have a table with two date-field, Datum1 and Datum2.
The following statement fails because of the comma in de SQL (-0,1).

                CultureInfo.CurrentCulture = new CultureInfo("nl-NL");
                var test = dbContext.TestTabels
                    .Where(r => r.Datum1.AddDays(-0.1) < r.Datum1)
                    .ToList();

fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (96ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
      SELECT "t"."ID", "t"."DATUM1", "t"."DATUM2"
      FROM "TEST_TABEL" "t"
      WHERE ("t"."DATUM1" + -0,1) < "t"."DATUM1"

Changing the CultureInfo to e.g. en-EN generates the correct statement.

**Comment by alexkeh** [comment]
Thanks for reporting! 

I've been able to reproduce the error. I've filed bug 32373425 to track the issue and to resolve it.

**Comment by alexkeh** [comment]
This bug has been fixed in the Oracle EF Core 5.21.1 release.
