### ISSUE TITLE
Decimal scale change between Oracle.ManagedDataAccess v19.6 and 19.7

### ISSUE THREAD

**Issue by jasonwnz** [oracle/dotnet-db-samples#140]
There seems to be an change between versions 19.6 and 19.7 of Oracle.ManagedDataAccess relating to the default decimal scale when zeros are involved. The new behaviour is also in Oracle.ManagedDataAccess.Core. I can't find any documentation on this change to know whether it's an intended change, or a bug?

e.g.

v19.6:
select 1.1 as aaa from dual returns 1.10
select 1.10 as aaa from dual returns 1.10
select 1.100 as aaa from dual returns 1.10

v19.7 
select 1.1 as aaa from dual returns 1.1
select 1.10 as aaa from dual returns 1.1
select 1.100 as aaa from dual returns 1.1

Sample console app code – run against both versions of Oracle.ManagedDataAccess:

```
static void Main(string[] args)
{
	var queries = new System.Collections.Generic.List<string>
	{
		{ "select 1.1 as value from dual" },
		{ "select 1.10 as value from dual" },
		{ "select 1.100 as value from dual" }
	};
	
	Oracle.ManagedDataAccess.Client.OracleConnection con = new Oracle.ManagedDataAccess.Client.OracleConnection(*** CONNECTION STRING ***);
	try
	{
		con.Open();

		foreach (string query in queries)
		{
			Oracle.ManagedDataAccess.Client.OracleCommand cmd = new Oracle.ManagedDataAccess.Client.OracleCommand
			{
				CommandText = query,
				Connection = con
			};

			using (Oracle.ManagedDataAccess.Client.OracleDataReader dr = cmd.ExecuteReader())
			{
				if (dr.HasRows)
				{
					while (dr.Read())
						System.Console.WriteLine(System.String.Format($"{query}\t = {dr["value"]}"));
				}
			}
		}
	}
	finally
	{
		con.Close();
	}

	System.Console.ReadLine();
}
```

Thanks

**Comment by alexkeh** [comment]
It's an intended change that is considered a bug fix in that the new behavior aligns with how other Oracle clients drop trailing zeros, such as SQL*Plus. You can restore past behavior programmatically using code similar to the following:

```
using System;
using Oracle.ManagedDataAccess.Types;

class T
{
  static void Main()
  {
    OracleDecimal odec = new OracleDecimal(1.1);
    Console.WriteLine(odec.ToString()); // outputs : 1.1
    Console.WriteLine(odec.Value.ToString("N2")); // outputs : 1.10
  }
}
```

As there are some apps that want the old behavior, but do not want to modify their code significantly, ODP.NET will add a new configuration property to keep trailing zeros after the decimal point.

**Comment by jasonwnz** [comment]
Thanks for the info. Can you give any details about the new configuration property to restore the old behavior? Does it exist already or are there plans to add it?

**Comment by alexkeh** [comment]
It doesn't exist yet. We're working on the implementation. It'll likely be a Boolean that you set to true if you want to keep the previous behavior.

**Comment by jasonwnz** [comment]
Great - Does it have a planned release? We are upgrading to Oracle.ManagedDataAccess.Core but hit this issue and it's not feasible to make the widespread code changes needed, so hoping this new config property will be included in that package too. 

Will close this issue, thanks for your quick responses.

**Comment by alexkeh** [comment]
It's scheduled to be in a release by April at the very latest.
