### ISSUE TITLE
Implement Async versions of Ado.Net methods

### ISSUE THREAD

**Issue by Giorgi** [oracle/dotnet-db-samples#144]
Ado.Net classes such as `DbCommand`, `DbConnection` have async methods that aren't truly async and just execute the non-async versions and return their result. It would be nice if ODP.NET had a real implementation of those methods (the same way other database providers have) and was truly async.

**Comment by alexkeh** [comment]
@Giorgi This is a feature the dev team is working on. I'll have better visibility to when we can deliver this feature in the second half of this year. You can ask me then.

**Comment by iinuwa** [comment]
Hello @alexkeh, is there an update on this request?

**Comment by alexkeh** [comment]
Ping me back in a couple of months. We're busy shipping the next 21c release right now. Once done, we'll have more visibility which release we'll be able to slot async in as we continue to make progress.

**Comment by luboid** [comment]
Is there progress on the issue

**Comment by alexkeh** [comment]
@luboid 
We're making progress, but I don't have a public timeline to share just yet. There's a wide range of dates possible depending on how the testing goes. It won't be with our next major ODP.NET release at the end of the year. That one will have .NET 6 and EF Core 6 support. Once that release goes out, I should be able to provide a time range for release.

**Comment by ksantoso** [comment]
Hi @alexkeh , is there any update on the estimated timeline for this async release?

**Comment by alexkeh** [comment]
@ksantoso ODP.NET async is planned for release around the end of this year. It's part of our next major release.

**Comment by iinuwa** [comment]
To confirm, that's around Q4 2022?

**Comment by alexkeh** [comment]
CY Q4 2022 seems most likely at this time.

**Comment by ricardodemauro** [comment]
Hi @alexkeh. 

Just checking. Is it still planned for CY Q4 2022?

Thanks,

**Comment by alexkeh** [comment]
It's looking like the release will be past Q4 this year. ODP.NET async will be released alongside Oracle's next major DB release and that release is not looking like it will make it by the end of the year.

**Comment by BaraOne** [comment]
Q4 has started. Any updates on this?
Regards

**Comment by alexkeh** [comment]
ODP.NET async in managed and core versions will be released with Oracle DB 23c as announced during Oracle CloudWorld. The release won't be in Q4 2022 though. It will be sometime next year. Keep an eye out for when Oracle RTMs DB 23c.

**Comment by alexkeh** [comment]
If your team wants to try ODP.NET async, sign up to join the [Oracle DB 23c beta program](https://tinyurl.com/OracleBetaTesting). ODP.NET 23c (managed and core) will support .NET async await in for DB 19c and higher.

**Comment by will-scc** [comment]
Hi @alexkeh, can I confirm the following: is it also the case that Oracle.EntityFrameworkCore does not currently supported .NET async/await but should do in the 23c release and when it does _only_ for databases which are 19c and later?

**Comment by alexkeh** [comment]
That's correct. ODP.NET 23c will be the first to support async/await. ODP.NET 23c will support only DB 19c and higher.

**Comment by say25** [comment]
@alexkeh Is there a timeline or place we can follow to see when the 23C driver will leave private beta and/or be officially released?

**Comment by alexkeh** [comment]
@say25 When we have a public date for the ODP.NET 23c release, I'll announce it on [my blog](https://medium.com/@alex.keh) and the [Oracle .NET Twitter channel](https://twitter.com/oracledotnet). It's unlikely we'll publish a timeline for pre-production releases as those releases tend to be released when they meet specific quality metrics.

For 23c beta customers, ODP.NET 23c availability will be announced through the beta email updates.

**Comment by alexkeh** [comment]
ODP.NET Core and Managed ODP.NET 23.2 Dev Release are now available on NuGet Gallery with support for async. You can learn more about using [ODP.NET async here](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/featAsyncPipelining.html#GUID-27CA3823-92BA-489A-9356-9EAA7B86A4FE).

**Comment by say25** [comment]
@alexkeh and news on getting a production release published for 23?

**Comment by alexkeh** [comment]
@say25 First half of 2024.

All DB 23c server and client software will be released in production at the same time.
