### ISSUE TITLE
Using Transactions ORA-00900

### ISSUE THREAD

**Issue by GoLo1992** [oracle/dotnet-db-samples#146]
![image](https://user-images.githubusercontent.com/12096844/108586897-129fa480-738c-11eb-91ae-507c9fa462b0.png)
![image](https://user-images.githubusercontent.com/12096844/108586916-2ea34600-738c-11eb-89f6-d7b5b50daaf5.png)
[OracleDemo.zip](https://github.com/oracle/dotnet-db-samples/files/6014306/OracleDemo.zip)
[Traces.zip](https://github.com/oracle/dotnet-db-samples/files/6014307/Traces.zip)
There should be something wrong with savepoints!

**Comment by alexkeh** [comment]
@GoLo1992 I was able to run your test case successfully with the new Oracle EF Core 5 provider and Oracle DB 19c. The data was inserted by the transaction, but no error occurs in the application.

In the trace, I do see an ORA-00900 generated, but it does not stop the app from continuing on. 

It's not clear to me what problem you are experiencing. Can you provide more details?

**Comment by GoLo1992** [comment]
> @GoLo1992 I was able to run your test case successfully with the new Oracle EF Core 5 provider and Oracle DB 19c. The data was inserted by the transaction, but no error occurs in the application.
> 
> In the trace, I do see an ORA-00900 generated, but it does not stop the app from continuing on.
> 
> It's not clear to me what problem you are experiencing. Can you provide more details?

Although it does not stop the app from continuing on, check the source code of EF Core 5, executed an unnecessary SQL "RELEASE SAVEPOINT __EFSavePoint", it is suggested to optimize this problem.

**Comment by alexkeh** [comment]
I opened bug 32544334 to track this issue. We'll investigate eliminating the RELEASE SAVEPOINT call.

**Comment by alexkeh** [comment]
This bug has been fixed. The patch will be part of the next Oracle EF Core 5 release.

**Comment by GoLo1992** [comment]
@alexkeh OK
