### ISSUE TITLE
oracle.entityframeworkcore.5.21.1 的FirstOrDefault

### ISSUE THREAD

**Issue by doson2006** [oracle/dotnet-db-samples#149]
生成的语句为
SELECT XXX
FROM "SYS_USER" "s"
FETCH FIRST 1 ROWS ONLY

这个不能在11.2中使用，必须使用12c及以上？

**Comment by doson2006** [comment]
11.2.0.4 and above are required

**Comment by alexkeh** [comment]
Be sure to [set UseOracleSQLCompatibility to 11](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/EFCoreAPI.html#GUID-D237259B-0A8A-42D1-A142-1685AAC4178C).
