### ISSUE TITLE
Configuration Api and tnsnames.ora

### ISSUE THREAD

**Issue by wahmedswl** [oracle/dotnet-db-samples#15]
Hi, tnsnames.ora is still supported scenario or db related details need to be provided via configuration api as given in the 

https://github.com/oracle/dotnet-db-samples/blob/master/samples/dotnet-core/configuration-api/config-api.cs#L32

Thanks

**Comment by alexkeh** [comment]
Tnsnames.ora is still supported in ODP.NET Core. You can use tnsnames.ora and/or Configuration API. Not all the tnsnames.ora properties are supported with ODP.NET Core. The list of supported properties is found here: https://docs.oracle.com/en/database/oracle/oracle-data-access-components/18.3/odpnt/InstallCoreConfiguration.html#GUID-24C963AE-F20B-44B5-800C-594CA06BD24B
