### ISSUE TITLE
ORA-00904:标识符无效

### ISSUE THREAD

**Issue by doson2006** [oracle/dotnet-db-samples#151]
EFCORE 5.0    Table映射的实体类的属性名称如果不显式指定的话需要使用全大写的形式，不然会报错“ORA-00904:标识符无效”，
只能使用select * from "SYS_USER" where  "TRUE_NAME" ='XXX'，如何设置可以不使用引号，并且也支持小写字段名？

**Comment by alexkeh** [comment]
You can use the backslash (\\) escape character to indicate you wish to use a special character, such as a quotation in a regular expression.  For example:

SELECT * FROM  \\"MyMixedCaseTable\\"

**Comment by doson2006** [comment]
必须要带引号？

**Comment by alexkeh** [comment]
Yes, it must be quoted. In the DB itself, mixed case identifier names are quoted.
