### ISSUE TITLE
EF Core 5.0中的序列使用

### ISSUE THREAD

**Issue by doson2006** [oracle/dotnet-db-samples#152]
使用 UseHiLo("SEQ_SYSUSER") 为主键配置了序列，第1次执行插入时会有个取序列的语句 SELECT "SEQ_SYSUSER".NEXTVAL FROM DUAL，后面的9次 都不再有 取序列的SQL，但主键在增加，造成第11次插入的时候 会再有个取序列的动作，这时候再插入会跟第2次插入的主键冲突，请问这是什么原因?

**Comment by alexkeh** [comment]
You may be hitting one of two known issues documented in the README.

1. The 11.2 Oracle databases do not support default expression to reference any PL/SQL functions nor any pseudocolumns such as '<sequence>.NEXTVAL'. As such, HasDefaultValue() and HasDefaultValueSql() fluent APIs cannot be used in conjunction with 'sequence.NEXTVAL' as the default value, for example, if the Oracle database is 11.2. However, the application can use the UseIdentityColumn() extension method to have the column be populated with server generated values, even if the Oracle database is 11.2. Please read about UseIdentityColumn() for more details.

2. Extension methods related to SequenceHiLo is not supported, except for columns with Char, UInt, ULong, and UByte data types.

**Comment by doson2006** [comment]
My project does not use hasDefaultValue () and hasDefaultValuesQl (), but configuring the sequence of primary keys as follows, and then I have the problem 

`entityBuilder.Property(e => e.UserId)
                .HasColumnName("USER_ID")
                .UseHiLo("SEQ_SYSUSER");`


Oracle 11.2 does not support increment. How to use it

**Comment by alexkeh** [comment]
In EF Core 5, UseOracleIdentityColumn has been replaced with UseIdentityColumn.

**Comment by doson2006** [comment]
When I use useIdentityColumn (), the configuration is :
`entityBuilder.Property(e => e.UserId)
                .HasColumnName("USER_ID")
                .UseIdentityColumn();`

The generated SQL :
`DECLARE
TYPE "rSYS_USER_0" IS RECORD
(
"USER_ID" NUMBER(19)
);
TYPE "tSYS_USER_0" IS TABLE OF "rSYS_USER_0";
"lSYS_USER_0" "tSYS_USER_0";
v_RowCount INTEGER;
BEGIN

"lSYS_USER_0" := "tSYS_USER_0"();
"lSYS_USER_0".extend(1);
INSERT INTO "SYS_USER" ("CREATE_TIME", "CREATE_USER_ID", "CREATE_USER_NAME", "IS_SYSTEM", "PASSWORD", "REMARK", "SECRET_KEY", "STATE", "TEL", "TRUE_NAME", "USER_NAME")
VALUES (null, 0, , 0, , null, 111, 0, null, core-test, core-test)
RETURNING "USER_ID" INTO "lSYS_USER_0"(1)."USER_ID";
OPEN null FOR SELECT "lSYS_USER_0"(1)."USER_ID" FROM DUAL;
END;`



Error message is :
`Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01400: 无法将 NULL 插入 ("BASEMANAGE"."SYS_USER"."USER_ID")
ORA-06512: 在 line 13
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, Int64 internalInitialJSONFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)`

**Comment by alexkeh** [comment]
Are you using DB version 11.2? If so, did you set UseOracleSQLCompatibility to "11"?

It appears that the USER_ID value is not being auto-generated. If not 11.2, which DB version are you using? Do you have a simple test case that reproduces the behavior?

**Comment by doson2006** [comment]
the DB version is 11.2，this is git [https://github.com/doson2006/SSS.Base.FrameWork-EFCORE](url)

**Comment by doson2006** [comment]
@alexkeh Did you find the problem?

**Comment by GoLo1992** [comment]
@doson2006 ef core sequence used cache. the increment of sequence can be set to 1.
like this
```
protected virtual void OnOracleModelCreating(ModelBuilder modelBuilder)
{
    var sequences = modelBuilder.Model.GetSequences();
    foreach (var sequence in sequences)
    {
        sequence.IncrementBy = 1;
    }
}
```

**Comment by alexkeh** [comment]
@doson2006 I haven't hit the problem yet. I tried your test case against my local DB and was able to execute without error.

I'll try the test on an 11.2 DB this upcoming week.

**Comment by alexkeh** [comment]
@doson2006 I ran the simple test case against an 11.2 DB. I was able to create create three SYS_USER entries without encountering an error.

Do you want to email us the ODP.NET trace for when you run the simple test case? In this way, we can see what you are seeing since I can't reproduce the error.

Here's some instructions for [turning on ODP.NET tracing in EF Core](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/EFCoreClasses.html#GUID-D5D99935-D8AF-4E16-BD52-88B2A7537B84
).

**Comment by doson2006** [comment]
I solved the problem!
The primary key of Oracle 11.2 must specify the sequence name using UseHiLo()!
OnModelCreating() must be configured like this:
` protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasSequence("SEQ_SYSUSER");
            base.OnModelCreating(modelBuilder);
        }`

This enables the sequential SQL to be generated on each insert
`SELECT "SEQ_SYSUSER".NEXTVAL FROM DUAL `
