### ISSUE TITLE
Need the same Extension for VS Codium

### ISSUE THREAD

**Issue by gowthamraam** [oracle/dotnet-db-samples#155]
Need the same Extension for VS Codium

**Comment by alexkeh** [comment]
@christianshay Are there any plans to support Oracle Developer Tools for VS Code with VSCodium?

**Comment by christianshay** [comment]
VS Codium should work with our VSIX. Have you tried to download and manually install our VSIX? Also, I note that VS Codium has some doc about integrating with the VS Marketplace:
https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace
