### ISSUE TITLE
Got ORA-01418: specified index does not exist using Autonomous Database

### ISSUE THREAD

**Issue by stevefan1999-personal** [oracle/dotnet-db-samples#156]
I tried to initiate a migration of Identity Service to an Autonomous Database with TNS and admin location properly set, but the migration process is stuck with index creation:
```
fail: Microsoft.EntityFrameworkCore.Database.Command[20102]
      Failed executing DbCommand (140ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
      DROP INDEX "UserNameIndex"
Failed executing DbCommand (140ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
DROP INDEX "UserNameIndex"
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01418: specified index does not exist
```
I have no idea where to submit this issue to, but still this is probably the best place. I just don't know how to intercept this statement and put `IF EXIST` after `INDEX`.

**Comment by alexkeh** [comment]
Are you asking about [database interceptors](https://docs.microsoft.com/en-us/ef/core/logging-events-diagnostics/interceptors) in general or are you asking about how to intercept for your specific use case?

If it's the latter case, you can replace the CommandText with the SQL you want executed once you tag and find the query you want to be modified.
