### ISSUE TITLE
Database generated primary key value not set on entity after insert

### ISSUE THREAD

**Issue by iulianb** [oracle/dotnet-db-samples#158]
The tables in our database have a surrogate id column that is seeded from a sequence in an insert trigger. Something along the lines of:

```
before insert
on products
for each row
begin
  if :new.ID < 0 OR :new.ID IS NULL
  then :new.ID := product_seq.nextval;
  end if;
end;
``` 

Our legacy application was using EF6 and the new id was set on the entity after SaveChanges. It's not the case for EF Core. After some investigating we've discovered that EF6 uses a RETURNING statement after INSERT while EF Core is only doing an insert without reading the new id. Is it intended behavior? If it is, what would be the alternative for getting the newly inserted id into the entity?

Oracle 11g (11.2.0.3.0)
Microsoft.EntityFrameworkCore 3.1.8
Oracle.EntityFrameworkCore 3.19.80

**Comment by alexkeh** [comment]
Officially, the Oracle EF Core provider supports Oracle DB 11.2.0.4 and higher. It's possible that 11.2.0.3 works, just that we haven't tested to verify it.

Be sure to set the `UseOacleSQLCompatibility` to 11 and `UseOracleIdentityColumn` to "Enabled" if that is your intent. More details what these Oracle EF Core settings do is [here](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3.2/odpnt/EFCoreAPI.html#GUID-1F02D363-BD4B-4240-AE14-274DD6815BAD).

**Comment by iulianb** [comment]
We have enabled the `UseOracleIdentityColumn`. We have tested it prior to opening this issue but wasn't working due to our ids having negative values. Thank you for the advice!
