### ISSUE TITLE
I can not find Oracle.EntityFrameworkCore in nuget

### ISSUE THREAD

**Issue by GilVieira** [oracle/dotnet-db-samples#16]
following the example with ef core (_https://github.com/oracle/dotnet-db-samples/tree/master/samples/dotnet-core/ef-core_) I must install the package **Oracle.EntityFrameworkCore** in nuget, but I can not find it. Today I use .NET Identity + EF 6 + Oracle and I will need to migrate to .NET Core and I am not making progress.

Tks.

**Comment by alexkeh** [comment]
The Oracle EF Core NuGet package is not available yet. The beta will become available in the middle of this month. The Oracle .NET twitter account will announce beta and production availability. https://twitter.com/oracledotnet
