### ISSUE TITLE
Connection request timed out after 15 seconds

### ISSUE THREAD

**Issue by sungam3r** [oracle/dotnet-db-samples#166]
It seems that #126 has not been fixed for some cases even after Oracle.ManagedDataAccess.Core v2.19.101 release.

```
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
```
Elapsed when this error happens: 15.001  15.031   15.179   15.156   15.107 and so on a bit above 15 seconds timeout.
The connection pool does not appear to be exhausted. We don't explicitly size it, so I'm pretty sure the default is 100.

The example output from `OracleConnection.Dump` when this happened:
```
(DUMP)
(CP) =================================
(CP) Data Source=(DESCRIPTION=(ENABLE=BROKEN)(LOAD_BALANCE=off)(FAILOVER=on)
(TRANSPORT_CONNECT_TIMEOUT=10)
(ADDRESS=(PROTOCOL=tcp)(HOST=<address1>)(PORT=1526))
(ADDRESS=(PROTOCOL=tcp)(HOST=<address2>)(PORT=1526))
(CONNECT_DATA=(SERVICE_NAME=<name>)(FAILOVER_MODE=(TYPE=session)(METHOD=basic))));
User Id=<id>;Password=;
(CP) pmid=
55059565(CP) =================================
(CP) <name> , <name2>:
(CP)   list  (count:1) : (2962:4287:T:F:F:F:N:<name>::<name2>)

(CP)   queue (count:0) : 
```
Names were replaces.

**Comment by alexkeh** [comment]
I was able to use your connect descriptor and connect ODP.NET Core 2.19.110 to Oracle DB 19c without a connection request timeout. I just added my own hosts, service name and ports.

Can you try a couple things:
1) Increase your Connection Timeout value to be much higher, maybe 120 seconds. I've seen cases when the timeout is too low and there's another connection configuration problem that takes longer than 15 seconds to manifest itself as an error. 
2) Remove the FAILOVER settings in your connect descriptor and see if you can connect. That can verify if it's these failover settings directly related to the problem.

**Comment by sungam3r** [comment]
> ODP.NET Core 2.19.110

Did you mean 2.19.101 ?

OK, I'll try you suggestions.

**Comment by alexkeh** [comment]
2.9.110 is the latest version managed ODP.NET version. It's newer than 2.19.101.

I'm hoping trying out these two scenarios will provide more clues on the root cause.

**Comment by monty241** [comment]
It seems that "connection timeout" also occurs when using a wrong version of the assembly. In our case, instead of 3.1.21.1 (.net core), the error occurred when due to a build error either 3.21.100 or (.net framework) 4.122.21.1 DLL were present.  Somewhat confusing is that the managed driver DLL of Oracle.ManagedAccess.Core nuget package is also Oracle.ManagedAccess.dll.

A clear error occurs solely when the Oracle.ManagedDataAccess.dll is not present. 

Maybe Oracle internally calls some code for a number of times and even with internal errors always returns a generic "connection timeout" from an exception handler?

Fix was to use the correct version of the DLL.

**Comment by alexkeh** [comment]
The timeout occurs as managed ODP.NET is looking for libraries it expects in .NET FW, but is not part of .NET Core. Since the library is not found, the connection times out. There's an ER (35402151) to improve the error message so that the app knows it has the wrong ODP.NET provider type loaded.
