### ISSUE TITLE
.net standard 2.0 compatibility?

### ISSUE THREAD

**Issue by lscorcia** [oracle/dotnet-db-samples#168]
Hello, currently the NuGet package for Oracle.ManagedDataAccess.Core advertises its compatibility with .net standard 2.1.

We are slowly converting some applications from .net 4.7.2 to .net core using .net standard 2.0 as a common ground for logic libraries that are shared between older and newer applications, but we had to stop this effort because no published ODP.net Core version actually supports .net standard 2.0.
Is this something you have on your radar?

EDIT: I found https://github.com/oracle/dotnet-db-samples/issues/12 that seems to imply that at some point in time ODP.net Core was .net standard 2.0 compatible, but no downgrade helped here. I'm puzzled.

**Comment by alexkeh** [comment]
ODP.NET Core 19c is .NET Standard 2.0 compatible. ODP.NET Core 21c is .NET Standard 2.1 compatible. If you have a requirement to stay with .NET Standard 2.0, then use ODP.NET 19c.

**Comment by lscorcia** [comment]
Excellent! I just tried with v2.19.110 and it works great! I thought I had tried it before, but I must have done something wrong.
I don't know if v19 is still being maintained but if you ever have to release an update for that, it would be helpful if it was annotated with the appropriate framework dependency like the most recent version.

Thanks again for your very helpful reply! Now, on to the next dependency :-)

**Comment by alexkeh** [comment]
Oracle 19c version of products will remain supported through at least 2027.

The NuGet package does indicate that the it relies on at least .NET Core 2.x, which is why the version number begins with 2.x instead of 19. The ODP.NET Core 3.21.1 release requires at least .NET Core 3.

**Comment by lscorcia** [comment]
Sorry, I should have been clearer - I was referring to annotating the nuspec file for the package v2.19.110 with the netstandard2.0 dependency:
![immagine](https://user-images.githubusercontent.com/16761934/118365240-28dc8b80-b59c-11eb-9818-281d36fa6a87.png)

Like v3 does:
![immagine](https://user-images.githubusercontent.com/16761934/118365251-3560e400-b59c-11eb-86bc-419c987a839c.png)

**Comment by alexkeh** [comment]
The "Dependencies" section is indicative of requirements, not compatibility level unfortunately. NuGet won't let the user install the main package without the required packages.

ODP.NET 21c has .NET Standard 2.1 as a dependency because it does not work with earlier .NET Standard versions.
