### ISSUE TITLE
nuget not available :- "Oracle.EntityFrameworkCore"

### ISSUE THREAD

**Issue by rahul-network** [oracle/dotnet-db-samples#17]
Please let me know if package source target is different.

http://packagesource

**Comment by alexkeh** [comment]
The beta package is not available yet on nuget.org. When it becomes available, it will be announced on the web (https://www.oracle.com/database/technologies/appdev/dotnet.html) and Twitter (https://twitter.com/oracledotnet).

**Comment by rahul-network** [comment]
Thank you @alexkeh for very quick response. May i know how long will it take to release beta version ?
Because i want to start development one of my app.

**Comment by alexkeh** [comment]
Sometime in the next week or two.

**Comment by TroyTurley** [comment]
Is it available for download outside of NuGet? You guys have published sample that use it, so I assume it's available somewhere.

**Comment by gnanaravindhan** [comment]
Any tentative timeline? when EF Core Beta will be available?

**Comment by SIkebe** [comment]
@gnanaravindhan 
>Private beta is end of this month. Public beta begins November/December.

https://twitter.com/OracleDOTNET/status/1054464351816404993

**Comment by prisar** [comment]
what is ` Oracle.ManagedDataAccess.Core` package which is present in nuget with version 2.18.3

**Comment by alexkeh** [comment]
Oracle.ManagedDataAccess.Core is the Oracle data provider for .NET Core.

**Comment by alexkeh** [comment]
Currently, Oracle EF Core is in a private beta program. The only way to get the assembly right now is to join the beta program. If you wish to join the beta, send an email to dotnet_us(at)oracle.com.

We hope to share Oracle EF Core in a public beta program soon.

**Comment by soumunote** [comment]
I wish to join to `Oracle EF Core private beta program`.
And I sent an email to dotnet_us(at)oracle.com.

Thank you.

**Comment by alexkeh** [comment]
ODP.NET EF Core is now publicly available:
https://www.nuget.org/packages/Oracle.EntityFrameworkCore/
