### ISSUE TITLE
Is it possible to affect collation at DBContext level ?

### ISSUE THREAD

**Issue by mandm-pt** [oracle/dotnet-db-samples#174]
Hi,

I am trying to set the collation of my DbContext globally so I don't need to touch existing queries.
Is it possible to set collation using `modelBuilder.UseCollation("some collation");` or using other way so I can affect the behavior of the queries relative to case sensitive, without modifying database configurations?

Thanks,

Some references:
https://docs.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity
https://docs.oracle.com/en/database/oracle/oracle-database/19/nlspg/linguistic-sorting-and-matching.html#GUID-F1F6A1EC-7ABF-45DF-9901-40576313A2EF

**Comment by alexkeh** [comment]
Yes, Oracle EF Core supports UseCollation.

**Comment by mandm-pt** [comment]
Thanks @alexkeh for the quick reply. Is it possible for you to provide some examples how to do case sensitive/insensitive and accent sensitive/insensitive?
I've tried the following: 
* `modelBuilder.UseCollation("USING_NLS_SORT_CI");`
* `modelBuilder.UseCollation("USING_NLS_SORT");`
* `modelBuilder.UseCollation("BINARY_CI");`

I am using this version with EF core 5.0 `Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production`

Sorry if I am missing something very obvious.

Thanks

**Comment by alexkeh** [comment]
Sorry, I apologize. My testing team first informed me we had tests covering this scenario and the tests passed. After they took another look, they found the tests were not passing and there are open bugs around using collation.

At present, you can execute an ALTER SESSION first if you don't want to modify your existing queries. For example:

`db.Database.ExecuteSqlRaw("alter session set nls_sort = binary_ai");`
