### ISSUE TITLE
Application Continuity sample: database license requirements

### ISSUE THREAD

**Issue by chrisleadbeater** [oracle/dotnet-db-samples#175]
You should note somewhere that " Application Continuity is available with Oracle Database Enterprise Edition with a Real Application Clusters or Active Data Guard option license."

**Comment by alexkeh** [comment]
@chrisleadbeater I've documented the AC DB server requirements in the following blog post: https://medium.com/oracledevs/oracle-net-application-continuity-getting-started-34e7045e863

AC is also supported in RAC One Node and Autonomous DB, in addition to RAC and ADG.

**Comment by chrisleadbeater** [comment]
Thanks!
