### ISSUE TITLE
Oracle.EntityFrameworkCore support for .NET 6.0 and EF Core 6.0

### ISSUE THREAD

**Issue by williamclarkmcbride** [oracle/dotnet-db-samples#176]
Are there any plans to update Oracle EFCore to 6 before the general release in November? It would be really nice to be able to update our projects to .NET 6 as soon as it is released, since it's a long term support release and 5 will not be supported for much longer after that.

Oracle EFCore 5 wasn't released until February, so I was hoping there would be plans to release the new version at the same time as .NET 6 (or even earlier with a preview or release candidate build).

**Comment by alexkeh** [comment]
You can start using ODP.NET Core 21c with .NET 6 right now. Oracle has done some functional testing and we haven't seen any unique bugs with .NET 6 preview and ODP.NET.

It's very likely ODP.NET will be certified with .NET 6 the same month it's released. That was our experience with .NET 5. Oracle will conduct some validation once the official .NET 6 releases before making it official.

EF Core is more of a challenge as the provider model changes significantly with every release, unlike ADO.NET. Understanding and implementing those changes accurately is difficult without a spec. That's the primary reason for past delays. The spec would help all third-party EF Core provider writers to support the latest EF Core version more quickly. For Microsoft, it's a balancing act. Certainly, they could work on a (constantly-evolving) spec, but that would take resources away from other EF Core priorities. Hopefully, that explains why a delay exists. 

With all that said, we are on track to to release the Oracle EFC6 provider this year. I'll have a more formal statement of direction later on right after our next ODP.NET 21c update in about a month.

**Comment by alexkeh** [comment]
Here's the [ODP.NET for .NET 6 and EF Core 6 statement of direction](https://medium.com/@alex.keh/oracle-support-for-net-6-and-entity-framework-core-6-statement-of-direction-cfa5d1c59ff8).
