### ISSUE TITLE
ENTITY FRAMEWORK CORE 5 - Return two oracle cursors from single stored procedure

### ISSUE THREAD

**Issue by adisonone** [oracle/dotnet-db-samples#177]
I am using EF core 5 with Oracle database(I cannot change anything in db).
I can call a procedure which has one RefCursor type of output parameter.
I need to call a procedure which has multiple output parameters of RefCursor type.
My issue is similar to an unanswered question on Stackoverflow.
Please refer the below url.
URl - https://stackoverflow.com/questions/66667184/entity-framework-core-5-return-two-oracle-cursors-from-single-stored-procedure

**Comment by alexkeh** [comment]
I believe this is a general EF Core 5 limitation at this time. There's an [open EF Core issue on GitHub](https://github.com/dotnet/efcore/issues/8127) asking for multiple result sets from a stored procedure.
