### ISSUE TITLE
Oracle.EntityFrameworkCore 5.21.1 ToView() causes table creation

### ISSUE THREAD

**Issue by yorgov** [oracle/dotnet-db-samples#178]
After upgrade to 5.21.2 running the Add-Migration command the resulting migration contains new table definition.
Using version 3.19.0-beta1 does not cause such definition
More detailed information can be found in this stackoverflow question:
https://stackoverflow.com/questions/67935610/oracle-entityframeworkcore-5-21-1-toview-causes-table-creation

**Comment by alexkeh** [comment]
There are no EF Core migration APIs for database view DDL. In lieu of APIs, execute SQL, such as using the ExecuteSqlRaw method as you see in the [Oracle EF Core view sample code](https://github.com/oracle/dotnet-db-samples/blob/master/samples/dotnet-core/ef-core/keyless-entity-types-views/keyless-entity-types-views.cs).

**Comment by yorgov** [comment]
Hi @alexkeh and thank you for the fast response
The view was created with a previous migration using the raw sql as suggested. 
The issue here is not that creating a migration does not generate the view. 
The issue is that creating a migration generates a table for the SimpleClasses DbSet even though it is mapped to a view.
I've tried to revert back to 3.19.0-beta1 and create a migration again and it ends up empty which is, in my opinion the expected result

**Comment by alexkeh** [comment]
@yorgov This could be due to EF Core 5's change: [ToView() is treated differently by migrations](https://docs.microsoft.com/en-us/ef/core/what-is-new/ef-core-5.0/breaking-changes#toview).

**Comment by yorgov** [comment]
Yep that was the problem, I guess I missed it.
Sorry to have wasted your time
