### ISSUE TITLE
Oracle.EntityFrameworkCore batching and bind variables

### ISSUE THREAD

**Issue by SierraNL** [oracle/dotnet-db-samples#179]
In a case where you insert multiple rows over a certain threshold the following SQL is generated as a batch:
```sql
BEGIN
INSERT INTO "MyTable" ("Id", "Type", "Created", "Updated")
VALUES (:p0, :p1, :p2, :p3);
INSERT INTO "MyTable" ("Id", "Type", "Created", "Updated")
VALUES (:p4, :p5, :p6, :p7);
INSERT INTO "MyTable" ("Id", "Type", "Created", "Updated")
VALUES (:p8, :p9, :p10, :p11);
INSERT INTO "MyTable" ("Id", "Type", "Created", "Updated")
VALUES (:p12, :p13, :p14, :p15);
END;
```

But if you add a lot of lines, or have a lot of columns for each line, don't you hit a limit on the bind variables? 
Does it break or create multiple batches?

**Comment by alexkeh** [comment]
PL/SQL's number of bind variables limit is 32K.

If you are binding anywhere close to that many variables when inserting rows to the same table, you would be better off using parameter array binding from both a run-time performance standpoint, as well as a programming efficiency standpoint.
