### ISSUE TITLE
How to make Depency Injection with AddDbContext in .NET Core

### ISSUE THREAD

**Issue by eddorneles** [oracle/dotnet-db-samples#18]
I've checked the "source_files" sample but it was to simple for my understanding...

The MySQL provider and Npgsql providers suggests create the database connection inside the Context class, something like:

```C#
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
=> optionsBuilder.UseNpgsql("Host=my_host;Database=my_db;Username=my_user;Password=my_pw");
```
And in the ConfigureService method of the Startup class, some code like this:

```C#
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbContext<OracleContext>().BuildServiceProvider();
}
```
So, I'd like to know if is possible to make the dependency injection like that, does exist some method like the "`UseNpgsql()`" in Oracle.ManagedDataAccess.Core? In fact, does this driver support Entity Framework Core Object Mapping? Or is it only for database access purposes with native queries?

Thanks in advance!

**Comment by alexkeh** [comment]
Oracle Entity Framework Core will support dependency injection, but it is not yet available. We hope to provide the public beta soon. You can see a code sample here:
https://github.com/oracle/dotnet-db-samples/tree/master/samples/dotnet-core/ef-core

**Comment by rbasniak** [comment]
Hi, I downloaded the beta provider from nuget and took a look at the samples on Github, but the AspNet Core sample is creating the DbContext manually, which is not a true and practical AspNetCore usage.

Is there any dependency injection support by now?

**Comment by alexkeh** [comment]
Here's a sample of how to use dependency injection with Oracle Entity Framework Core.
https://github.com/oracle/dotnet-db-samples/tree/master/samples/dotnet-core/ef-core/dependency-injection
