### ISSUE TITLE
c# Oracle.EntityFrameworkCore 5.21.3 System.Guid handling

### ISSUE THREAD

**Issue by Shortcheese** [oracle/dotnet-db-samples#186]
Since the upgrade of Oracle.EntityFrameworkCore from 5.21.1 towards 5.21.3 I face the following problem:
All my entities have a primairy key based on a GUID (maybe not the best idea but ok) 

Table definition
``` Sql
create table "TABLE"
(
  id                              RAW(16) not null,
  ...
);
```

To get an entity by a guid I use 
```C# 
public TEntity GetById(Guid id)
{
    return DoQuery().SingleOrDefault(x => x.Id == id);
}
```
In 5.21.1 this result correctly in an entity using 
```
info: Microsoft.EntityFrameworkCore.Database.Command[20101]
      Executed DbCommand (11ms) [Parameters=[:id_0='e6538e18-e795-45d4-894c-aa321a5c2e58' (DbType = Binary)], CommandType='Text', CommandTimeout='0']
      SELECT "r"."ID", <omitted columns>
      FROM "TABLE" "r"
      WHERE "r"."ID" = :id_0
      FETCH FIRST 2 ROWS ONLY
```
in 5.21.3 the query doesn't return a result while logging the same query

With both versions the database is the same no other packages are upgraded and no changes applied to the code,.
It feels like something happend in the handling of translating of guids. Is there something changed?

**Comment by alexkeh** [comment]
Thanks for reporting! I've been able to reproduce this problem and have filed bug 33198936. One of the dev team members will review and fix the bug.

**Comment by anderjoy** [comment]
I had the same problem, I had to rollback the version to 5.21.1 because the system is in production with billions of lines.

Any workarounds until the definitive solution is released?

I tried using "convert<guid, guid>" but the library ignores my code.

**Comment by alexkeh** [comment]
After discussing this issue with the development team, they have concluded this is not a bug, but an expected behavior change as a result of another GUID bug fix.

With respect to GUID conversion, we're taking a look at it. You can follow this issue to track that discussion.
https://github.com/oracle/dotnet-db-samples/issues/181

**Comment by anderjoy** [comment]
@Shortcheese This workaround solved the conversion "problem" with Guid:

```
public override void OnModelCreating(ModelBuilder modelBuilder)
{
	var converter = new ValueConverter<Guid, byte[]>(
		to => to.ToByteArray(),
		from => new Guid(from));

	foreach (var property in modelBuilder.Model.GetEntityTypes()
            .SelectMany(t => t.GetProperties())
	    .Where(p => p.ClrType == typeof(Guid) ||
                        p.ClrType == typeof(Guid?)))
	{
		property.SetValueConverter(converter);
	}
}
```

**Comment by Shortcheese** [comment]
Thanks @anderjoy! Bad we have to implent, but it works  :)

**Comment by Shortcheese** [comment]
In the end, we just used:  
``` c#
.HasConversion<byte[]>(); 
``` 
on all defined Guid properties. The solution with the ValueConverter messed up with Guid FK's not defined as propery in the entity.
