### ISSUE TITLE
Migrations ，Scaffolding  Reverse Engineering support comment

### ISSUE THREAD

**Issue by crashsol** [oracle/dotnet-db-samples#187]
like mysql,sqlserver efProvider ,  gerenate table and property comment

**Comment by alexkeh** [comment]
I can generate Oracle column and table comments using EF Core migrations using the following syntax:

```
            [Comment("My Table Comment")]
            public class Blog
            {
                [Comment("My column comment")]
                public int Id { get; set; }
            }
```

Are you asking for comments to be created in reverse engineering? I don't believe that's possible today natively in EF Core.
https://github.com/dotnet/efcore/issues/24070
https://github.com/dotnet/efcore/issues/4038

**Comment by crashsol** [comment]
yes, i have the proplem with  reverse engineering , i use  https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars to generate comment info , mysql or sqlserver is ok ,but oralce can not get  comment metadata, can support in next version ？

**Comment by crashsol** [comment]
yes, i have the proplem with  reverse engineering , i use  https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars to generate comment info , mysql or sqlserver is ok ,but oralce can not get  comment metadata, can support in next version ？

**Comment by alexkeh** [comment]
I'm not familiar with EF Core Scaffolding Handlebars project. Is the Oracle provider missing some API or does Handlebars need to add this specific Oracle functionality itself? Has the Handlebars project owner identified what is required to add scaffolding Oracle comments?

**Comment by alexkeh** [comment]
Closing for now. I can re-open it if it becomes clearer what changes ODP.NET needs to make. ODP.NET behaves similarly to SqlClient EF Core provider around comment generation during migrations and scaffolding. MS is working on generating comments via scaffolding in a future EF Core release.
