### ISSUE TITLE
.NET Core 3.1 - Many subqueries using Include()

### ISSUE THREAD

**Issue by danielnetcvb** [oracle/dotnet-db-samples#189]
I created the context, maps and models using scaffolding. I'm using Oracle.EntityFrameworkCore 5.21.3.
However, when I perform the following operation, a large query with subqueries is generated.

```
IQueryable<POSSESSION> query = context.POSSESSIONS
                .Include(p => p.ADDRESS)
                .Include(p => p.DISTRICTs)
                    .ThenInclude(p => p.GROUPs);

            query = query.Where(a => a.ID == 25600);

            var tst = await query.FirstOrDefaultAsync();
```

Something like:

```
SELECT ...
      FROM (
          SELECT ...
          FROM "POSSESSIONS" "p"
          INNER JOIN "ADDRESSES" "p0" ON "p"."ADDRESS_ID" = "p0"."ID"
          WHERE "p"."ID" = 25600
          FETCH FIRST 1 ROWS ONLY
          ) "t"
          LEFT JOIN (
              SELECT ...
              FROM "DISTRICTs" "p1"
              LEFT JOIN "GROUPs" "p2" ON "p1"."ID" = "p2"."PRODUCTION_LOCAL_ID"
              ) "t0" ON "t"."ID" = "t0"."POSSESSION_ID"
              ORDER BY "t"."ID", "t"."ID0", "t0"."ID", "t0"."ID0"
```

This causes an unwanted nested loop, as shown in the execution plan below:

**| Id  | Operation                               | Name                                        | Rows  | Bytes | Cost (%CPU)| Time     |**
---------------------------------------------------------------------------------------------------------------------------------------
|   0 | SELECT STATEMENT                        |                                             |     6 |  9048 |     5  (20)| 00:00:01 |
|   1 |  SORT ORDER BY                          |                                             |     6 |  9048 |     5  (20)| 00:00:01 |
|   2 |   NESTED LOOPS OUTER                    |                                             |     6 |  9048 |     4   (0)| 00:00:01 |
|*  3 |    VIEW                                 |                                             |     1 |  1209 |     3   (0)| 00:00:01 |
|*  4 |     WINDOW NOSORT STOPKEY               |                                             |     1 |  1196 |     3   (0)| 00:00:01 |
|   5 |      NESTED LOOPS                       |                                             |     1 |  1196 |     3   (0)| 00:00:01 |
|   6 |       TABLE ACCESS BY INDEX ROWID       | POSSESSIONS                       |     1 |   460 |     2   (0)| 00:00:01 |
|*  7 |        INDEX UNIQUE SCAN                | PK_POSSESSIONS                    |     1 |       |     1   (0)| 00:00:01 |
|   8 |       TABLE ACCESS BY INDEX ROWID       | ADDRESSES                        |     1 |   736 |     1   (0)| 00:00:01 |
|*  9 |        INDEX UNIQUE SCAN                | PK_ADDRESSES                     |     1 |       |     0   (0)| 00:00:01 |
|  10 |    VIEW PUSHED PREDICATE                |                                             |     2 |   598 |     1   (0)| 00:00:01 |
**|  11 |     NESTED LOOPS OUTER                  |                                             |   173K|    49M|     1   (0)| 00:00:01 |**
|  12 |      TABLE ACCESS BY INDEX ROWID BATCHED| DISTRICTs                           |  1955 |   297K|     1   (0)| 00:00:01 |
|* 13 |       INDEX RANGE SCAN                  | IX_DISTRICTs_POSSESSION_ID |   782 |       |     1   (0)| 00:00:01 |
|  14 |      TABLE ACCESS BY INDEX ROWID BATCHED| GROUPs                         |    89 | 12727 |     0   (0)| 00:00:01 |
|* 15 |       INDEX RANGE SCAN                  | IX_GROUPs_PRODUCTION_LOCAL_ID  |    89 |       |     0   (0)| 00:00:01 |

I think one possibility could create the query like this:
```

      	SELECT 
      		...
      	FROM (SELECT ... FROM POSSESSIONS pp WHERE pp.id = 25600 FETCH FIRST 1 ROWS ONLY)  pp 
      		JOIN ADDRESSES  pa ON pp.ADDRESS_id = pa.id
      		LEFT JOIN DISTRICTs  pl ON pp.id = pl.POSSESSION_id 
      		LEFT JOIN GROUPs  ps ON pl.id = ps.production_local_id
      	
      	ORDER BY
      		pp.ID, pa.ID, pl.ID, ps.ID
```
      		

Having a more desirable execution plan:

| Id  | Operation                              | Name                                        | Rows  | Bytes | Cost (%CPU)| Time     |
--------------------------------------------------------------------------------------------------------------------------------------
|   0 | SELECT STATEMENT                       |                                             |   137 |   201K|     4  (25)| 00:00:01 |
|   1 |  SORT ORDER BY                         |                                             |   137 |   201K|     4  (25)| 00:00:01 |
|   2 |   NESTED LOOPS OUTER                   |                                             |   137 |   201K|     3   (0)| 00:00:01 |
|   3 |    NESTED LOOPS OUTER                  |                                             |    46 | 62790 |     3   (0)| 00:00:01 |
|   4 |     NESTED LOOPS                       |                                             |     1 |  1209 |     3   (0)| 00:00:01 |
|*  5 |      VIEW                              |                                             |     1 |   473 |     2   (0)| 00:00:01 |
|*  6 |       WINDOW NOSORT STOPKEY            |                                             |     1 |   460 |     2   (0)| 00:00:01 |
|   7 |        TABLE ACCESS BY INDEX ROWID     | POSSESSIONS                       |     1 |   460 |     2   (0)| 00:00:01 |
|*  8 |         INDEX UNIQUE SCAN              | PK_POSSESSIONS                    |     1 |       |     1   (0)| 00:00:01 |
|   9 |      TABLE ACCESS BY INDEX ROWID       | ADDRESSES                        |     1 |   736 |     1   (0)| 00:00:01 |
|* 10 |       INDEX UNIQUE SCAN                | PK_ADDRESSES                     |     1 |       |     0   (0)| 00:00:01 |
|  11 |     TABLE ACCESS BY INDEX ROWID BATCHED| DISTRICTs                           |    46 |  7176 |     0   (0)| 00:00:01 |
|* 12 |      INDEX RANGE SCAN                  | IX_DISTRICTs_POSSESSION_ID |    46 |       |     0   (0)| 00:00:01 |
|  13 |    TABLE ACCESS BY INDEX ROWID BATCHED | GROUPs                         |     2 |   286 |     0   (0)| 00:00:01 |
|* 14 |     INDEX RANGE SCAN                   | IX_GROUPs_PRODUCTION_LOCAL_ID  |    89 |       |     0   (0)| 00:00:01 |

**Is there any way I can generate a more suitable query?**

Thank you!
By the way, the project is amazing

**Comment by alexkeh** [comment]
Thanks for the compliment! If you're using 5.21.3, then you must be using EF Core 5.0.

You may want to post this issue on the EF Core GitHub site. There are more LINQ experts there. Most LINQ to SQL generation issues are not provider specific.

**Comment by danielnetcvb** [comment]
Thanks @alexkeh !
Sorry, it should be ".NET Core 3.1". The EF Core version is 5.0.9.

> You may want to post this issue on the EF Core GitHub site. There are more LINQ experts there. Most LINQ to SQL generation issues are not provider specific.

I will do. 
Again, thanks!
