### ISSUE TITLE
Unable to find provider assembly with name Oracle.EntityFrameworkCore

### ISSUE THREAD

**Issue by sovbangit** [oracle/dotnet-db-samples#19]
I added below two references on asp.net core console application.

Install-Package Microsoft.EntityFrameworkCore.Tools -Version 2.1.4
Install-Package Oracle.ManagedDataAccess.Core -Version 2.18.3 

I am getting below exception when I am using scaffolding command for nuget command. 
 
Unable to find provider assembly with name Oracle.EntityFrameworkCore

My scaffolding command is like below :

Scaffold-DbContext "Data Source=oracle_host;Persist Security Info=True;User Id=myuser;Password=mypassword;" Oracle.EntityFrameworkCore -OutputDir Models

**Comment by alexkeh** [comment]
Currently, Oracle EF Core is in a private beta program. The only way to get the assembly right now is to join the beta program. If you wish to join the beta, send an email to dotnet_us(at)oracle.com.

We hope to share Oracle EF Core in a public beta program soon.

**Comment by akorchev** [comment]
How soon is the public beta going to happen?
