### ISSUE TITLE
Oracle.ManagedDataAccess backwards compatibility for old, still maintainable Oracle database versions 

### ISSUE THREAD

**Issue by StrugariStefan** [oracle/dotnet-db-samples#197]
Are the Oracle database versions (12, 18, 19, 21) correlated to the major version of the Oracle.ManagedDataAccess NuGet package? I am mostly interested if there is any incompatibility, for instance, when using the 21.3.0 NuGet version to connect to Oracle 12.

**Comment by alexkeh** [comment]
ODP.NET 21.3 is backwards compatible with Oracle DB 11.2.0.4 and higher, for as long as those DB versions are supported. For example, when Oracle desupports DB 11.2.0.4, then it becomes desupported for all ODP.NET versions. Thus, future ODP.NET releases will not be certified to work with DB 11.2.0.4.

The best place to check is the [ODP.NET System Requirements documentation section](https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/InstallSystemRequirements.html#GUID-A6405CAD-C0E9-45E0-9C38-26B7ED214479) specific to the version you're looking for. I've linked to the ODP.NET 21c book.

**Comment by WenningQiu** [comment]
@alexkeh you mentioned 21.3, but that version is not available on NuGet.org. Versions 21.4, 21.5 and 21.6.1 of Oracle.ManagemedDataAccess NuGet pacakge no longer have the backward compatibility statement in the readme.txt file. Is the latest 21.* package still backward compatible?

Below is in the readme.txt of 19.14.0:

Note: The 32-bit "Oracle Developer Tools for Visual Studio" download from https://otn.oracle.com/dotnet is 
required for Entity Framework design-time features and for other Visual Studio designers such as the 
TableAdapter Wizard. This NuGet download does not enable design-time tools; it only provides run-time support. 
**This version of ODP.NET supports Oracle Database version 11.2.0.4 and higher.**

**Comment by alexkeh** [comment]
All the current ODP.NET 21c versions are backwards compatible with DB 11.2.0.4. However, at some point, new 21c patch updates will no longer be validated with DB 11.2.0.4. My expectation is that will occur around the end of this year when DB 11.2 market-driven support ends.

**Comment by WenningQiu** [comment]
Thanks @alexkeh
