### ISSUE TITLE
Multiple connections to DB within single local transaction

### ISSUE THREAD

**Issue by rfatkullin** [oracle/dotnet-db-samples#198]
I've faced the problem of local transaction propagation to distributed.

I use same connection string to same DB instance, but it is has no effect. 
Maybe such feature have not implemented yet? Maybe I am doing something wrong?

My code example and environment:

Oracle.ManagedDataAccess.Core version: 3.21.3
Os: Windows 10
Framework:  NET Core 5

```
static void Main(string[] args)
{
    using var transactionScopeRoot = new TransactionScope(TransactionScopeOption.Required);

    using var con1 = new OracleConnection(ConnectionString);
    con1.Open();

    using var con2 = new OracleConnection(ConnectionString);
    con2.Open();

    transactionScopeRoot.Complete();
}
```

**Comment by rfatkullin** [comment]
I know about that limitations.
Question is how I can prevent transaction propagation to distributed when I create multiple connections to same db instance?
Is it possible?

**Comment by alexkeh** [comment]
Not when both connections are open at the same time. This behavior is by design.

https://github.com/dotnet/SqlClient/issues/13
