### ISSUE TITLE
Oracle.EntityFrameworkCore | Version 5.21.3 | UseRelationalNulls Not being respected?

### ISSUE THREAD

**Issue by andrewharry** [oracle/dotnet-db-samples#199]
We are migrating an existing .Net Framework project to .NET 5 and have hit an issue regarding the null behavior in EF Core.

We want to turn off the newer (albeit better) null logic in order to reduce the number of breaking changes to the large code base.

We are using the DbContextOptionsBuilder to specify UseRelationalNulls = false.
But the SQL queries being generated are still using the newer 'IS NULL' syntax.

`option.UseOracle(connectionStringName, v => v.UseRelationalNulls(useRelationalNulls: false));`

An example of the Linq query and the resulting SQL:

LINQ Query
```
string accountId = null;
var query = context.Set<Schedule>().Where(v => v.AccountId == accountId);
logger.Warn($"SQL Query: {query.ToQueryString()}");
```
SQL Query (Generated by EF Core)
```
SELECT "e"."ID", "e"."ESC_ACCOUNT_ID"
FROM "EZIAUS"."EZI_SCHEDULE" "e"
WHERE "e"."ESC_ACCOUNT_ID" IS NULL
```

Toggling the 'UseRelationalNulls' value on or off has impact on the generated SQL.

What I am expecting with the value set to false is
```
SELECT "e"."ID", "e"."ESC_ACCOUNT_ID"
FROM "EZIAUS"."EZI_SCHEDULE" "e"
WHERE "e"."ESC_ACCOUNT_ID" = :linqParameter
```

**Comment by alexkeh** [comment]
We've reviewed this issue. It appears to occur generically as we've been able to reproduce the same issue in SQL Server. We've created a issue with the EF Core team for further info: https://github.com/dotnet/efcore/issues/26138

**Comment by alexkeh** [comment]
Closing issue. This bug is a result of behavior from EF Core itself, not from the Oracle provider.
