### ISSUE TITLE
ORA-01000: maximum open cursors exceeded

### ISSUE THREAD

**Issue by deniscpereira** [oracle/dotnet-db-samples#202]
I'm running several inserts and updates in the database.

But I got this exception that seems to be when performing the update. Am I right?

``
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01000: maximum open cursors exceeded
``

How can I manage not to have this exception? If possible an example.

**Comment by deniscpereira** [comment]
Thanks for the reply @alexkeh

I'm using EF Core to open the context with dispose `IDisposable` of the connection at the end of each execution.

``_db.Dispose();``

Could you give me an example of how to explicitly close my cursors using EF Core?

**Comment by alexkeh** [comment]
The explicit Dispose() is fine as long as your code always ends up call it even when there's an exception/error.

If that's not the issue, then the OPEN_CURSORS limit could be increased based on the maximum number of cursors an app session will open at once.

The other possibility is that you have a cursor leak, which could be an ODP.NET issue or an issue in which Dispose isn't being called under specific situations.
