### ISSUE TITLE
ORA-12570  when connecting oracle with Oracle.EntityFrameworkCore 3.21.3

### ISSUE THREAD

**Issue by chanh2505** [oracle/dotnet-db-samples#203]
Hi Friends,
I'm getting the ORA-12570 connection errors with the application using Oracle.EntityFramworkCore

I checked the firewall and the connection worked fine. 
How can I resolved or workaround?

Envrioments:
 Database OS: Oracle Linux
 Oracle version: 19.12
 App: Oracle.EntityFrameworkCore 3.21.3.

The connections string:
  User ID=xxxx;Password=yyyy;Pooling=true;Min Pool Size=5;Connection Lifetime=180;Max Pool Size=50;Incr Pool Size=5;Connection Timeout=600;Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=172.27.4.43)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=ZZZZ)));

**Comment by alexkeh** [comment]
Can you provide the circumstances around when this error happens? Does it happen upon first connecting for every connection, only when connections have been idle for some time when picked up from the pool, etc.?

The most common reason I'm seeing this error nowadays is that many cloud firewalls are setting a TCP idle connection timeout. If a connection stays idle in the pool for several minutes, then the load balancer or firewall kills it. Developers can keep their pooled connections alive using the ODP.NET KeepAlive properties: KeepAlive, KeepAliveInterval, and KeepAliveTime.

**Comment by chanh2505** [comment]
> Can you provide the circumstances around when this error happens? Does it happen upon first connecting for every connection, only when connections have been idle for some time when picked up from the pool, etc.?
> 
> The most common reason I'm seeing this error nowadays is that many cloud firewalls are setting a TCP idle connection timeout. If a connection stays idle in the pool for several minutes, then the load balancer or firewall kills it. Developers can keep their pooled connections alive using the ODP.NET KeepAlive properties: KeepAlive, KeepAliveInterval, and KeepAliveTime.

Hi alexkeh,
Thanks for your reply. The error happens when connections have been idle after 1-2 hours. 
With the first connection after the connection was idle, the error will have appeared.

I'm using EF Core and I don't know how to set the attribute KeepAlive in DbContext. Can you help me with some samples?

So to workaround, I intend to use the health-check API as a way to keepalive for the DB connections.

**Comment by alexkeh** [comment]
In ODP.NET, you need access to the OracleConnection class directly as that is where the KeepAlive properties reside. These aren't static properties. I don't believe EF Core can directly call these properties then.

You can try the health check, which is a bit heavier than a KeepAlive, but effectively does the same thing.

A simpler way is to eliminate or increase your firewall's or load balancer's TCP timeout if it's not needed.

**Comment by chanh2505** [comment]
> In ODP.NET, you need access to the OracleConnection class directly as that is where the KeepAlive properties reside. These aren't static properties. I don't believe EF Core can directly call these properties then.
> 
> You can try the health check, which is a bit heavier than a KeepAlive, but effectively does the same thing.
> 
> A simpler way is to eliminate or increase your firewall's or load balancer's TCP timeout if it's not needed.

Thanks my friend,

I have tried both ways, and the issue seems to be resolved. 

I'm monitoring it more. Thanks again.
