### ISSUE TITLE
EF Core 3.1 scaffolding is slow due to the system view USER_TRIGGER_COLS

### ISSUE THREAD

**Issue by Matt500b** [oracle/dotnet-db-samples#206]
Using 
- Oracle.EntityFrameworkCore 3.19.80
- Oracle database 19.9.0.0

Rough schema estimates:
- ~850 tables
- ~11,000 columns
- ~ 4,000 triggers
- On an instance with ~70 other schemas of similar sizes

Running the scaffolder with verbose we find that the following query is taking 15 minutes to run for 8 tables, and around 50 minutes with 50 tables.

```
select  u.*, 
        v.trigger_name, 
        v.table_name, 
        v.column_name, 
        v.table_owner 
from (
    SELECT  sys_context('userenv', 'current_schema') as schema,    
            c.table_name,    
            c.column_name,    
            c.column_id,    
            c.data_type,    
            c.char_length,    
            c.data_length,    
            c.data_precision,    
            c.data_scale,    
            c.nullable,    
            c.identity_column,   
            c.data_default,    
            c.virtual_column,    
            c.hidden_column  
    FROM user_tab_cols c 
    INNER JOIN  (
        select table_name 
        from user_tables 
        where table_name not in (select container_name from user_mviews)
    )  t  ON t.table_name=c.table_name  
    WHERE t.table_name <> '__EFMigrationsHistory'
    AND (t.table_name IN (:t0, :t1, :t2, :t3, :t4, :t5, :t6, :t7, :t8) 
    AND CONCAT(sys_context('userenv', 'current_schema'), CONCAT('.', t.table_name)) IN (:sdott0, :sdott1, :sdott2, :sdott3, :sdott4, :sdott5, :sdott6, :sdott7, :sdott8))  
)u 
left join USER_TRIGGER_COLS v  on u.table_name = v.table_name and u.column_name = v.column_name and u.schema = v.table_owner 
ORDER BY u.column_id
```

Here we can see the timestamp either side of the query displaying the 15minute execution time
![Scaffolding timestamps](https://user-images.githubusercontent.com/11037250/136566671-c60c3eef-1bc8-4ef9-9ff1-992ab5010424.png)

Assuming that `:t0..:t8` are just the table names and `:sdott0..:sdott8` are the table names prepended with the schema name, running this query took 15 minutes to retrieve 827 rows.

Isolating the USER_TRIGGER_COLS view (`SELECT * FROM USER_TRIGGER_COLS`) results in ~18.5k records after 2.5 mins.

We've currently put a development environment fix in place by copying the view, tuning it by adding a RULE hint and using a synonym to point to the custom one. This has reduced our ~50 minute scaffold time to ~2 minutes however this is not a great fix long term and means we need work arounds to ensure this doesn't go to production environments.

Finally, I'd like to question why this scaffolding query even looks at triggers, are triggers even relevant in scaffolding?

Many thanks :)

**Comment by Matt500b** [comment]
Thanks for the explanation of why triggers are required, I had a suspicion that was the case but thought I'd check anyway.

I'll look into seeing if we can come up with a reproducible test case.

We don't normally run in Verbose mode, and this gave no further performance degradation to the speed of the scaffolding but allowed us to pinpoint the faulting query.

I'll try upgrading to 3.19.130 to see if it's any better and get back to you.

**Comment by alexkeh** [comment]
Closing this thread for now. I'll re-open if there's an update.
