### ISSUE TITLE
Different Guid conversion between Dapper and Entity Framework 6, when using Oracle.ManagedDataAccess version 21.3

### ISSUE THREAD

**Issue by nicoleta-scrimint** [oracle/dotnet-db-samples#208]
[OdpNetGuidIssueWithEntityFramework.zip](https://github.com/oracle/dotnet-db-samples/files/7364562/OdpNetGuidIssueWithEntityFramework.zip)

Hi,

I use Oracle 12c Release 12.2.0.1.0 database and when upgrading the NuGet package Oracle.ManagedDataAccess from 19.11.0 into 21.3.0 and the NuGet package Oracle.ManagedDataAccess.EntityFramework from 19.7.0 into 21.3.0, I observed that the Guid value is not generated in the same way in the database with Dapper and Entity Framework 6.

With Dapper, the .Net Guid value is converted and saved in a concatenated hexa byte array and I need to use a Guid converter when getting data with RAW Oracle data type in order to not have the error "InvalidCastException: Specified cast is not valid.", as you can see at [DapperErrorWhenGetGuidWithoutConverter.txt](https://github.com/oracle/dotnet-db-samples/files/7364979/DapperErrorWhenGetGuidWithoutConverter.txt). 
With Entity Framework 6, the .Net Guid value is saved as they are displayed in .Net.

For example, when inserting an entity, the .Net Guid value 7fbe9835-0713-b045-b9e9-4b69b6f67cc4 is saved with Dapper as 3598BE7F130745B0B9E94B69B6F67CC4 and with Entity Framework 6 it is saved as 7FBE98350713B045B9E94B69B6F67CC4.
As you can see here, 3598BE7F130745B0B9E94B69B6F67CC4 is the concatenation of the bytes in hexa for the 7fbe9835-0713-b045-b9e9-4b69b6f67cc4 Guid value:
byte array for 7fbe9835-0713-b045-b9e9-4b69b6f67cc4:
decimal: 53 152 190 127 19  7  69 176 185 233 75 105 182 246 124 196
hexa:      35 98    BE   7F  13 07 45 B0   B9   E9   4B 69   B6   F6   7C   C4

This different Guid conversion between Dapper and Entity Framework 6 is an issue because our team cannot use both ORM libraries for the same entities and the Guid values which were saved in the past with Oracle.ManagedDataAccess 19.11.0 and Entity Framework 6 are loaded in the .Net application with other Guid values than it was loaded in the past.

I understand that for EF Core there is a workaround for this issue by using value conversion as it is specified at [https://github.com/oracle/dotnet-db-samples/issues/186](https://github.com/oracle/dotnet-db-samples/issues/186).
For Entity Framework 6, value conversion is not supported and it will not be included in the future as it is specified here by Microsoft team: [https://github.com/dotnet/ef6/issues/710](https://github.com/dotnet/ef6/issues/710).

As a workaround for Entity Framework 6, we can use double properties for identifiers, one property with Guid to be used in the .Net application and one with byte array type to be used for the mapping to the Oracle column, like it is the PersonWithByteArrayIdentifiers model class from the attached sample. Still, this workaround pollutes the domain models and involves a big impact refactoring in the existing .Net application of the team.

As I can see at [https://docs.oracle.com/database/121/ODPNT/entityEDMmapping.htm#ODPNT8275](https://docs.oracle.com/database/121/ODPNT/entityEDMmapping.htm#ODPNT8275), Guid type is the corresponding EDM type for RAW(16), still it is not saved the same as it is done with Dapper.

Could you please suggest a fix for this issue of using Dapper and Entity Framework 6 for connecting to an Oracle database with Oracle.ManagedDataAccess NuGet package so that we have the same conversion approach for Guid values?

Thank you!

**Comment by alexkeh** [comment]
These releases are now on NuGet Gallery. A correction on the actual bug fixed is 33402710. The other bug was a related bug, but 33402710 is what I believe the source of the problem.
