### ISSUE TITLE
`Scaffold-DbContext` results ORA-00904: "C"."IDENTITY_COLUMN"

### ISSUE THREAD

**Issue by soumunote** [oracle/dotnet-db-samples#21]
`Scaffold-DbContext` results ORA-00904: "C"."IDENTITY_COLUMN"
The DB which i connected to is "R11.2" which does not have IDENTITY_COLUMN.
I think "That is reason".

Is there any way to specify target DB version which is not support IDENTITY_COLUMN.

`ODP.NET-EF-Core-Beta-2-Documentation.pdf` says UseOracleSQLCompatibility() extention method
can specify database version.
But ... 

Thank you.

**Comment by alexkeh** [comment]
Moving the discussion offline.
