### ISSUE TITLE
NET6 Method 'AppendIdentityWhereCondition' does not have an implementation

### ISSUE THREAD

**Issue by tomasfil** [oracle/dotnet-db-samples#214]
After upgrading to NET6 and EF Core 6 I am getting this error thrown on any action against context.

![image](https://user-images.githubusercontent.com/34779382/141454857-4575a1cf-d765-4146-a822-2499b6f46be6.png)

**Comment by tomasfil** [comment]
Altought I found this https://medium.com/oracledevs/oracle-support-for-net-6-and-entity-framework-core-6-statement-of-direction-cfa5d1c59ff8 but I cannot seem to find way to use "If you would like to get started today, you can already use the latest .NET 6 preview version with ODP.NET Core 21c. "

**Comment by alexkeh** [comment]
.NET 6 will work today with the latest ODP.NET Core driver. EF Core 6 will not until we release a new provider, likely later this month.

**Comment by tomasfil** [comment]
Hello, this issue is still present in EF Core 5 after popping project version to NET6:
![image](https://user-images.githubusercontent.com/34779382/141653117-10a7f19b-0874-4e39-98ac-2d728d2ba9fc.png)

**Comment by tomasfil** [comment]
Ef Core 5.0.12 works. thanks.
