### ISSUE TITLE
InvalidOperationException: Sequence contains more than one matching element NET6

### ISSUE THREAD

**Issue by tomasfil** [oracle/dotnet-db-samples#215]
Hello, I am not sure if it is tied to NET6, but using .Any or Contains in queries started throwing this weird exception:
![image](https://user-images.githubusercontent.com/34779382/141811498-c6bf2d17-10ae-4ada-ba6c-6352003dd34a.png)

Reproduction code steps (any enumerable will do, no matter how it is created):
```
var a = new decimal[]{ 10 }.AsEnumerable();
var test =await this.Context.Set<TJobLine>().Where(x => a.Contains(x.Status.Value) && x.Valid == 1).ToListAsync();
```

Project version NET6
library versions 5.0.12 for EF Core and 5.21.4 oracle EF core and 3.21.4 for managed data acces core:
![image](https://user-images.githubusercontent.com/34779382/141811835-0c023fcd-d49e-4ba8-9174-d9f7cea2225a.png)
![image](https://user-images.githubusercontent.com/34779382/141811860-8379e335-dc7b-421d-b223-910449edee67.png)

**Comment by tomasfil** [comment]
Please try my code sample, but just on different dbset. Use contains, or any inside where clause. 

.Any() by itself works.

That code in my example was working before updating to NET6

**Comment by jogaiii** [comment]
I've run into this issue as well with .NET 6.0, EF Core 5.0 and Oracle EF 5.21.4 as well. My queries seem to work if I make sure to use a List<T> with Contains, but they were working before I switched the project to .NET 6.0 as Enumerables.

**Comment by mdddev** [comment]
I am also having this, out of a sudden. @alexkeh what version of the NET5 libraries of EFCore did you test?
It failed with v5.0.12 and v5.0.9 (<-- the lowest Oracle.EntityFrameworkCore v5.21.4 will let me downgrade to).

This works

```csharp
var oracleConnStr = "Data Source=...";
var opt = new DbContextOptionsBuilder<MyDbContext>().UseOracle(oracleConnStr).Options;
var oracle = new MyDbContext(opt);
var query = oracle.Table
    .Where(w => w.KursDate == new DateTime(2021, 11, 17))
    .Where(w => w.TypeKz == "EZB");

// var ignore = new[] {"XBT"};
// query = query.Where(w => !ignore.Contains(w.DevisenKey));

var result = await query.ToListAsync();
System.Console.WriteLine(JsonSerializer.Serialize(result));
```

This does not 

```csharp
var oracleConnStr = "Data Source=...";
var opt = new DbContextOptionsBuilder<MyDbContext>().UseOracle(oracleConnStr).Options;
var oracle = new MyDbContext(opt);
var query = oracle.Table
    .Where(w => w.KursDate == new DateTime(2021, 11, 17))
    .Where(w => w.TypeKz == "EZB");

var ignore = new[] {"XBT"}; // <------------
query = query.Where(w => !ignore.Contains(w.DevisenKey)); // <------------

var result = await query.ToListAsync();
System.Console.WriteLine(JsonSerializer.Serialize(result));
```

**Comment by alexkeh** [comment]
Thanks @tomasfil, @jogaiii, and @mdddev for reporting. I was able to reproduce the problem with Contains. I have created bug 33580449 to have my dev team review. 

I am curious whether you plan to use EF Core 5 with .NET 6 for the long term or that this is a temporary solution until Oracle EF Core 6 is available, which is coming soon.

I did try to reproduce the issue with .NET 5, EF Core 5.0.12, and Oracle EFCore 5.21.4, but that was successful. It only failed when using .NET 6.

**Comment by mdddev** [comment]
Thanks @alexkeh for following up on this! Since you asked: For me this is only a temp. setup, I plan to adapt EF Core 6 as soon as Oracle EF Core 6 is available.  Cheers

**Comment by tomasfil** [comment]
Hello @alexkeh . Thanks for your time and confirming the bug. It is temporary till Oracle EF core 6 comes out. I did upgrade too soon I guess and now I have had to stop developing my project, since reverting to NET 5 would be breaking change. Is there any rough ETA for Oracle EF 6 yet?

**Comment by jogaiii** [comment]
Thanks @alexkeh, I also plan to update to Oracle EF Core 6.0 when it's available.

**Comment by mdddev** [comment]
[6.21.4](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/6.21.4) was just released. Thank you.
