### ISSUE TITLE
Oracle.EntityFrameworkCore 5.21.4: Identity Column not working anymore

### ISSUE THREAD

**Issue by jhouben98** [oracle/dotnet-db-samples#217]
Hello,

Oracle.EntityframeworkCore 5.21.4 has changed the behaviour of identity columns comparing to 5.21.3:

Old: `"ID" NUMBER(19) NOT NULL`
New: `"ID" NUMBER(19) 1, 1 NOT NULL`

This is created even when `UseOracleSQLCompatibility("11")` option is set, and migration fails with ORA-00907.

**Comment by alexkeh** [comment]
Do you have a simple test case to reproduce the problem? I haven't observed this problem myself. I haven't tried it with an 11.2 DB, but it sounds like the problem occurs whether your are using UseOracleSqlCompatibility at 11 or not.

**Comment by jhouben98** [comment]
Entity Class
```
public sealed class CLASS
{
        public long Id { get; set; }
}
```

Model
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
        modelBuilder.HasDefaultSchema("SCHEMA");
	modelBuilder.Model.SetMaxIdentifierLength(30);

        modelBuilder.Entity<CLASS>(entity =>
	{
		entity.Property(p => p.Id).UseIdentityColumn();

                entity.HasKey(p => p.Id);
        }
}
```

Migration:
```
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "TABLE",
                schema: "SCHEMA",
                columns: table => new
                {
                    ID = table.Column<long>(type: "NUMBER(19)", nullable: false)
                        .Annotation("Oracle:Identity", "1, 1")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_TABLE", x => x.ID);
                });
         }
```

Class/Schema/Table Name are only sample values.

**Comment by jhouben98** [comment]
Addition:

When creating the migration with the 5.21.4 version it works, and the Annotation is changed:

Old: `.Annotation("Oracle:Identity", "1, 1")`
New: `.Annotation("Oracle:Identity", "START WITH 1 INCREMENT BY 1")`

Although it should be fixed to not break existing migrations.

**Comment by alexkeh** [comment]
It sounds like Oracle EF Core 5.21.4 is working for you then.

What kind of SQL breakage are you seeing exactly with your existing migrations? What's the error and the statements in question?

**Comment by jhouben98** [comment]
I've created a repository for your convenience, where you can reproduce this: https://github.com/jhouben98/oracle-dotnet-217

I haven't found the 5.21.3 version on nuget, so I used 5.21.1 - it doesn't matter for this issue.

I have also pregenerated the migration scripts, so you can already see the difference / problem:

[Script created with 5.21.1](https://github.com/jhouben98/oracle-dotnet-217/blob/main/oracle-dotnet-217/MigrationScript_5.21.1.sql) (working)
[Script created with 5.21.4](https://github.com/jhouben98/oracle-dotnet-217/blob/main/oracle-dotnet-217/MigrationScript_5.21.4.sql) (breaks)

**Comment by alexkeh** [comment]
I got some clarification from the ODP.NET dev team. The 5.21.3 Fluent API generation for identity columns was not correct. It was fixed in 5.21.4. 

To your point, it is generally not recommended to mix Oracle EF Core versions when generating the migration source files, updating the DB, and running the app. We will make this clearer in the doc. You may get some artifacts, such as what you experienced. You should use the same version for each of these steps.

**Comment by jhouben98** [comment]
Okay, thanks for the clarification.

How is the recommended way to update a fresh database then?

Because when I understand it correctly, one either needs to:

- Never update the package
or
- Recreate **ALL** migrations whenever an update comes out (don't know if this is even possible)

**Comment by alexkeh** [comment]
Between major EF Core versions, it's more likely you will need to recreate all migrations. I've had some of my sample code break after upgrading to new .NET Core or EF Core versions when MS decides to change APIs without backwards compatibility. Within major versions, it's less likely to occur, but strict backwards compatibility is not always maintained.

The APIs Oracle uses to write its EF Core provider can change more significantly within a release. Those APIs are only of use to DB vendors. The publication of those APIs does not include a formal spec, which is contrast to classic EF6.

An additional challenging factor is the rapid iteration of versions, which makes testing cross-version compatibility a challenge as the combinations grow.

All these factors combine for us to recommend, when possible, to use a single (latest) version for migrations, updates, and runtime. Theoretically, the migrations script generation, the SQL update, and running EF Core are well-decoupled such that you could run each with a different provider and EF Core provider version. But anomalies can occur, such as what you observed.

**Comment by jhouben98** [comment]
Thanks for the explanation 👍
