### ISSUE TITLE
ORA-12516 & ORA-12520

### ISSUE THREAD

**Issue by wahmedswl** [oracle/dotnet-db-samples#218]
Hi,
We are getting ORA-12516 and ORA-12520 on ManagedDataAccess v4.122.19.1. Is there any configuration we need to tweak at the Database side or Driver side that help? We implemented retry which do work but we also get failures. So, if there's any better solution etc that will help would be appreciated.

```
Oracle.ManagedDataAccess.Client.OracleException: Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12516: TNS:listener could not find available handler with matching protocol stack ---> OracleInternal.Network.NetworkException (0x000030E4): ORA-12516: TNS:listener could not find available handler with matching protocol stack
at OracleInternal.Network.OracleCommunication.DoConnect(String tnsDescriptor)
at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)
at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
```

```
Oracle.DataAccess.Client.OracleException: Oracle.DataAccess.Client.OracleException ORA-12520: TNS:listener could not find available handler for requested type of server at Oracle.DataAccess.Client.OracleException.HandleErrorHelper(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, OpoSqlValCtx* pOpoSqlValCtx, Object src, String procedure, Boolean bCheck)
at Oracle.DataAccess.Client.OracleException.HandleError(Int32 errCode, OracleConnection conn, IntPtr opsErrCtx, Object src)
at Oracle.DataAccess.Client.OracleConnection.Open()
```

Thanks

**Comment by alexkeh** [comment]
If this problem is only happening under load, then I would look at increasing the PROCESSES parameter on the DB side. This [Oracle forum thread](https://community.oracle.com/tech/developers/discussion/362226/tns-listener-could-not-find-available-handler-witht-matching-protocol-stack) has more details.

**Comment by wahmedswl** [comment]
Yes, we do call ```OracleConnection.ClearAllPools();``` or ```OracleConnection.ClearPool(connection);``` but it also doesn't help always! PROCESSES parameter increase will help but, how much value is sufficient as we already using high value >1000. Is there any limit per single db user etc or limits apply to overall sessions? Is there any article or thread where we can look for performance best practices etc?

Thanks

**Comment by alexkeh** [comment]
@wahmedswl This gets into the area of DB tuning, of which I know a bit, but don't have performance tuning expertise.

What most DBAs do when they see they will be hitting a process limit is switch from from "dedicated server" to "shared server". The latter allows multiple user processes to share the same server process. If your connection usage is of short duration, you can use Database Resident Connection Pooling, which provides a connection pool for dedicated servers.

Additional possible solutions is to scale your hardware, such as more CPUs or add a RAC node.

**Comment by wahmedswl** [comment]
It seems like connection pooling accounting works per process, is there any way it can be per machine according to the ConnectionString?

Thanks

**Comment by alexkeh** [comment]
I'm not sure what you mean by connection pooling per machine. You can use shared server or DRCP in order to share processes among a pool of connections. These settings do require DB configuration changes since you are optimizing DB resource usage.

**Comment by wahmedswl** [comment]
Is there anything special need to be taken care for DRCP, as it seems like not much can be configured in Odp.Net.

**Comment by alexkeh** [comment]
Here's the [ODP.NET doc on DRCP concepts and how to get started](https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/featConnecting.html#GUID-757A465B-4025-4550-8F13-EA92FE0C1B5A) using it.

You'll want to indicate in your connect descriptor to use the pooled server. There are a couple of DRCP related ODP.NET OracleConnection properties, but I don't think you'll use them for your specific use case.

You will, of course, need to configure DRCP on the DB server side as well.
