### ISSUE TITLE
Explain plan?

### ISSUE THREAD

**Issue by craibuc** [oracle/dotnet-db-samples#22]
Is there a way to perform an explain plan on a query where the results are returned as a managed-code object, rather than a string to be parsed?

**Comment by alexkeh** [comment]
Not possible right now. What's your use case that you need a managed code object?

Explain plan is intended to be consumed by the DBA, rather than by an app.

**Comment by craibuc** [comment]
I have a number reports (Crystal Reports and Web Intelligence), deployed in an enterprise platform, who's performance I'd like to analyze.  Currently, the DBAs only look for the worst offenders.  I'd like to have a more-holistic approach:
- examine each report
- extract its SQL
- get the plan (via ODP.net) for the query
- store it for further analysis

All is is done via PowerShell scripts and API calls.  Rather than having to parse the results of the explain plan, I'd rather have a proper object.

**Comment by alexkeh** [comment]
You can use the static data dictionary view, [PLAN_TABLE](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/refrn/PLAN_TABLE.html#GUID-0CAFEAD1-8C79-4200-8658-947D04BDFFE2), to query for each of the items you're looking for.

I believe using this table will give you the equivalent solution you're looking for.

**Comment by alexkeh** [comment]
I'm closing this issue. Peel free to re-open if the proposed solution of using PLAN_TABLE is not suitable.
