### ISSUE TITLE
Documenation samples link is broken

### ISSUE THREAD

**Issue by madelson** [oracle/dotnet-db-samples#224]
https://www.oracle.com/topics/technologies/dotnet/tech-info-autonomousdatabase.html has a link labeled "ODP.NET Core Sample Code" which takes you to https://github.com/oracle/dotnet-db-samples/tree/master/samples/dotnet-core/autonomous-db which is a dead link.

**Comment by alexkeh** [comment]
The ODP.NET Core Autonomous DB sample code was moved to this GitHub directory:
https://github.com/oracle/dotnet-db-samples/tree/master/samples/autonomous-db/odp-core
