### ISSUE TITLE
ORA-06502: PL/SQL: numeric or value error while calling PL/SQL stored proc with unsized varchar parameters

### ISSUE THREAD

**Issue by lutin7812** [oracle/dotnet-db-samples#228]
**Bug Report**

    NuGet Package: Oracle.ManagedDataAccess 21.4.0
    Database version: Oracle Database 11gR2 Standard Edition 11.2.0.4.0 - Dev

We come accross a strange behavior while calling a PL/SQL stored proc.
If we don't specifically indicate parameter size for a varchar2 parameter we get an ORA-06502 error.

` var sql = @"BEGIN pack_utildb.getParameter (:param_name, :param_val); END; ";
            var nomParamParam = new OracleParameter("param_name", OracleDbType.Varchar2, nomParam, ParameterDirection.Input);

            nomParamParam.Size = 50; // if not specified explicitly we get an ORA-06502 error

            var valueParamParam = new OracleParameter("param_val", OracleDbType.Varchar2, ParameterDirection.Output);

            valueParamParam.Size = 100; // if not specified explicitly we get an ORA-06502 error

            try
            {
                using (Entities conn = new Entities())
                {
                    var result = conn.Database.ExecuteSqlCommand(sql, nomParamParam, valueParamParam);
                    var valueParam = valueParamParam.Value.ToString();
                    LogsManager.WriteTrace($"valueParam getparameter :  {valueParam}");
                    return valueParam;
                }
            }`

`   PROCEDURE getparameter (param_name IN VARCHAR2, param_val OUT VARCHAR2)
   IS
   BEGIN
      SELECT p.valeur_parametre
        INTO param_val
        FROM parametres p
       WHERE UPPER (p.nom_parametre) = UPPER (param_name);
   EXCEPTION
      WHEN NO_DATA_FOUND
      THEN
         param_val := NULL;
   END;
`

Even if we specified the size in the OracleParameter constructor, we still get the error.

**Workaround** : explicitly => valueParamParam.Size = 100

Any idea?

**Comment by alexkeh** [comment]
ODP.NET PL/SQL output parameters must have their sizes explicitly declared.

Input parameters can be inferred when calling the stored procedure directly. You lose some of this capability with anonymous PL/SQL. You can try adding a DECLARE block for your input variable if you want to continue using anonymous PL/SQL.

Here's the relevant doc on [ODP.NET parameter sizes](https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/ParameterSize.html#GUID-941B5A3B-9D8C-4C81-9E9E-56120FDE27E2).
