### ISSUE TITLE
Please make Oracle.ManagedDataAccess.EntityFramework.OracleMigrationSqlGenerator  PUBLIC so we can override the generation of SQL

### ISSUE THREAD

**Issue by worthy7** [oracle/dotnet-db-samples#230]
Title says it all.

**Comment by alexkeh** [comment]
I've created an internal ER 33811059 to track this request.

**Comment by alexkeh** [comment]
This feature could be done. It's more a matter of prioritization as most customers are using EF Core and moving away from EF6.

If there's a significant number of customers requesting this feature over the next couple months, Oracle will work on adding this feature. People can "vote" for this feature by replying to this thread about why the need is important.

**Comment by pjonatansr** [comment]
That feature could be helpful in my case. 

Btw, which strategies you all are using while it's not done?

**Comment by Rafunk** [comment]
Maybe I'm late, but it will be really appreciated.
Thanks

**Comment by ricardodemauro** [comment]
Me too

**Comment by alexkeh** [comment]
Oracle is planning to make OracleMigrationSqlGenerator public. However, to get support, we will require bugs be reproduced without overriding the class.

In our discussions with MS, the public use of this class is intended for provider writers, not for EF6 app developers. Thus, there is minimal available for conformance testing and documentation.

**Comment by alexkeh** [comment]
The [OracleMigrationSqlGenerator class members can be overridden](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/entityUnsupported.html#GUID-1AB87200-2C60-4C85-8A73-D8662448EC6A) starting with version 23.4
