### ISSUE TITLE
When the server version is lower than 12, each query SQL will trigger the query of nls_session_parameters

### ISSUE THREAD

**Issue by shaofing** [oracle/dotnet-db-samples#231]
Each query SQL will trigger an SQL
```
DECLARE  err_code VARCHAR2(2000);  
	err_msg VARCHAR2(2000);  BEGIN  
	SELECT VALUE into :p_nls_comp from nls_session_parameters where PARAMETER='NLS_COMP'; 
	SELECT VALUE into :p_nls_length_semantics from nls_session_parameters where PARAMETER='NLS_LENGTH_SEMANTICS'; 
	SELECT VALUE into :p_nls_nchar_conv_excep from nls_session_parameters where PARAMETER='NLS_NCHAR_CONV_EXCP'; 
	SELECT '0' into :p_err_code from dual;  
	SELECT '0' into :p_err_msg from dual;  
END;
```
Oracle server version : 11g
| Framework | driver | version |
| :-----| ----: | :----: |
| .Net Framework 4.6 | Oracle.ManagedDataAccess.dll | 4.122.19.1 |
| .NetCore 3.1 | nuget package Oracle.ManagedDataAccess.Core | 2.19.80 |

---
I use `dnspy.exe` to debug into the source code of `Oracle.Manageddataaccess.dll` ,  each time `ExecuteReader` is executed, it will trigger `nls_session_parameters` query .
![0](https://user-images.githubusercontent.com/21122388/151321806-637c4fdf-bacd-40ae-8a34-62a51d621adf.jpg)
![1](https://user-images.githubusercontent.com/21122388/151287834-44b2b646-eb2a-480a-aeb3-a9bce1a525ac.jpg)
![2](https://user-images.githubusercontent.com/21122388/151287851-a9e4012b-666d-4b68-b413-bae35757d611.jpg)
![3](https://user-images.githubusercontent.com/21122388/151287861-65313ec8-ca46-425c-bca8-fda51a402652.jpg)
![4](https://user-images.githubusercontent.com/21122388/151287867-0a85f058-451c-4744-9557-557ed128fd3f.jpg)
```
ExecuteReader ---> OracleDataReader --->GetSessionInfo ---> GetGlobalizationValues ---> SelectNLSValues ---> ExecuteNonQuery
```
The results of the `SelectNLSValues` method are not saved, so you query them every time

**Comment by shaofing** [comment]
Why is it designed like this?
Preserve the value of `SESSION_TIME_ZONE` as `m_sessionProperties` property.
![11](https://user-images.githubusercontent.com/21122388/151289273-662927af-dbcc-4349-9ad4-bdcc08fd5820.jpg)

**Comment by shaofing** [comment]
One hour requests
![12](https://user-images.githubusercontent.com/21122388/151301467-fd39373f-f894-4451-adb8-5a4a2b9bf69b.jpg)

**Comment by Gavinluo** [comment]
i have same performance problem @shaofing ,  @Djelibeybi  how to avoid it , my production environment`s AWR Report statistics  every hour has 5 million calls

**Comment by alexkeh** [comment]
This sounds like Bug 33309065. It was fixed in the 19c and 21c code lines last year. You should be able to get the fix from the latest ODP.NET version on NuGet Gallery.
