### ISSUE TITLE
Issue in create table script generated from ef migration

### ISSUE THREAD

**Issue by knalinne** [oracle/dotnet-db-samples#233]
After mgirating from 5.21.1 to 5.21.5, all my create table script now have a weird definition on 

the generated script will look like this: 

```
CREATE TABLE "ROLE" (
        "ID" NUMBER(10) 1, 1 NOT NULL,
        "CODE" NVARCHAR2(50) NOT NULL,
        "CREATED_BY" NVARCHAR2(255) NOT NULL,
        "CREATED_ON" TIMESTAMP(7) NOT NULL,
        "UPDATED_BY" NVARCHAR2(255) NOT NULL,
        "UPDATED_ON" TIMESTAMP(7) NOT NULL,
        CONSTRAINT "PK_ROLE" PRIMARY KEY ("ID")
    )
```

As you can see, there is a "1, 1" just after the column type for the "id" column.

the definition for the Id column as 2 annotations

```
[Key]
[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
public int Id { get; set; }
```

When I try to execute the script, I've the following error:

```
[2022-02-17 19:22:26] [42000][907] ORA-00907: missing right parenthesis
[2022-02-17 19:22:26] Position: 46
```

Any idea how to solve this ?

**Comment by alexkeh** [comment]
This is a known issue. See #217 for a full explanation.

The solution is to use Oracle EF Core 5.21.5 to generate your migration scripts. It will no longer generate scripts with the "1, 1" syntax anymore in this newer version and will be able to execute the migration scripts successfully.

The earlier 21c version used the "1, 1" syntax and was able to execute it.
