### ISSUE TITLE
Field CONTENT NOT NULL, type is CLOB, value is empty clob, Error loading to table

### ISSUE THREAD

**Issue by netnr** [oracle/dotnet-db-samples#234]
```
using var reader = dbCommand.ExecuteReader(CommandBehavior.KeyInfo);

do
{
    var dt = new DataTable();

    dt.Load(reader); // ERROR
} while (!reader.IsClosed);
```

```
using var reader = dbCommand.ExecuteReader(CommandBehavior.KeyInfo | CommandBehavior.CloseConnection);

do
{
    var dt = DbHelper.ReaderTableSchema(reader);

    while (reader.Read())
    {
        var dr = dt.NewRow();
        for (int i = 0; i < dt.Columns.Count; i++)
        {
            var col = dt.Columns[i];
            var cellValue = reader[i];

            if (cellValue != DBNull.Value)
            {
                dr[i] = cellValue;
            }
            else if (col.AllowDBNull == false)
            {
                // run here ...
                // col.AllowDBNull = true;
            }
        }

        // ...
    }
} while (reader.NextResult());
```

Empty CLOB should probably not be equal to DBNull.Value ?

**Comment by netnr** [comment]
Failed to enable constraints. One or more rows contain values violating non-null, unique, or foreign-key constraints

Source: System.Data.Common
ClassName: System.Data.ConstraintException

StackTrace
```
   在 System.Data.DataTable.EnableConstraints()
   在 System.Data.DataTable.set_EnforceConstraints(Boolean value)
   在 System.Data.DataTable.EndLoadData()
   在 System.Data.Common.DataAdapter.FillFromReader(DataSet dataset, DataTable datatable, String srcTable, DataReaderContainer dataReader, Int32 startRecord, Int32 maxRecords, DataColumn parentChapterColumn, Object parentChapterValue)
   在 System.Data.Common.DataAdapter.Fill(DataTable[] dataTables, IDataReader dataReader, Int32 startRecord, Int32 maxRecords)
   在 System.Data.DataTable.Load(IDataReader reader, LoadOption loadOption, FillErrorEventHandler errorHandler)
   在 System.Data.DataTable.Load(IDataReader reader)
```

**Comment by alexkeh** [comment]
If you set ReturnProviderSpecificTypes to true on the OracleDataAdapter, you can return your CLOBs as ODP.NET types, then use IsEmpty or IsNull CLOB properties to distinguish whether the CLOB is empty or null.

**Comment by netnr** [comment]
So this problem is not going to be fixed?

**Comment by alexkeh** [comment]
It may be a bug. What ODP.NET version are you using? Are you using ODP.NET Core, managed, or unmanaged? What DB version are you using?

**Comment by netnr** [comment]
```
<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="3.21.50" />
```

**Comment by alexkeh** [comment]
I just created a simple .NET app returning two rows of CLOBs from a 21c DB table. With ODP.NET Core 3.21.50, it distinguishes between empty and NULL CLOBs when retrieving as expected. I don't see the behavior you see.

**Comment by netnr** [comment]
[screenity.zip](https://github.com/oracle/dotnet-db-samples/files/8190490/screenity.zip)
@alexkeh The new table does not reproduce the problem

**Comment by alexkeh** [comment]
Can you upload a test case that reproduces the problem? There must be some special condition under which this problem reproduces for you and not for me. What DB version are you using?

**Comment by netnr** [comment]
Oracle Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
With the Partitioning, OLAP, Data Mining and Real Application Testing options

I'm guessing maybe it's a database issue, not a program issue
The sample data needs to be processed, I try

**Comment by alexkeh** [comment]
ODP.NET 21c requires the Oracle DB 11.2.0.4+ patch release or higher. It's possible you are encountering a DB bug that was fixed in a subsequent patch. You should upgrade to the latest 11.2 patch or to 19c.

**Comment by netnr** [comment]
I guess so, so let's talk about it here
