### ISSUE TITLE
OracleBulkCopy - Direct Path mode

### ISSUE THREAD

**Issue by sierrodc** [oracle/dotnet-db-samples#238]
Hi,

  we were testing arraybind vs bulk copy and we noticed arraybind is faster than bulk. According to our DBA OracleBulkCopy works in conventional mode (vs direct path mode).

could you suggest us what we are doing wrong? (ps: we are still using oracle 11g, nuget package=3.21.50)

Thanks.

**Comment by alexkeh** [comment]
ODP.NET Core Bulk Copy always uses direct path unless there's some other restriction the ODP.NET doc or DB doc notes that direct path can't be used.

https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/featBulkCopy.html

https://docs.oracle.com/cd/E11882_01/server.112/e22490/ldr_modes.htm
