### ISSUE TITLE
Alex Leh

### ISSUE THREAD

**Issue by pandap1** [oracle/dotnet-db-samples#239]
Hi Alex,

I am getting ORA-12541 TNS No Listener when trying to connect to ADW using Visual Studio 2017 / Managed ODP drivers 21.5.0

One thing which I couldn't follow which is shown on your blog is to configure your local IIS attribute Load User Profile to "true" so that you can use the local wallet.
Here is the link of the document (Point 8) which I am refering above: https://blogs.oracle.com/database/post/connecting-azure-web-apps-to-oracle-autonomous-database.

I had followed the document to T and able to connect to database using Oracle Developer tool but when connecting from code it is getting error, here is the connection string.
"User Id=admin;Password=XXXXX;Data Source=(description=(address=(protocol=tcps)(port=1522)(host=xxxxxx.xxx.xxx.xxx.com))(connect_data=(service_name=xxxxxxxxxxx_xxxxxx_xxx.xxxx.oraclecloud.com))(SECURITY = (MY_WALLET_DIRECTORY = C:\\Users\\opc\\source\\repos\\WebApplication1\\WebApplication1\\DB))); "  

Appreciate your help.

THanks
Prashanth

**Comment by alexkeh** [comment]
@pandap1 Most likely, there's a firewall in between the web server and ADW. Are you trying to connect from a corporate intranet? Some companies have a proxy server that will allow you to then use port 1522 to connect to ADW.

**Comment by alexkeh** [comment]
Closing for now. I'll re-open if this problem remains an issue.
