### ISSUE TITLE
Geography / spatial data type

### ISSUE THREAD

**Issue by nickwade-phl** [oracle/dotnet-db-samples#24]
How can I access an Oracle table that has a SHAPE / geographic column type?

For these tables I am getting "One or more errors occurred. (Unsupported column datatype)".

**Comment by alexkeh** [comment]
Currently, you need to create a user-defined type (UDT) in ODP.NET that maps to the geographic/shape type you want to access. This functionality is available currently in unmanaged ODP.NET only.

You can have Oracle auto-generate the mapping using Oracle Developer Tools for Visual Studio. Here's a walk-through on using UDTs with ODP.NET and Visual Studio tools.
https://www.oracle.com/webfolder/technetwork/tutorials/obe/db/hol08/dotnet/udt/udt_otn.htm

**Comment by nickwade-phl** [comment]
Thanks. I am working on setting up through the unmanaged driver now.

Is there an unmanaged driver specifically for .Net Core? Or do I have to use the 4.x version?

**Comment by alexkeh** [comment]
No, Only ODP.NET Core supports .NET Core. ODP.NET Core does not yet support UDTs.

**Comment by nickwade-phl** [comment]
So there is not an unmanaged version of ODP.Net Core at this point?

**Comment by alexkeh** [comment]
Correct. There never will be as unmanaged ODP.NET was built from the very beginning for .NET FW.
