### ISSUE TITLE
EF Core 6 - Difference between two Date columns

### ISSUE THREAD

**Issue by kakone** [oracle/dotnet-db-samples#250]
The bug #84 is back with Oracle EF Core 6. :angry:

When I do 
```csharp
var days = (from r in dbContext.Blogs select (DateTime.Now - r.CreationDate).Days).FirstOrDefault();
```

I get a `System.InvalidCastException: 'Unable to cast object of type 'System.Decimal' to type 'System.TimeSpan'.'`
I updated the [project](https://github.com/kakone/OracleBug31423881) that reproduces the bug.

**Comment by alexkeh** [comment]
Thanks for reporting this issue. I've been able to reproduce the error from your test case. I've filed bug 34479760 to track this issue and have a dev team member fix it.

**Comment by kakone** [comment]
Is there any chance to have a new version of the NuGet package with the fix this month ?

**Comment by kakone** [comment]
I opened an Oracle Support and requested a patch. Unfortunately, I still haven't got anything except a "Development team is working on the bug". This bug is problematic for us, we would like to have a correction.

**Comment by alexkeh** [comment]
A patch hasn't been created yet for this bug. The bug is still in the dev team's work queue.

**Comment by alexkeh** [comment]
21.8 is now available with the fix. https://www.nuget.org/packages/Oracle.EntityFrameworkCore/7.21.8

**Comment by kakone** [comment]
4 months later, incredible. You just got the worst support ever trophy from me.

**Comment by alexkeh** [comment]
Sorry, this bug correlated with the busiest time of year for our EF Core team. The EF Core 7 architecture changed quite a bit in the last few months, which kept us busy. We plan to deliver the Oracle EF Core 6 bug fix during the first half of January on NuGet Gallery.
