### ISSUE TITLE
DataTable.NewRow() memory usage problem

### ISSUE THREAD

**Issue by netnr** [oracle/dotnet-db-samples#254]
```csharp
public void OracleReader()
{
    var connectionString = "Data Source=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=local.host)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=orcl)));User Id=NETNR;Password=123";
    
    var conn = new Oracle.ManagedDataAccess.Client.OracleConnection(connectionString);
    conn.Open();

    var cmd = conn.CreateCommand();
    cmd.CommandText = "SELECT * FROM ALL_OBJECTS";
    var reader = cmd.ExecuteReader(CommandBehavior.KeyInfo | CommandBehavior.CloseConnection);

    do
    {
        var dt = new DataTable();
        // ignore column addition ...

        var rowCount = 0;
        while (reader.Read())
        {
            // Query the table created by SQL for the user
            // the memory usage continues to grow, and the memory is released at the end of the query
            var dr = dt.NewRow();

            // object[] row = new object[reader.FieldCount]; // the memory usage is normal

            // without filling data
            //for (int i = 0; i < reader.FieldCount; i++)
            //{
            //    dr[i] = reader[i];
            //}
            //dt.Rows.Add(dr.ItemArray);

            if (++rowCount % 100 == 0)
            {
                Debug.WriteLine($"{rowCount} rows, memory: {Environment.WorkingSet}");
            }
        }
    } while (reader.NextResult());

    Debug.WriteLine($"Done! memory: {Environment.WorkingSet}");
}
```

Observational analysis:
- When the query SQL is a system table, such as `SELECT * FROM ALL_OBJECTS`, the memory usage is stable
- When querying a table created by SQL for a user, such as `SELECT * FROM LOG_HISTORY`, the memory usage continues to grow, and the memory is released at the end of the query
- query SQL arbitrarily, change `var dr = dt.NewRow();` to `object[] row = new object[reader.FieldCount];`, the memory usage is stable

**Comment by alexkeh** [comment]
Is this with .NET (Core) or .NET FW? Which version?
Which ODP.NET is it: core, managed or unmanaged? Which version?

**Comment by netnr** [comment]
.NET 6.0.8
Oracle.ManagedDataAccess.Core v3.21.70

**Comment by alexkeh** [comment]
When I tested .with `SELECT * FROM V$LOG_HISTORY` with `var dr = dt.NewRow();` and then `object[] row = new object[reader.FieldCount];`, I didn't see a big difference in memory growth.

Using `var dr = dt.NewRow();`
```
100 rows, memory: 63778816
200 rows, memory: 63909888
300 rows, memory: 63926272
400 rows, memory: 63934464
500 rows, memory: 63942656
Done! memory: 63987712
```

Using `object[] row = new object[reader.FieldCount];`
```
100 rows, memory: 63700992
200 rows, memory: 63840256
300 rows, memory: 63848448
400 rows, memory: 63856640
500 rows, memory: 63873024
Done! memory: 63901696
```

What kind of growth are you seeing?

**Comment by netnr** [comment]
It's not the `V$LOG_HISTORY` table, it's the table `LOG_HISTORY` created by me

I will try again today. The memory has not continued to grow. I am also very confused. You can close this question first, and then add it if you have any questions.

**Comment by alexkeh** [comment]
Closing for now as suggested.

I likely won't be able to reproduce the problem without your `LOG_HISTORY` metadata and may be the some sample data as well. It depends on the how the bug manifests itself.
