### ISSUE TITLE
An exception is thrown when removing comments for columns of type CLOB

### ISSUE THREAD

**Issue by Ruthlessist** [oracle/dotnet-db-samples#256]
An earlier version of migrations contained comments, now they don't fit, I'm going to remove them, but applying the new migration throws an exception: 
> ORA-22859: invalid modification of columns

The following migration code:
```C#
migrationBuilder.AlterColumn<string>(
                name: "ColumnName",
                table: "TableName",
                type: "CLOB",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "CLOB",
                oldNullable: true,
                oldComment: "oldComments");
```
generated the migration script:
```sql
declare
   l_nullable user_tab_columns.nullable % type;
begin 
   select nullable into l_nullable 
   from user_tab_columns 
  where table_name = 'TableName' 
  and column_name = 'ColumnName' 
;
   if l_nullable = 'N' then 
        EXECUTE IMMEDIATE 'ALTER TABLE "TableName" MODIFY "ColumnName" CLOB NULL';
 else 
        EXECUTE IMMEDIATE 'ALTER TABLE "TableName" MODIFY "ColumnName" CLOB';
 end if;
end;
/

COMMENT ON COLUMN "TableName"."ColumnName" is N''
/
```

As above, the provider generates redundant alter statements for columns that only have comments modified, which happens to not be supported for columns of type CLOB.

**Comment by alexkeh** [comment]
Thanks for reporting this issue. I've been able to reproduce the behavior and have created a bug (34676084) to track issue resolution.

**Comment by alexkeh** [comment]
21.8 is now available. https://www.nuget.org/packages/Oracle.EntityFrameworkCore/7.21.8
