### ISSUE TITLE
Supporting JSON-column in EF Core

### ISSUE THREAD

**Issue by elmanav** [oracle/dotnet-db-samples#259]
Are the new .NET EF Core 7 `JSON`-column supported?
Сurrently still it RC, but with the release we would like to be able to manipulate json-data in table columns (https://devblogs.microsoft.com/dotnet/announcing-ef7-release-candidate-2/).

**Comment by elmanav** [comment]
> Not in the initial release, but it's something we're taking a look at. Is your team using Oracle DB JSON columns?

Yes, we use json-docs to store some data in tables. Get a hybrid.

**Comment by alexkeh** [comment]
I've filed ER 34700870 to track this feature request. If there are others that would like to see this feature, please upvote the original request.

**Comment by SavoInfostream** [comment]
Here's a link with the complete feature list: [Entity Framework Core 7 (EF7) is available today](https://devblogs.microsoft.com/dotnet/announcing-ef7).
This probably won't get a lot of upvotes at the start, but I think these features for .NET developers are much more convenient than than JSON syntax in SQL 😵😵😵

So, please implement them.

P.S. "ORA-50612: Mapping .NET Aggregate types to JSON column is currently not supported" I got this today, so don't forget the lists.

**Comment by alexkeh** [comment]
Our expectation is for EF Core JSON support to be available with the 21.10 version of ODP.NET EF Core.

**Comment by alexkeh** [comment]
Unfortunately, we weren't able to get this update into 21.10. We're still working on this feature update and fixing associated bugs.

**Comment by biplovkc** [comment]
@alexkeh Is there any ETA on EF Core Json support?
We have been using oracle json column and this feature would make things so much easier

**Comment by alexkeh** [comment]
@biplovkc Not yet. I'll try to get one soon.

**Comment by Wx19880221** [comment]
@alexkeh 
   now ef core 7.21 add the feature? I found still report ORA-50612: Mapping .NET Aggregate types to JSON column is currently not supported.

**Comment by alexkeh** [comment]
@Wx19880221 Oracle continues to work on adding EF Core JSON column support. It's hard to provide an ETA since resolving some of the significant bugs requires fixes in EF Core itself. When we encounter EF Core issues, we report them to MS.

**Comment by alexkeh** [comment]
JSON columns supported starting with Oracle EF Core 8.
