### ISSUE TITLE
Entity Framework Core 7 Support

### ISSUE THREAD

**Issue by MartijnFLC** [oracle/dotnet-db-samples#266]
Now there is a final release of EF Core 7, just over a week ago. Can you tell when we can expect Oracle to have a compatible driver for EF Core 7?

**Comment by alexkeh** [comment]
Oracle plans to release an EF Core 7 provider by the end of this year on NuGet Gallery.

**Comment by DsSHac** [comment]
Since EF Core 7 itsself supports both .net 7 and .net 6 (LTS) - will the new EF Core 7 Oracle Provider also support .net 6?

**Comment by alexkeh** [comment]
Yes, Oracle EF Core 7 will run on .NET 6.

**Comment by guilhermecampello** [comment]
> Oracle plans to release an EF Core 7 provider by the end of this year on NuGet Gallery.

Any release date yet ?  😬

**Comment by alexkeh** [comment]
The date is still planned by the end of the year, anywhere from middle of this month to the end.

**Comment by alexkeh** [comment]
Now available on NuGet Gallery: https://www.nuget.org/packages/Oracle.EntityFrameworkCore/7.21.8
