### ISSUE TITLE
Scaffold-DbContext GetTriggerColumns Exception. An item with the same key has already been added.

### ISSUE THREAD

**Issue by vn506138** [oracle/dotnet-db-samples#28]
Table has multiple triggers, using the same column_name.
select column_name from USER_TRIGGER_COLS.
System.ArgumentException: An item with the same key has already been added.

**Comment by alexkeh** [comment]
Thanks for reporting this issue! Another customer has encountered the same bug (29611320) already and the Oracle team is working on a fix.

**Comment by alexkeh** [comment]
This bug has been fixed in our code line and will be available starting with Beta 4.

**Comment by alexkeh** [comment]
Beta 4 is available on NuGet with this bug fixed.
