### ISSUE TITLE
Timeline for resolving Oracle.ManagedDataAccess.Core v2.19.190 vulnerability?

### ISSUE THREAD

**Issue by stephen-swensen** [oracle/dotnet-db-samples#286]
NuGet.org is reporting a High severity vulnerability in the latest version of the Oracle.ManagedDataAccess.Core 2.x series package (2.19.190):

* https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/2.19.190
* https://github.com/advisories/GHSA-5pm2-9mr2-3frq

It occurs to me that 2.19.190 might actually be OK but is incorrectly being scooped up by the `Affected Versions < 3.21.90` constraint of the github advisory. In any case, do you have a timeline for resolving the issue? Thanks!

**Comment by alexkeh** [comment]
@stephen-swensen The CVE (2023-21893) has been fixed as of ODP.NET Core 19.18. You'll see it noted in the README.txt in that NuGet package. The 2.19.190 NuGet package will have the fix as well.

What hasn't been corrected is the version scoping as you suspect. That is a little more involved to fix as there is a formal process to follow to get info changed on a CVE.

**Comment by stephen-swensen** [comment]
Awesome, thanks for confirming 👍
