### ISSUE TITLE
.First or .FirstOrDefault does not work

### ISSUE THREAD

**Issue by Carloscrmk** [oracle/dotnet-db-samples#29]
This code is giving the following exception: 
_context.User.FirstOrDefault(p => p.Id == 3)

exception:
"ORA-00933: SQL command not properly ended"

When I use .ToList() work normaly

**Comment by alexkeh** [comment]
I assume you are using Oracle DB 11.2. If so, use the extension method and set it to UseOracleSQLCompatibility("11") as described in the doc included with the NuGet package.

**Comment by Carloscrmk** [comment]
Tks!!!
