### ISSUE TITLE
Migration does not comply with maximum identifier lenght when using Code first

### ISSUE THREAD

**Issue by tomasfil** [oracle/dotnet-db-samples#297]
Hello,

I am using Oracle.EntityFrameworkCore 7.21.9 and when I set within OnModelCreating
```
modelBuilder.UseTablePrefix("T_");
modelBuilder.Model.SetMaxIdentifierLength(30);
```

For this DbSet
`public virtual DbSet<PaymentCheckRunApprovalRequest> PaymentCheckRunApprovalRequests { get; set; }`

The generated name is "T_PAYMENT_CHECK_RUN_APPROVAL_REQUESTS".

Which is 37 characters long and thus migration update fails.

Note, that I am also using the compatability option:
`options.UseOracleSQLCompatibility("11");`

**Comment by alexkeh** [comment]
Does it work if you use `MaxIdentifierLength`? That's the one the Oracle documents to use to [set the maximum identifier length](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/EFCoreIdentifier.html#GUID-FA43F1A1-EDA2-462F-8844-45D49EF67607).

**Comment by tomasfil** [comment]
Isnt that what `modelBuilder.Model.SetMaxIdentifierLength(30);` does?

**Comment by alexkeh** [comment]
Yes may be hitting this known issue in EF Core itself.
https://github.com/dotnet/efcore/issues/26993

**Comment by alexkeh** [comment]
Closing for now. Will re-open if https://github.com/dotnet/efcore/issues/26993 fix does not resolve issue or there's more info that points to a separate root cause.
