### ISSUE TITLE
Release Notes?

### ISSUE THREAD

**Issue by ricardodemauro** [oracle/dotnet-db-samples#300]
Is there a place where we can find the release notes of each nuget package version?

Sorry if is the wrong place to ask that.

Thanks

**Comment by sungam3r** [comment]
In the nupkg itself
![изображение](https://github.com/oracle/dotnet-db-samples/assets/21261007/732c40d1-c239-4f16-bce3-6081f9ee76f5)

**Comment by alexkeh** [comment]
The ODP.NET team will start naming its NuGet package README files, README.md, which NuGet prefers for embedded doc. We'll start with the long term release (i.e. 19c and 23c) managed ODP.NET packages. If all goes smoothly, all ODP.NET related packages will adopt the change.

**Comment by ricardodemauro** [comment]
Thanks
