### ISSUE TITLE
Object UDT =>  GET_Type_SHAPE issue

### ISSUE THREAD

**Issue by mezJihad** [oracle/dotnet-db-samples#308]
I folow the sample provided for using object UDT, but i have this exception after executing the sample : 

ORA-06550: Ligne 1, colonne 13 :
PLS-00306: numéro ou types d'arguments erronés dans appel à 'GET_TYPE_SHAPE'
ORA-06550: Ligne 1, colonne 7 :
PL/SQL: Statement ignored

I'm using .Net 6 and Oracle.ManagedDataAccess.Core 3.21.110

**Comment by alexkeh** [comment]
UDTs are supported with ODP.NET Core starting with version 23. Use the following download (or later versions when they become available).
https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core/23.2.0-dev

**Comment by mezJihad** [comment]
Hello, thank you for you're response. 

I tried the new release  V23.2.0-dev, but i have same issue.

There is please another alternatif of using UDT : I want to send list of items to my stored procedure.

**Comment by alexkeh** [comment]
You can use [PL/SQL associative arrays in ODP.NET](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/featOraCommand.html#GUID-05A6D391-E77F-41AF-83A2-FE86A3D98872) if it's a list of items of the same type.
