### ISSUE TITLE
Official version

### ISSUE THREAD

**Issue by Carloscrmk** [oracle/dotnet-db-samples#31]
Hello!!

I would like to know when it's published the official version ?

tks,

**Comment by alexkeh** [comment]
An official version of which product?

**Comment by Carloscrmk** [comment]
Oh! Sorry!!

Entity FrameWork Core for Oracle

**Comment by alexkeh** [comment]
The official beta 3 version is up on NuGet, which you can download today.
https://www.nuget.org/packages/Oracle.EntityFrameworkCore/

The production version is currently planned to be released by end of this quarter (i.e. June). However, this date can be moved up or back depending on beta feedback. If beta customers find few issues, the production date could be moved up. If customers find significant issues that require another beta or find them late in the beta cycle, then the date could be moved back.

You can think of the production release target as not encompassing just a date, but a mix of a date, feature completeness, and quality metric.

**Comment by Carloscrmk** [comment]
thanks very much !!!!
