### ISSUE TITLE
[HELP/HOW TO] Pass udt types into a function call in PLSQL

### ISSUE THREAD

**Issue by gpgpublickey** [oracle/dotnet-db-samples#310]
Hi everyone, need some assist about how to call a function inside of a package which receives an udt type and returns an udt type? I'm having problems to define the returned type and execute it successfully

The examples I saw works for stored procedures, any hints or tips?

Thanks

**Comment by alexkeh** [comment]
Here's an ODP.NET UDT example using a function.
https://www.codeproject.com/Articles/1139474/ODP-NET-User-Defined-Type-Implementation

It's based upon unmanaged ODP.NET, but the code isn't too different from managed/Core versions.
