### ISSUE TITLE
CoreFirst  EFMigrationsHistory Error

### ISSUE THREAD

**Issue by l2999019** [oracle/dotnet-db-samples#32]
I copied this code to execute corefirst and told me that the table did not exist.

I am a brand new database

Error:
Failed executing DbCommand (113ms) [Parameters=[], CommandType='Text', CommandTimeout='0']
SELECT "MigrationId", "ProductVersion"
FROM "__EFMigrationsHistory"
ORDER BY "MigrationId"

What am I missing?

**Comment by l2999019** [comment]
I think I found the reason.
My Oracle data has two different accounts, but in the same space it looks like this。
![image](https://user-images.githubusercontent.com/10385855/56713361-29f7b180-6764-11e9-85bd-1f7bb8c1e795.png)
So when one of the libraries has a table named “_EFMigrationsHistory”, Codefirst will not create a new “_EFMigrationsHistory“, causing this error. Do you know any solution?

**Comment by alexkeh** [comment]
These are two different issues. In your first post, you are executing a SELECT against a table that does not yet exist. The solution is to scaffold the migration, then apply the model to the DB, which will then create __EFMigrationsHistory table. You can do this by following the steps in this README.

https://github.com/oracle/dotnet-db-samples/tree/master/samples/dotnet-core/ef-core

I need more information to understand what produces your second error. What is the relationship between ORACLETESTDB and MYTEST? If they are two distinct schemas, what common access does the user have in common for these schemas?

**Comment by l2999019** [comment]
These two users are in the same database instance, but they are different users.
I execute the following SQL statement in Mytest, and I can find "_EFMigration History" in ORACLETESTDB.
Is that the reason?
![image](https://user-images.githubusercontent.com/10385855/56783294-c336ce80-681d-11e9-8457-8bf63039a60b.png)

Because I deleted the “_EFMigrationsHistory“ table of ORACLETESTDB, Codefirst on MYTEST side can be successfully executed.
The relationship between ORACLETESTDB and MYTEST is shown below, in the same database instance.
![image](https://user-images.githubusercontent.com/10385855/56783424-45bf8e00-681e-11e9-8138-7d2f3775aa86.png)
![image](https://user-images.githubusercontent.com/10385855/56783443-5d971200-681e-11e9-9b18-502fd16da199.png)

**Comment by alexkeh** [comment]
In most situations, each Oracle user has its own separate schema.

I suspect what has happened is that you had created an EF Core schema already created for ORACLETESTDB. Then, you tried to create a new EF Core schema again before deleting the previously created tables, such as _EFMigration History.

Of course, the solution is what you found, which is deleting the previously created schema objects if you plan to start a new EF Core schema.

**Comment by l2999019** [comment]
Thank you very much for your answer
