### ISSUE TITLE
How to Associate Sequences with Tables？

### ISSUE THREAD

**Issue by l2999019** [oracle/dotnet-db-samples#33]
I used codefrist to generate tables and primary keys, and automatically generated new sequences for each primary key.
Like this：
![image](https://user-images.githubusercontent.com/10385855/56788012-da32ec00-6830-11e9-8c50-8aea92def7d4.png)
But I added the code as follows:
`using (BloggingContext db = new BloggingContext())
            {
                db.Blogs.Add(new Blog { Url = "aaaaa1" });
                db.SaveChanges();
            }`
I will get an error message:
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Because I didn't copy the primary key。
I found the sequence of ForOracleUseSequenceHiLo method settings
like this
 entity.Property(o => o.Id).ForOracleUseSequenceHiLo("aa_sq");

But I can't determine the automatically generated sequence name. Or do you have a better way to connect directly?

**Comment by khizhenokm** [comment]
try this
modelBuilder.HasSequence<int>("aa_sq");

https://docs.microsoft.com/ef/core/modeling/relational/sequences

**Comment by l2999019** [comment]
> 试试这个
> modelBuilder.HasSequence（“aa_sq”）;
> 
> https://docs.microsoft.com/ef/core/modeling/relational/sequences

It's just creating sequences that don't associate him with any tables.

**Comment by alexkeh** [comment]
SequenceHiLo extensions methods are not supported in the beta 3.

Since it appears you are using the sample app, I would just re-create the sample again with a primary key.

**Comment by l2999019** [comment]
Modify the sample code?

**Comment by alexkeh** [comment]
You shouldn't need to modify the sample code for EF Core to generate a sequence unless you are using Oracle DB 11.2. If so, set the extension method UseOacleSQLCompatibility to "11" as described in the beta doc.
