### ISSUE TITLE
Scaffold-DbContext number(x,y)

### ISSUE THREAD

**Issue by vn506138** [oracle/dotnet-db-samples#34]
Column tyoe: number(x,y)
Scaffold-DbContext Result: type int not decimal
Example:
Column tyoe: number(10,4)
Db value: 1234.5678
int value: 1234

**Comment by alexkeh** [comment]
I'm not able to reproduce this behavior. When using Oracle EF Core Beta 3 to scaffold the table below, the NUMBER column is mapped to decimal. I used DB server 12.2 in my test.
===============
  CREATE TABLE "TABLE1" 
   (	"COLUMN1" NUMBER(10,4) NOT NULL ENABLE,
	CONSTRAINT "CONSTRAINT1" PRIMARY KEY ("COLUMN1") ENABLE
   );

  CREATE UNIQUE INDEX "CONSTRAINT1" ON "TABLE1" ("COLUMN1");
===============

Can you share your table create script? I can then try reproducing this issue again.

**Comment by vn506138** [comment]
Sorry, I used different components.
