### ISSUE TITLE
How to use OpenTelemetry with entity framework core?

### ISSUE THREAD

**Issue by mihaimyh** [oracle/dotnet-db-samples#344]
In our application, we are using the ef core oracle driver. How can we use open telemetry with ef core? The OTL samples only shows how we can use it directly with the OracleConnetion object.

**Comment by alexkeh** [comment]
You can use [OpenTelemetry.Instrumentation.EntityFrameworkCore](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.EntityFrameworkCore) instrumentation library for EF Core OpenTelemetry.

The EF Core team has an [open feature request to improve OpenTelemetry tracing](https://github.com/dotnet/efcore/issues/29281) as well.

If your intent is to trace EF Core itself, there shouldn't be a need to add any ODP.NET-specific code.

If you want to trace ODP.NET operations in addition, you will need to reference ODP.NET's OpenTelemetry provider by adding some variation of the existing ODP.NET OpenTelemetry sample.
