### ISSUE TITLE
Core 8 with oracle 11

### ISSUE THREAD

**Issue by yamamotokazue** [oracle/dotnet-db-samples#352]
In core 7
DI UseOracleSqlCompatibility("11")

But in core 8
string change to OracleSQLCompatibility.DatabaseVersion19,21,23

So oracle 11 can’t use in core 8？

Thank you for response

**Comment by alexkeh** [comment]
In Oracle EF Core 8, there is no DB 11.2 backwards compatibility support. Oracle DB 11.2 Extended Support ended in 2020. Market Driven Support occurred after that, which has now ended. The Oracle .NET team expectation is that customers will use newer, supported DB versions for their new .NET development. You can continue to use older ODP.NET versions with DB 11.2,

**Comment by yamamotokazue** [comment]
Thank you for response🥹
