### ISSUE TITLE
Fulltext support

### ISSUE THREAD

**Issue by marian-margeta** [oracle/dotnet-db-samples#36]
Are you planning to add fulltext support to Oracle.EntityFrameworkCore? In SQL Server it can be done as follows
```csharp
dbContext.ExampleTable.Where(x => EF.Functions.Contains(x.ftProperty, "text")).ToList();
```

**Comment by alexkeh** [comment]
The equivalent functionality is already available using `EF.Functions.Like`. For example, you can use the following line of code in the Oracle EF Core GitHub sample to replace the existing query:

`var blogs = db.Blogs.Where(x => EF.Functions.Like(x.Url, "%oracle%")).ToList();`

**Comment by marian-margeta** [comment]
Thanks @alexkeh, but it is not truly fulltext search. It uses just regular `LIKE` operator which is really slow. I thought an expression that be can translated into something like this:
```sql
select * from BLOGS WHERE CONTAINS(URL, 'oracle', 1) > 0
```

For example PostgreSQL connector extends `EF.Functions.*` with their [own methods](https://www.npgsql.org/efcore/mapping/full-text-search.html) to provide fulltext support. I am curious if it is also planned for Oracle connector.

**Comment by alexkeh** [comment]
We're not planning to add full text search in the first production release as it is late in the beta stage.

We'll consider this feature in the second release.

**Comment by alexkeh** [comment]
As we consider full text search support, please specify what functionality are you looking for. For example, are you looking for support of just the querying with CONTAINS or do you need additional capabilities? What type of CONTAINS scenarios do you need?

**Comment by alexkeh** [comment]
Closing feature request until we hear more feedback on feature request details. I will re-open if community provides more direction.
