### ISSUE TITLE
Records not supported in EF object initialization expressions

### ISSUE THREAD

**Issue by silkfire** [oracle/dotnet-db-samples#364]
In an EF Select clause, if the object is a record, the query fails with an exception that it can't be translated (something with `ParameterQueryRootExpression`).

When using anonymous objects or classes, things work as intended.

Repro:

```
await _dbContext.MyTable.Where(...).Select(m => new Record(m.Column1, m.Column2)).ToListAsync();
```

**Comment by alexkeh** [comment]
Does EF Core itself support records yet? See https://github.com/dotnet/efcore/issues/11457

**Comment by silkfire** [comment]
Thanks for the reply, I wasn't actually aware of that.
