### ISSUE TITLE
Sample with ArrayBind should avoid using square exemple to avoid columns/rows confusion

### ISSUE THREAD

**Issue by rferraton** [oracle/dotnet-db-samples#368]
It would be great to change the example to avoid using square exemple to avoid columns/rows confusion.

Using 5 elements arrays for each 3 columns in this exemple instead of 3 elements arrays would be better

https://github.com/oracle/dotnet-db-samples/blob/95b7321c6510d07884a5160f2c81b4fc79977ec2/samples/array-bind/ArrayBind.cs#L32

**Comment by alexkeh** [comment]
Done. Thanks @rferraton for the suggestion!
