### ISSUE TITLE
[QUESTION] Can be name convention on udt class generation changed?

### ISSUE THREAD

**Issue by gpgpublickey** [oracle/dotnet-db-samples#370]
I would like to map the udt class with auto mapper to a DTO and my udt class is being generated in uppercasing + underscore following the name in the table column, there is a configuration I can use to change it to pascal casing to match the naming convention we use for dtos?

**Comment by alexkeh** [comment]
ODP.NET doesn't have a configuration setting to convert DB object names to Pascal case in .NET.

**Comment by gpgpublickey** [comment]
Just to clarify im referring to the naming of the properties in the udt generated class.

**Comment by alexkeh** [comment]
Are you asking the .NET classes Oracle Developer Tools for Visual Studio auto-generate from Oracle DB UDTs?

**Comment by gpgpublickey** [comment]
Yes correct those!, because property names are being generated with the same name from column instead to use a naming convention like pascal case or camel case

**Comment by christianshay** [comment]
Hi, casing change is not yet a feature of Oracle Developer Tools for Visual Studio. I will add it to our list of potential enhancements.

**Comment by gpgpublickey** [comment]
Thanks both!
