### ISSUE TITLE
Oracle.ManagedDataAccess.Core DbDataReader.ReadAsync does not handle cancellation properly

### ISSUE THREAD

**Issue by nobodo** [oracle/dotnet-db-samples#376]
When canceled, ReadAsync(cancellationToken) is sometimes giving ORA-12570.

As per Mircosoft documentation ReadAsync should throw OperationCanceledException. It seems that ODP.Net prefers to just throw OracleExceptions, which is fine, but in that case the error should be ORA-01013

Using version 23.4.0

**Comment by alexkeh** [comment]
For [DbDataReader](https://learn.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.readasync?view=net-8.0), the ReadAsync exception of DbException. For [SqlClient](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldatareader.readasync?view=dotnet-plat-ext-5.0), the relevant exception is the SqlException.

Both ORA-12570 and ORA-01013 are the Oracle DB errors that get returned to ODP.NET upon a ReadAsync cancel exception.

**Comment by nobodo** [comment]
Ok, I'll just close this then since it seems to be working as planned.
