### ISSUE TITLE
Compatibility issue on Boolean mapping 

### ISSUE THREAD

**Issue by BehroozBahrameh** [oracle/dotnet-db-samples#377]
When you have an entity with a boolean column like

``` csharp
[Table("TEST_TABLE", Schema = "BB")]
public class TestEntity
{
    [Column("ID")] public long Id { get; set; }
    [Column("IsTrue")] public IsTrue int  { get; set; }
}
```

and a domain record like:
``` csharp
public record Test(
    long Id,
    bool IsTrue);
```

and use `AutoMapper` for mapping those two like:

``` csharp
public class TestProfile : Profile
{
    public TestProfile()
    {
        CreateMap<TestEntity, Test>();
    }
}
```

and try to retrieve data with like:

``` csharp
_mapper.ProjectTo<Test>(
            _dbContext.TestEntity.Take(10)
).ToArrayAsync();
```

the generated query from the version `8.21.140` is,
``` sql
SELECT "a"."ID", CASE
          WHEN "a"."IsTrue" = -1 THEN 1
          ELSE 0
      END
      FROM "BB"."TEST_TABLE" "a"
      FETCH FIRST :p_0 ROWS ONLY
```
and from version `8.23.40` is
```sql
SELECT "a"."ID", CASE
          WHEN "a"."IsTrue" = -1 THEN True
          ELSE False
      END
      FROM "BB"."TEST_TABLE" "a"
      FETCH FIRST :p_0 ROWS ONLY
```
and therefore `TRUE` and `FALSE` do not exist on Oracle, by the latest version of the Oracle drive (8.23.40) you get an exception.
`Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00904: "FALSE": invalid identifier` and everything is fine in the previous versions!

**Comment by alexkeh** [comment]
In the 23ai release, we've added [new `OracleSQLCompatibility` enumeration values](https://docs.oracle.com/en/database/oracle/oracle-database/21/odpnt/EFCoreAPI.html#GUID-41786CF0-11E3-4AD2-8ED1-3D31D5FE2082):

- `OracleSQLCompatibility.DatabaseVersion19`
- `OracleSQLCompatibility.DatabaseVersion21`
- `OracleSQLCompatibility.DatabaseVersion23`
By default, the enumeration value will match the ODP.NET version number. In the case of ODP.NET 23, the enumeration is `OracleSQLCompatibility.DatabaseVersion23`. 

In DB 23ai, BOOLEAN columns and native JSON columns are supported. Thus, Oracle EF Core will use these in its SQL when `OracleSQLCompatibility.DatabaseVersion23` is set. If you'd like to revert to 19c compatible behavior, use the `OracleSQLCompatibility.DatabaseVersion19` value.

**Comment by BehroozBahrameh** [comment]
thank you so much for your reply @alexkeh.
the issue is solved by explicitly defining `UseOracleSQLCompatibility`
I have a question, mostly out of curiosity, What is the recommended way to check breaking changes as versioning does not show it ( or maybe I have a wrong interpretation )?

**Comment by alexkeh** [comment]
@BehroozBahrameh The breaking change is documented [here](https://docs.oracle.com/en/database/oracle/oracle-database/23/odpnt/EFCoreDesupportedAPIs.html#GUID-9429D321-2E46-4A95-AF56-EFBEC52A9E01). It's a new enumeration that replaces a string value, but also has a different default than its replacement as older Oracle DB versions have reached end of support.

In the next doc version, we'll make the new default behavior clearer in this breaking change section.

**Comment by lwestfall** [comment]
Note to self: read closed issues before spending half a day on a repro. Glad compatibility can be set though!
