### ISSUE TITLE
Default Entity Framework OTel settings for Aspire

### ISSUE THREAD

**Issue by cmdkeen** [oracle/dotnet-db-samples#378]
I've got a [PR open](https://github.com/dotnet/aspire/pull/4078) for the new Aspire framework's Oracle support to add the new OpenTelemetry package - it's all very exciting.

There is a question about what the right default settings should be - I used the values from [this repo](https://github.com/oracle/dotnet-db-samples/blob/master/samples/opentelemetry/opentelemetry.cs). It would be good to get confirmation that for Entity Framework they are a good set of properties.

Adding if you want to see it in action - clone the repo and run the project in playground\OracleEndToEnd\OracleEndToEnd.AppHost\

**Comment by alexkeh** [comment]
I responded to the question [here](https://github.com/dotnet/aspire/pull/4078#discussion_r1593105578).

**Comment by cmdkeen** [comment]
Great, thanks. Will pick up there.
