### ISSUE TITLE
dotnet core 3 support

### ISSUE THREAD

**Issue by xcaptain** [oracle/dotnet-db-samples#38]
dotnet core version: `3.0.0-preview5-19227-01`
ef core version: `3.0.0-preview5.19227.1`
Oracle.EntityFrameworkCore version: `2.19.0-beta4`

in `Startup.cs`

```csharp
services.AddDbContext<DbContext>(opt => opt.UseOracle("User Id=user1;Password=123456;Data Source=127.0.0.1:1521/ORCLPDB1"));
```

got an error when doing a simple query

```
An unhandled exception has occurred while executing the request.
System.TypeLoadException: Method 'PopulateDebugInfo' in type 'Oracle.EntityFrameworkCore.Infrastructure.Internal.OracleOptionsExtension' from assembly 'Oracle.EntityFrameworkCore, Version=2.0.19.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

Is this a Oracle.EntityFrameworkCore but? when will it support dotnet core 3.

I found a similar discussion about `Devart.Data.Oracle` at https://forums.devart.com/viewtopic.php?t=36091

**Comment by alexkeh** [comment]
It's likely ODP.NET Core will certify with .NET Core 3 when it goes production. .NET Core 3 has not introduced significant ADO.NET changes.

Oracle EF Core will not certify until the second production release at the earliest. EF Core 3 has introduced significant changes that provider writers must implement.

**Comment by romuloteixeira** [comment]
I got the same issue and I found the following:
[https://www.nuget.org/packages/Oracle.EntityFrameworkCore/](url)

Basically, this page shows the dependencies DLLs and versions.
    Microsoft.EntityFrameworkCore.Relational (>= 2.1.11 && < 3.0.0)

I updated from 3.1.0 to 2.2.6 of these packages and it worked nice:
   Microsoft.EntityFrameworkCore and;
   Microsoft.EntityFrameworkCore.Relational

**Comment by ronnyek** [comment]
Amazing this still doesn't appear to be a thing considering 3.0 is basically end of life or end of support in a month or so

**Comment by alexkeh** [comment]
ODP.NET Core 19.6 supports both .NET Core 3 and 3.1.

**Comment by HarshaNaga** [comment]
Hi Alex, Using My Local (Development Environment) I can able to connect ORACLE DB using .NET Core 3 with ODP.NET Core 19.6, however after publishing my code into Server then ORACLE Connection is failing. Can you please suggest me Do I Need To Install Any ORACLE Stuff in My Deployment Server..?

Appreciate your quick response and reference links.

Thanks,
Harsha Naga.

**Comment by alexkeh** [comment]
@HarshaNaga What error are you seeing?

**Comment by HarshaNaga** [comment]
Thanks for your quick response Alex,
I am getting the below error.

Microsoft.EntityFrameworkCore.Database.Connection[20004]
      An error occurred using the connection to database '' on server 'XYZServerOraDB'.
Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12154: TNS:could not resolve the connect identifier specified
 ---> OracleInternal.Network.NetworkException (0x00002F7A): ORA-12154: TNS:could not resolve the connect identifier specified
   at OracleInternal.Network.AddressResolution..ctor(String TNSAlias, SqlNetOraConfig SNOConfig, Hashtable ObTnsHT, String instanceName, ConnectionOption CO)
   at OracleInternal.Network.OracleCommunication.Resolve(String tnsAlias, ConnectionOption& CO)
   at OracleInternal.ConnectionPool.PoolManager`3.ResolveTnsAlias(ConnectionString cs, Object OC)
   at OracleInternal.ServiceObjects.OracleConnectionImpl.Connect(ConnectionString cs, Boolean bOpenEndUserSession, OracleConnection connRefForCriteria, String instanceName)
   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, OracleConnection connRefForCriteria, String affinityInstanceName, Boolean bForceMatch)
   at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, OracleConnection connRefForCriteria)
   at Oracle.ManagedDataAccess.Client.OracleConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)

**Comment by HarshaNaga** [comment]
While I connect from my local system(Development System), I placed the tnsnames.ora file in C:\oracle\client\product\12.1.0\client_1\network\admin folder as suggested in article @ "https://docs.oracle.com/database/121/ODPNT/InstallConfig.htm#ODPNT8159  "
then it connected, but in deployment server don't have oracle client installation and it doesn't have oracle folder in C drive.

**Comment by alexkeh** [comment]
With ODP.NET Core, there is no concept of an Oracle Home because the assembly can be xcopy deployed. The installer does not set up the ORACLE_HOME\network\admin directory as a location for finding its DB connection config files as is typical of a full Oracle Client. 

You will need to set this environment variable yourself with ODP.NET Core if you intend to use the network\admin folder. Here are all the options and the order in which ODP.NET Core tries to find its DB connection config files:

1. OracleConfiguration.OracleDataSources
2. Directory set in OracleConnection.TnsAdmin property
3. Directory set for the Tns_Admin connection string attribute
4. Directory set in OracleConfiguration.TnsAdmin property
5. Current working directory or web application root directory
6. TNS_ADMIN directory setting of the OS environment variable or container environment variable

**Comment by HarshaNaga** [comment]
Appreciated your quick response Alex, Can I have any reference link where and how we can set the Tns_Admin connection string attribute, Is that Okay we can configure this attribute in appsettings.json or web.config files. otherwise please advise me the which option is best in deployment servers.  Thanks in adavnce.

**Comment by alexkeh** [comment]
The doc page is here at the bottom of the page: https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/InstallCoreConfiguration.html#GUID-24C963AE-F20B-44B5-800C-594CA06BD24B

As the doc published last year, we've made a number of updates in our interim releases. My list is more up to date if you're using the latest ODP.NET Core version. .NET Core is still relatively new and we're addressing the different ways customers would like to configure their DB connection info.

We added Tns_Admin connection string attribute in the 19.7 version. You can place the connection string wherever you want. As long as ODP.NET Core can find it when it needs to create a connection, you're good to go.

**Comment by alexkeh** [comment]
I talk about the ODP.NET 19.7 new features, including the new connection string attributes here: https://medium.com/oracledevs/odp-net-19-7-whats-new-2bb96174571f

**Comment by HarshaNaga** [comment]
Again Thank You Much Alex, does ODP.NET 19.7 support .Net core 3.0 and 3.1 EF, I hope ODP.NET 19.7 support Microsoft.EntityFrameworkCore (3.0.0 or 3.1.0 ),  Microsoft.EntityFrameworkCore.Tools (3.0.0 or 3.1.0 ), Microsoft.EntityFrameworkCore.Design (3.0.0 or 3.1.0 ), Microsoft.EntityFrameworkCore.SqlServer (3.0.0 or 3.1.0 ) right. Please let me try with latest ODP.NET Core 19.7 and I will let you know if any issues. Thank You.

**Comment by alexkeh** [comment]
ODP.NET 19.7 supports all those things. You must use the Oracle EF Core provider on top for EF Core 3.1 support. That Oracle EF Core beta is currently in beta and available on NuGet Gallery.

**Comment by HarshaNaga** [comment]
Okay Thank You Alex, I was wondering if you could able to provide any sample connection how to refer the path for tnsnames.ora in appsettings.json **or** DbContextOptionsBuilder.

Thanks in advance.

**Comment by alexkeh** [comment]
This sample code uses DbContextOptionsBuilder. You can append "Tns_Admin=<Directory>;" to the connection string.

**Comment by HarshaNaga** [comment]
Okay gotcha Thank You. If I am not wrong DIRECTORY NAME will be the path of tnsnames.ora file location right.
