### ISSUE TITLE
[HELP] Does odp.net supports datafiles?

### ISSUE THREAD

**Issue by gpgpublickey** [oracle/dotnet-db-samples#393]
Hi everyone,

I'm having some troubles to identify if currently odp.net is supporting datafiles for temp files and temp tablespaces storage.

Could somebody help me with this clarification?

thanks!

**Comment by alexkeh** [comment]
How the DB treats the storage is generally transparent to ODP.NET. I haven't tried setting up datafiles in a temporary tablespace myself. If it works in the Oracle DB and you can access it from a regular user session, then it should work similarly with ODP.NET.

**Comment by gpgpublickey** [comment]
We need to do attachments feature which is currently supported with this datafile feature, I'm wondering if ODP.NET handles creation and drop of temp datafiles despite to just access it @alexkeh do you have something in mind about this? thx for the quick reply

**Comment by alexkeh** [comment]
ODP.NET can perform DDL. In fact, if you use Oracle Developer Tools (ODT)for VS or VS Code to create schema objects or setup tablespaces, the driver being used to execute those commands is ODP.NET.

Just make sure your ODP.NET user has the admin privileges necessary to execute the DDL.

This capability requires writing the SQL as this type of DB administration is uncommon for ODP.NET apps to expose to their end users. If you're looking for GUI tools to perform these schema creation and update tasks, then I would recommend using ODT.
