### ISSUE TITLE
How to use in asp.net core

### ISSUE THREAD

**Issue by smallprogram** [oracle/dotnet-db-samples#4]
Can you tell me how to use in asp.net core 2?

**Comment by alexkeh** [comment]
I assume you are asking about ODP.NET Core. Here's how to run ODP.NET Core in ASP.NET Core 2:

Start VS 2017.
Create an empty ASP.NET Core web application.
Add ODP.NET Core assembly to your project.
Replace the Startup.cs file with the one attached here.
[Startup.txt](https://github.com/oracle/dotnet-db-samples/files/1754572/Startup.txt)
Add the user password and Data Source to connect. I assume you have access to the HR sample schema.
Run the website.

This is a very simple app, just to illustrate how to get started.

**Comment by alexkeh** [comment]
The ODP.NET Core Beta 2 was just released with NuGet support. Did that version resolve the issue for you?
