### ISSUE TITLE
Scaffold whole shema - Schema not found

### ISSUE THREAD

**Issue by Bjego** [oracle/dotnet-db-samples#40]
Hey guys,
if I try to scaffold a whole schema (not the schema of the given user), I always get the message:

Unable to find a schema in the database matching the selected schema.

Here is how I try to scaffold the context:
```bash
dotnet ef dbcontext scaffold "User Id=myUser;Password=myPassword;Data Source=SomeTnsName;" Oracle.EntityFrameworkCore -o Models --schema SCHEMA
```

**Comment by alexkeh** [comment]
This sounds like bug 29443379/28963848. This bug exists in Beta 4 and has been fixed for the production release.

**Comment by Bjego** [comment]
Hey,
 is there a planed release date for the production release?

**Comment by alexkeh** [comment]
This month.

**Comment by Bjego** [comment]
Okay cool, I guess we can close this then.
@alexkeh Any idea, or hint why the following describe takes up to 2 minutes?
Is there anything I can improve in my schema to make this faster? Or how I can detect the slowness?
Scaffolding my db takes ages...
`
 OracleDatabaseModelFactory.GetTriggerColumns() : select column_name from USER_TRIGGER_COLS where table_name ='someTable'
`

Running it on an Oracle 18 database
![grafik](https://user-images.githubusercontent.com/12625568/60863704-d6084f00-a221-11e9-99df-998c7da2da25.png)

**Comment by Bjego** [comment]
@alexkeh btw great work with your Visual Studio Code extension!

**Comment by alexkeh** [comment]
@Bjego 
Since Beta 4, we've optimized the triggers query so that it executes faster. We also are eliminating the default output tracing that occurs during scaffolding. You should see these changes in production.

I will pass along your praise for the Oracle Developer Tools for VS Code extension to @christianshay and @ahmed-riaz whose team built it
