### ISSUE TITLE
Error using Kerberos on ODP.NET 23.x

### ISSUE THREAD

**Issue by richardcwagner** [oracle/dotnet-db-samples#409]
Hello Everyone,

I am trying to update Oracle.ManagedDataAccess.Core from 3.21 to 23.5.1, but when I try to connect to a database using Kerberos5, I am receiving the following error:

```OracleInternal.Network.NetworkException (0x80004005): ORA-50210: Kerberos5: Authentication handshake failure at stage: Loading ODP Kerberos assembly.

System.IO.FileNotFoundException: Could not load a file or assembly 'Oracle.ManagedDataAccess.Kerberos, Version=23.1.0.0, Culture=neutral
```

On version 3.21.X, I was using the library Kerberos.NET together, on 23.4.0 to 23.5.1 I tried using with and without this lib, but always I am receiving the same error message. 

I also tried to compile the code in a Visual Studio running on Windows and in a container running Linux, but the same error occurred on both. 

Anyone could run this lib using Kerberos with version 23? On 3.21.x it is working fine.

Thank you for your attention!

**Comment by alexkeh** [comment]
Same issue as #237.

Kerberos on .NET Core is not yet officially supported. It's planned for 23.6 in which a new NuGet package for ODP.NET Core Kerberos will be available.

The Kerberos code was included with ODP.NET Core 21, but not supported, as we worked with MS to ensure we had the right deployment and support models.
