### ISSUE TITLE
Connection.Open take 7 seconds when done from a dll loaded via reflection

### ISSUE THREAD

**Issue by ElectricVampire** [oracle/dotnet-db-samples#412]
I am trying to add oracle support in query plan [visualizer visual studio extension](https://github.com/Giorgi/EFCore.Visualizer/tree/main?tab=readme-ov-file#oracle). The issue I am facing is that [connection.Open()](https://github.com/Giorgi/EFCore.Visualizer/blob/main/src/IQueryableObjectSource/DatabaseProvider.cs#L19)  is taking 7 seconds which is timing out the debug visualizer. 
Exact same connection.Open take milliseconds when done in same process without visualizer. 
![image](https://github.com/user-attachments/assets/c5683869-d84c-45e6-a659-8825c6ef0a4c)

I have captured traces in both cases :
[Fast.txt](https://github.com/user-attachments/files/17174720/Fast.txt)
[slow.txt](https://github.com/user-attachments/files/17174721/slow.txt)

**Comment by alexkeh** [comment]
@ElectricVampire We see the 7+second delay in the trace. What is BEHIND the 127.0.0.1:1521 you have for the localhost? Are you using it as a HOOK into the tool, like the SSH tunnel is for SSH?

Nothing is being written to the ODP.NET trace for those 7 seconds, which suggests we're waiting upon an operation outside ODP.NET to return.

**Comment by ElectricVampire** [comment]
@alexkeh 
I took the network traces as well, I am not able to understand what I am doing different in case of slow and fast use case and I am able to reproduce it all the time.
(Remove .txt from file names)
[fast.pcapng.txt](https://github.com/user-attachments/files/17189567/fast.pcapng.txt)
[slow.pcapng.txt](https://github.com/user-attachments/files/17189568/slow.pcapng.txt)

![image](https://github.com/user-attachments/assets/2e94489a-8faa-4c17-aa76-d0d3ea08793f)

Its always reproducible.
Sample App:
Replace your oracle connection string. Now here query returns immediately.
[EfCoreTesting.zip](https://github.com/user-attachments/files/17177613/EfCoreTesting.zip)

Install [visual studio extension](https://marketplace.visualstudio.com/items?itemName=GiorgiDalakishvili.EFCoreVisualizer) Or Install vsix after building https://github.com/Giorgi/EFCore.Visualizer or just install from following zip file
[EfCoreVisualizerExtension.zip](https://github.com/user-attachments/files/17177623/EfCoreVisualizerExtension.zip)
![image](https://github.com/user-attachments/assets/5c06ab37-db94-401a-b33d-63f479360917)


After installing if you inspect query in visualizer, it will timeout. Which basically tell that connection.Open took 7 seconds.

**Comment by WalterDias** [comment]
I running in a similar issue but with the async operations, I know for sure that EF Core is giving me here the same scenario (I did the test already).

If you dont mind @ElectricVampire can you perform the same test using version Oracle.ManagedDataAccess.Core 23.5.1 to see if you are having the same issue as I.

```
try
{
    using (OracleConnection con = new OracleConnection("<CONNECTION>"))
    {
        Task task = con.OpenAsync();

        using (var cmd = new OracleCommand("SELECT * FROM <SOMETABLE> FETCH FIRST 100 ROWS ONLY", con))
        {
            await task;

            var rdr = await cmd.ExecuteReaderAsync();

            while (await rdr.ReadAsync()) { }

            await con.CloseAsync();
        }
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
    throw;
}
```

My thread: https://github.com/oracle/dotnet-db-samples/issues/411

**Comment by alexkeh** [comment]
@ElectricVampire Thanks for the complete test case. 

I was able to reproduce the 7+ second delay using your test case. We'll take a look at what's going on.

I created a bug (37138146) to track this issue.

**Comment by ElectricVampire** [comment]
> I running in a similar issue but with the async operations, I know for sure that EF Core is giving me here the same scenario (I did the test already).
> 
> If you dont mind @ElectricVampire can you perform the same test using version Oracle.ManagedDataAccess.Core 23.5.1 to see if you are having the same issue as I.
> 
> ```
> try
> {
>     using (OracleConnection con = new OracleConnection("<CONNECTION>"))
>     {
>         Task task = con.OpenAsync();
> 
>         using (var cmd = new OracleCommand("SELECT * FROM <SOMETABLE> FETCH FIRST 100 ROWS ONLY", con))
>         {
>             await task;
> 
>             var rdr = await cmd.ExecuteReaderAsync();
> 
>             while (await rdr.ReadAsync()) { }
> 
>             await con.CloseAsync();
>         }
>     }
> }
> catch (Exception ex)
> {
>     Console.WriteLine(ex.ToString());
>     throw;
> }
> ```
> 
> My thread: #411

Yes, I do see issue on 23.5.1

**Comment by alexkeh** [comment]
@ElectricVampire It looks like ODP.NET is just waiting for a response as it tries to connect to the DB host when the delay occurs. We'd like to see if your DB listener is working on any tasks during this delay. Can you clear your DB listener log and run the test case again with ODP.NET tracing on as well? Then, send us both the ODP.NET trace and listener log. We can then line up the timestamps and see what happens on the listener (and DB) side when the 7+ second delay occurs.

You can post it here or email it to us dotnet_us(at)oracle.com.

You'll need the tool, lsnrctl, which is a tool in the full Oracle DB client. The Oracle DB server has this tool as well. 

You can call `lsnrctl status` from the command line to find out where you listener log is located. Clean it out and run the test case.

**Comment by alexkeh** [comment]
From analyzing the Wireshark trace, this issue appears to be result of the .NET runtime. ODP.NET is waiting for a response from .NET that is taking 7 seconds. https://github.com/dotnet/runtime/issues/108363
