### ISSUE TITLE
Support for EF Core 9

### ISSUE THREAD

**Issue by ssougnez** [oracle/dotnet-db-samples#415]
EF Core 9 is just around the corner (November 2024).

Do know whether the Oracle EF provider will support it right away or if we'll have to wait?

Thanks

**Comment by alexkeh** [comment]
Oracle is testing the new EF Core 9 RCs as soon as MS is releasing them. Oracle EF Core 9 should arrive shortly after MS releases EF Core 9.

**Comment by ssougnez** [comment]
Thanks.

Do you already know if the version 8 of the provider is compatible with the version 9 of .NET Core?

**Comment by alexkeh** [comment]
ODP.NET Core versions that work with .NET 8 also work in .NET 9. .NET runtimes have had this backwards compatibility for awhile now.

EF Core 9 requires fundamental provider level changes to interoperate. Thus. EF Core 8 providers will not work with EF Core 9. It's the same for all provider vendors.

**Comment by ssougnez** [comment]
Okay thanks :-)

**Comment by ssougnez** [comment]
Can I kindly asked whether you have a clearer view on the release date of the provider, please?

**Comment by alexkeh** [comment]
The release has slipped to early next week.

**Comment by ssougnez** [comment]
Awesome, thanks a lot :-)

**Comment by alexkeh** [comment]
[Oracle EF Core 9](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/9.23.60) is now available on NuGet Gallery!

**Comment by ssougnez** [comment]
I love you <3
