### ISSUE TITLE
Sample for Oracle AQ?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [oracle/dotnet-db-samples#422]
Is there a sample on how to create a worker that is supposed to listen a queue indefinitely and "do stuff"? im having difficulty and the only "way out" I see is to "pool" the database on a regular interval...

Please advise

**Comment by alexkeh** [comment]
Here's an ODP.NET AQ event handler sample included in this [discussion forum thread](https://forums.oracle.com/ords/apexds/post/how-to-consume-oracle-aq-using-net-core-8358#comment_53173828715792734016825268728173870969).
