### ISSUE TITLE
Oracle.EntityFrameworkCore not compatible with Microsoft.EntityFrameworkCore

### ISSUE THREAD

**Issue by MarkFangmeyer** [oracle/dotnet-db-samples#424]
I have encountered a problem with Oracle.EntityFrameworkCore and latest Microsoft.EntityFrameworkCore 9.0.0. When a new DB context is being created I get the following exception.

> Method 'get_LockReleaseBehavior' in type 'Oracle.EntityFrameworkCore.Migrations.Internal.OracleHistoryRepository' from assembly 'Oracle.EntityFrameworkCore, Version=8.0.23.1, Culture=neutral, PublicKeyToken=89b483f429c47342' does not have an implementation

**Comment by alexkeh** [comment]
The Oracle EF Core 9 provider is not yet available. We plan to release it next week.

**Comment by alexkeh** [comment]
[Oracle EF Core 9](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/9.23.60) is now available on NuGet Gallery!
