### ISSUE TITLE
Error when using latest Oracle.EntityFrameworkCore 9

### ISSUE THREAD

**Issue by MarkFangmeyer** [oracle/dotnet-db-samples#430]
I've updated the nuget recently. All depending MS nugets are also got updated. Connection settings didn't change. When trying to connect, I get the following error. 

`{"ORA-00904: \"FALSE\": invalid ID\r\nhttps://docs.oracle.com/error-help/db/ora-00904/"}`

**Comment by alexkeh** [comment]
This is probably the same issue as https://github.com/oracle/dotnet-db-samples/issues/377.

Set the `OracleSQLCompatibility` enum to the DB version you are connecting to if it's not 23ai. Earlier DB versions do not support Boolean columns.

**Comment by alexkeh** [comment]
Closing for now. If the recommendation doesn't resolve the issue, let us know.
