### ISSUE TITLE
Server Returns ORA-01017 When Connecting to Server with EUS Enabled Using Managed Driver

### ISSUE THREAD

**Issue by hanserya** [oracle/dotnet-db-samples#46]
Are there any known issues within the managed driver that prevent client applications from authenticating with an Oracle server whenever Enterprise User Security is enable server-side?

We are able to connect to the database behind EUS just fine as long as we use the unmanaged driver. However; using the managed driver results in the server returning an ORA-01017 error code. Additionally, we can connect to other Oracle servers using the managed driver when EUS is not in the picture.

**Comment by alexkeh** [comment]
The early part Chapter 3 in the ODP.NET Users Guide covers features and differences in authenticating with the different ODP.NET drivers, including documented restrictions.
https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/featConnecting.html#GUID-BCF2F215-C25F-403C-8D18-B03A69BC7104

It's hard to say whether you are encountering a bug, a known restriction, or mis-configuration without more info. I'm happy trying to work with whatever info you can provide. Just keep in mind, this is a public forum.

**Comment by alexkeh** [comment]
Closing the issue. I will re-open if you'd like to continue the discussion.
