### ISSUE TITLE
DbUpdateConcurrencyException with EntityFramework Core for workflow-core

### ISSUE THREAD

**Issue by pbros** [oracle/dotnet-db-samples#50]
Hello,

I'm trying to implement Oracle as a Persistence mechanism for [workflow-core](https://github.com/danielgerlag/workflow-core). I based myself on the existing MySQL, MSSQL and Postgre implementations (which all work 100%)

However, when I run my integration tests, some of them fail (EventScenario,RetrySageScenario,WhileScenario) with the following errors

> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.InvalidOperationException: The instance of entity type 'PersistedExecutionPointer' cannot be tracked because another instance with the key value '{PersistenceId: 1}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

> Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 2282 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

The EF query that gives theses errors is here:
```csharp
        public async Task PersistWorkflow(WorkflowInstance workflow)
        {
            using (var db = ConstructDbContext())
            {
                var uid = new Guid(workflow.Id);
                var existingEntity = await db.Set<PersistedWorkflow>()
                    .Where(x => x.InstanceId == uid)
                    .Include(wf => wf.ExecutionPointers)
                    .ThenInclude(ep => ep.ExtensionAttributes)
                    .Include(wf => wf.ExecutionPointers)
                    .AsTracking()
                    .FirstAsync();

                var persistable = workflow.ToPersistable(existingEntity);
                await db.SaveChangesAsync();
            }
        }
```

Is this a known issue?

This was done using Oracle.EntityFrameworkCore Version 2.19.30, on a 12.1.0.2.0 Database

See https://github.com/danielgerlag/workflow-core/issues/422 for reference

**Comment by alexkeh** [comment]
During beta, there was a bug (29683096 ) with a similar error. This bug was fixed for production. 

Do you have reproducible test case? We can take a look.

**Comment by pbros** [comment]
You can checkout my fork here: https://github.com/pbros/workflow-core

I didn't implement the Docker Integration tests, but you can connect to an existing database by setting the connection string (replace `__CONNECTION__STRING__`)

The tests to run are in WorkflowCore.Tests.Oracle

**Comment by alexkeh** [comment]
I filed bug 30452644 to track this issue. My team may come back with questions about setting up the test case as we have not used this particular workflow engine before.

**Comment by alexkeh** [comment]
@pbros 
Is it possible for you to run the test with ODP.NET tracing on?

You can enable it EF Core with the following instructions:
https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/EFCoreClasses.html#GUID-D5D99935-D8AF-4E16-BD52-88B2A7537B84

You can email the trace to dotnet_us(at)oracle.com and we'll take a look. It will give us a better idea of what the problem is if we have trouble setting up the test case.

**Comment by alexkeh** [comment]
@pbros 

We tried the tests under WorkflowCore.Tests.Oracle, but were unable to get them to work properly. Is there some guidance you can provide in using the tests? If it's easier to communicate via email, please email dotnet_us(at)oracle.com or post your email address. We'll get in contact with you.

**Comment by alexkeh** [comment]
Bug 30452644 has been fixed. It shipped in ODP.NET EF Core 19.6, which was just published on NuGet Gallery.
