### ISSUE TITLE
Can not resolve reference: `System.Diagnostics.PerformanceCounter`, referenced by `Oracle.ManagedDataAccess`.

### ISSUE THREAD

**Issue by simix-felipebaltazar** [oracle/dotnet-db-samples#53]
## Overview

After creating a new Xamarin.Android project (VS2019) and added `Oracle.ManagedDataAccess.Core` library, I can't compile exit with an error.

<details>
    <summary>
        <b>Error description (Click to expand)</b>
    </summary>

Can not resolve reference: `System.Diagnostics.PerformanceCounter`, referenced by `Oracle.ManagedDataAccess`. Please add a NuGet package or assembly reference for `System.Diagnostics.PerformanceCounter`, or remove the reference to `Oracle.ManagedDataAccess`.
</details>

## Steps to reproduce

1. Create a new Xamarin.Android (specific platform) project at windows VS 2019;
2. Add `Oracle.ManagedDataAccess.Core` to the project;
3. And error throw when try to compile the project

**Comment by simix-felipebaltazar** [comment]
Thanks for your reply!

**Comment by alexkeh** [comment]
My dev team has closed the bug as Android is not officially supported by ODP.NET Core.
https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/InstallSystemRequirements.html#GUID-A6405CAD-C0E9-45E0-9C38-26B7ED214479
