### ISSUE TITLE
ODP.NET Core LDAP settings

### ISSUE THREAD

**Issue by davidbernardo** [oracle/dotnet-db-samples#55]
Are there any examples of the configurations to connect with ldap in .NET CORE?

**Comment by alexkeh** [comment]
I don't have any sample configurations. The LDAP properties you'll need to use are the following ones in the OracleConfiguration class: https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/ConfigurationDirectoriesProperties.html#GUID-B966ACFC-FE33-4DAC-B048-03DED04CE23B

For managed or unmanaged ODP.NET, you would set these LDAP settings in a .NET config or ldap.ora file. Just move those same settings over to the OracleConfiguration class in .NET Core.
