### ISSUE TITLE
Tab opens unnecessarily when executing PL/SQL

### ISSUE THREAD

**Issue by TBinconso** [oracle/dotnet-db-samples#57]
I just started to try out your extension and it is very satisfying.

Only one thing: When I execute a .SPC or .BDY file and the compilation is successful, the extension opens another tab (just like it does when you execute standard-SQL) and displays the command (in my case the creation of a 2000 line packge-body) it just fired. In case of an error during compilation the extension behaves quite familiar. It opens a new tab and displays the error-message. That's okay, because it is useful information and I need to see this.

But it is annoying to see the full package content after each compilation.

Can this issue be resolved via configuration? Is it a bug or is it intended behavior?

Thanks!

**Comment by alexkeh** [comment]
@christianshay can you answer these questions?

**Comment by TBinconso** [comment]
I just realized, that I placed this maybe in the wrong repo. What I am talking about is not about the dotnet-db-samples. It is about the VS code plugin "Oracle Developer Tools for VS Code"

**Comment by alexkeh** [comment]
@TBinconso You can also try posting your questions to the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=Oracle.oracledevtools&ssr=false#qna), which has a Q&A section for products.

**Comment by TBinconso** [comment]
@alexkeh Thanks. I did so.
