### ISSUE TITLE
Can't save NUMBER(4,0) to database

### ISSUE THREAD

**Issue by xamadev** [oracle/dotnet-db-samples#60]
I scaffolded the model from database which contains a column with datatype NUMBER(4,0). It's mapped wrongly to datatype byte instead of int as mentioned in [this post](https://github.com/oracle/dotnet-db-samples/issues/41). I changed the type manually to int. Reading data from database works fine but saving ends in the following exception:

"System.InvalidCastException" in Microsoft.EntityFrameworkCore.dll - The specified conversion is invalid.

Datatype short also doesn't work. Datatype byte works.

Thanks for your help.

Version info:
Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production
Oracle.ManagedDataAccess.Core 2.19.60
Microsoft.EntityFrameworkCore 2.2.6

**Comment by alexkeh** [comment]
You may be able to solve this error by using Value Conversions. See this thread for more details.

https://community.oracle.com/thread/4293559

**Comment by xamadev** [comment]
Thanks for your help. The workaround defining the conversion from the linked post did the trick:

protected override void OnModelCreating(ModelBuilder modelBuilder)  
{  
  modelBuilder.Entity<Item>().Property(t => t.ItemLoc).HasColumnType("NUMBER(5)");  
  modelBuilder.Entity<Item>().Property(t => t.ItemLoc).HasConversion(  
    t => Convert.ToInt32(t),  
    t => Convert.ToInt32(t));  
}
