### ISSUE TITLE
Update-Database doesn't use transaction!

### ISSUE THREAD

**Issue by adomorn** [oracle/dotnet-db-samples#62]
When i apply initial migration with  Update-Database and if it fails, some tables are still reflected to database. It looks like it is not using Transaction Scope.. 
Could you advise on this?
I am using Oracle.EntityFrameworkCore 2.19.60

**Comment by alexkeh** [comment]
DDL is not transactional. That's the fundamental reason why migrations can't be wrapped in a transaction scope.
