### ISSUE TITLE
we are getting this issue Could not load type 'Autonomous_Managed_ODP_WebApp.autonomous_managed_odp'.

### ISSUE THREAD

**Issue by anjanidevio** [oracle/dotnet-db-samples#64]
Server Error in '/' Application.

Parser Error 
  Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

 Parser Error Message: Could not load type 'Autonomous_Managed_ODP_WebApp.autonomous_managed_odp'.

Source Error: 

Line 19: --> Line 20:  Line 21: <%@ Page Language="C#" AutoEventWireup="true" CodeBehind="autonomous-managed-odp.aspx.cs" Inherits="Autonomous_Managed_ODP_WebApp.autonomous_managed_odp" %> Line 22:  Line 23: <!DOCTYPE html>
--

**Comment by alexkeh** [comment]
In my Visual Studio solution file, I named the project "Autonomous-Managed-ODP-WebApp", which becomes the prefix in what the web page inherits from:  "Autonomous_Managed_ODP_WebApp.autonomous_managed_odp".

Make sure your project name and references to the project name when you modify the sample code match.
