### ISSUE TITLE
Versioning problems

### ISSUE THREAD

**Issue by EamonHetherton** [oracle/dotnet-db-samples#65]
I'm trying to switch from oracle.manageddataaccess 19.7.0 to oracle.manageddataaccess.core 2.19.70 but you've gone and reused the same dll name in the package but used a lower file version number!

oracle.manageddataaccess 19.7.0  -> Oracle.ManagedDataAccess.dll 4.122.19.1
oracle.manageddataaccess.core 2.19.70 -> Oracle.ManagedDataAccess.dll 2.0.19.1

What this means is that windows installer will leave the "older" dll in place when you try to install a new version and the application fails at runtime.

I don't suppose there is any chance of changing the dll name to match the package name?

Also, seems to me life would much simpler if the library file version simply tracked the nuget package version.

**Comment by alexkeh** [comment]
You can deinstall the managed ODP.NET first before installing ODP.NET Core to solve the problem of the managed ODP.NET DLL being left in place. Technically, these are two separate assemblies, which is why the managed ODP.NET DLL is kept installed.

There are historical reasons for the versioning and why they differ between the file version and NuGet packaging. The NuGet version is meant to be read by humans. The file version is meant to be read by .NET.

**Comment by EamonHetherton** [comment]
I know they are two different assemblies and that is my point; they are named the same even though as you say "Technically, these are two separate assemblies".  That is the problem I'd like to see addressed.  The ODP.NET Core assembly is straight up a different assembly and as such should be called something else like Oracle.ManagedDataAccess.Core.dll then versioning would not come into the discussion at all.

To be clear, I'm not talking about installing ODP.NET directly.  The Oracle.ManagedDataAccess.dll is included in the build output of our product because it is references ODP.NET, we then build a MSI installer file from the build output which puts the file into our installer.  The problem we face is that a previous version of our product (lets call it v1.0) included ODP.NET and as such the file Oracle.ManagedDataAccess.dll v4.122.19.1 and the new version (say v2.0) has moved to ODP.NET Core so now includes Oracle.ManagedDataAccess.dll v2.0.19.1.  If someone does an upgrade from v1.0 -> v2.0, windows installer detects the same file name with a higher version number already exists on disk and leaves that file in place which breaks the application at runtime as it cannot find v2.0.19.1.  Overriding that behavior in windows installer is not quite trivial and quite beside the point here.

The file version attribute is not used by .NET, only the assembly version 
[https://support.microsoft.com/en-au/help/556041](https://support.microsoft.com/en-au/help/556041) but the file version is used by windows installer when deciding which file to keep when presented with  two files with the same name.

**Comment by alexkeh** [comment]
Naming the two assemblies makes it possible to migrate from managed ODP.NET to ODP.NET Core possible without any code changes. At the time this decision was made, Microsoft recommended namespaces and assembly names match between .NET FW and .NET Core.

In .NET, the first two digits of the library file version have special meaning when upgrading. If the first or second digit changes, an existing app will not use the the new assembly version unless there is an app policy file that indicates that or the app is rebuilt. The feedback ODP.NET customers have given over the years is they want to upgrade only by installing without additional configuration tasks. "Freezing" the ODP.NET assembly versions has met this goal.

NuGet versioning is more flexible as there are no inherent .NET operations tied to a NuGet version change. Oracle has tied NuGet versioning to ODP.NET's actual versions.

I'm not saying there are no downsides to these decisions. There are. However, most customers will experience a smoother experience as a result.

For MSI, do you have the option to 'always copy over'? That would ensure your ODP.NET Core version will always overwrite your managed ODP.NET version.

**Comment by EamonHetherton** [comment]
TBH windows installer being so strongly opinionated about file versioning and not having support to allow the installer's author to force overwrite a single file regardless of version is a huge PIA but its behavior is well defined and not easy to workaround (I've yet to find a workaround that doesn't come with baggage) and besides, I feel the root problem is the versioning of the ODP.NET and core libraries.

You said that
> In .NET, the first two digits of the library file version have special meaning when upgrading. If the first or second digit changes, an existing app will not use the the new assembly version unless there is an app policy file that indicates that or the app is rebuilt

can you provide a reference for this that I can read?  This does not match with my understanding nor with a small test application I just created to test it (console application built against v1.0.0.0 of a library had no problem when I swapped the library dll with version 2.0.0.0 and 3.0.0.0 without rebuilding the console .exe with no binding redirects).  Maybe it was that way a long time ago but does not appear true today.

Also two microsoft articles appear to contradict this in my reading [https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies](https://docs.microsoft.com/en-us/dotnet/framework/deployment/how-the-runtime-locates-assemblies)
>There is no version checking for assemblies without strong names, nor does the runtime check in the global assembly cache for assemblies without strong names.

and [https://support.microsoft.com/en-au/help/556041](https://support.microsoft.com/en-au/help/556041)
> Assembly File Version : This is the version number given to file as in file system. It is displayed by Windows Explorer. Its **never** used by .NET framework or runtime for referencing.

As far as windows installer is concerned, it is this "Assembly File Version" that is causing my problem and this can be set independently of the assembly version anyway.

I think that if the assembly within the oracle.manageddataaccess.core nuget package is going to retain the same name as in oracle.manageddataaccess (i.e. Oracle.ManagedDataAccess.dll) going forward and the expectation is that people will be migrating from ODP.NET -> ODP.NET Core, then setting the "Assembly File Version" to something greater than 4.122.19.1 would facilitate a much smother upgrade path.

For now, I feel exhausted by the process of trying to "upgrade" from oracle.manageddataaccess -> oracle.manageddataaccess.core and I'm backing out.  Going to leave the old package in place until the migration story gets better.

**Comment by alexkeh** [comment]
In the first article you link to, it says in the first paragraph.

> By default, the runtime attempts to bind with the exact version of an assembly that the application was built with. This default behavior can be overridden by configuration file settings.

The second article also recommends keeping the "Assembly Version" the same with each assembly release.

In our experience testing .NET assembly version, modifying the first two sets of digits forces apps to rebuild if they want to use the newer ODP.NET, rather than just being able to drop in place.

With that said, modifying the Assembly File Version is a useful suggestion. My team will take a look at potentially adopting this.

Thanks for your constructive feedback!

**Comment by alexkeh** [comment]
This blog post provides more details about [ODP.NET versioning and what the each set of values represent in the version](https://medium.com/@alex.keh/odp-net-versioning-primer-c1f5a365e701).

Long term, the ODP.NET Assembly File Version will follow the major .NET (Core) version. .NET 6 is the next LTS. When ODP.NET upgrades to .NET 6, then it will have a Assembly File Version larger than its managed ODP,NET counterpart, which should remain at major version 4 indefinitely.

**Comment by EamonHetherton** [comment]
Any commitment to a release schedule post net6.0 with a higher file version? (again, all I ask is that the "Assembly File Version" is changed above 4.122, keep the actual assembly version to whatever floats your boat. I'm investigating a migration to net5.0 and this issue has reared it's ugly head again.

Also your blog post suggests that the major version "is the minimum major .NET (Core) version number that this ODP.NET Core version supports" and as such it will not change unless you also drop support for netcore3.1....?

**Comment by alexkeh** [comment]
The upcoming ODP.NET Core release that supports .NET 6 will also have support for .NET Core 3.1. When .NET 7 is released at the end of 2022, ODP.NET Core will then support .NET 6 too. The assembly product version will follow the minimum .NET (Core) version supported.

So, yes, we need to wait for .NET Core 3.1 support to be dropped before the version is greater than the version for ODP.NET in .NET FW.
