### ISSUE TITLE
scaffold-dbcontext not generating classes

### ISSUE THREAD

**Issue by ptgullas** [oracle/dotnet-db-samples#67]
Hi,

I'm using Oracle.EntityFrameworkCore v 2.19.70. 

When I enter the scaffold-dbcontext command as described in the [get-started doc](https://github.com/oracle/dotnet-db-samples/tree/master/samples/dotnet-core/ef-core/get-started), it generates a ModelContext.cs file that is mostly empty, except for OnConfiguring() and OnModelCreating(). No DbSets or anything else from the DB. Any ideas?

**Comment by alexkeh** [comment]
It could be a DB privilege problem. Does the user have rights to access the schema objects you would like to scaffold?

You can set the Scaffold-DbContext command to verbose mode to get more details on what the issue may be.

**Comment by ptgullas** [comment]
I've been using the users listed in the connection strings that our existing legacy apps are using, and those apps are currently working and can retrieve the needed data from the DB.  What privileges does the EF Core provider require? I'm not really an Oracle guy...

**Comment by alexkeh** [comment]
The getting started tutorial provides the commands to grant the privileges that should cover most EF Core apps. You can skip the tablespace commands if storage is already configured for the DB user.

You will need DDL privileges for creating and altering schema objects when using EF Core migrations. At runtime, you likely will only need CRUD privileges.

At design time, you can grant the DDL privileges to create the necessary schema objects, then revoke them for runtime operations.

EF Core can theoretically modify almost any type of DB schema object, which makes it difficult to provide specific privileges to enable.
