### ISSUE TITLE
Newest EFCore Beta1: Scaffold-DbContext chooses decimal type for NUMBER(24,0)

### ISSUE THREAD

**Issue by fsmirne** [oracle/dotnet-db-samples#69]
During scaffolding columns defined as NUMBER(24,0) are translated to decimal instead of long.
Previously they were translated to long.

**Comment by alexkeh** [comment]
This may have been a bug with the previous version. Any NUMBER greater than 19 precision is intended to map to a decimal.

https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/EFCoreREDataTypeMapping.html#GUID-4FF3A9A3-AE49-431B-A4FB-31F8C53FCCF5

**Comment by fsmirne** [comment]
Thank you for the info!
