### ISSUE TITLE
.net core 3.1 beta | linq query exception when relating classes

### ISSUE THREAD

**Issue by JQ-IOWA** [oracle/dotnet-db-samples#70]
It appears to exclude the dot between BookingBlock alias class and the property.

I've tweaked my classes and now I get a 00936 Missing expression.
Update: I've added the one to many relationship in dbcontext and added the CustomerGroup as a property to BookingBlock. I get the same ora 00936.

The query I'm looking to mimic is 
` select pbb.RPTNG_FLOW_PATH_ID,
             pcg.CUST_GROUP_IDFTN
        from PDF_BOOKING_BLOCK pbb, PDF_CUST_GROUP pcg
       where 1 = 1
         and pbb.CUST_GROUP_IDFTN = pcg.CUST_GROUP_IDFTN
         and pbb.RPTNG_FLOW_PATH_ID = 2
         and pbb.CUST_GROUP_IDFTN = 275`

DBContext
`
public DbSet<BookingLimit> BookingLimits { get; set; }
public DbSet<BookingBlock> BookingBlocks { get; set; }
public DbSet<CustomerGroup> CustomerGroups { get; set; }
public DbSet<FlowPath> FlowPaths { get; set; }
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      //leaving this for now to use for direct db integration/validation in unit test
      if (!optionsBuilder.IsConfigured)
      {
        optionsBuilder
          .UseLoggerFactory(ConsoleLoggerFactory)
          .UseOracle("Data Source = xxx");
      }
    }

    public static readonly ILoggerFactory ConsoleLoggerFactory =
      LoggerFactory.Create(builder =>
      {
        builder.AddFilter((category, level) =>
          category == DbLoggerCategory.Database.Command.Name && level == LogLevel.Information).AddConsole();
      });

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      modelBuilder.Entity<BookingBlock>().ToTable("PDF_BOOKING_BLOCK");
      modelBuilder.Entity<FlowPath>().ToTable("PDF_FLOW_PATH");
      modelBuilder.Entity<CustomerGroup>().ToTable("PDF_CUST_GROUP");

      //tables w/ composite keys
      modelBuilder.Entity<BookingBlock>()
          .HasKey(pk => new { pk.RPTNG_FLOW_PATH_ID, pk.CUST_GROUP_IDFTN }); 
      //one to many
      modelBuilder.Entity<CustomerGroup>().HasMany(cg => cg.BookingBlocks).WithOne(bb => bb.CustomerGroup);
`

Classes

`
  public class CustomerGroup
  {
    public CustomerGroup()
    {
      BookingBlocks = new List<BookingBlock>();
    }

    [Key]
    public int CUST_GROUP_IDFTN { get; set; }
    public string CUST_GROUP_NAME { get; set; }
    public string CUST_GROUP_DESC { get; set; }
    public string ENABLED_INDIC { get; set; }
    public string LAST_CHNGD_IDFTN { get; set; }
    public DateTime DATE_CRTD { get; set; }
    public DateTime DATE_LAST_CHNGD { get; set; }
    public List<BookingBlock> BookingBlocks { get; set; }
  }
`

`
 public class BookingBlock
  {

    public int RPTNG_FLOW_PATH_ID { get; set; }
    public int CUST_GROUP_IDFTN { get; set; }
    public int BLOCK_MIN_LEAD_TIME { get; set; }
    public int BLOCK_BKNG_WEEKS { get; set; }
    public string ENABLED_INDIC { get; set; }
    public int SORT_SEQ { get; set; }
    public string LAST_CHNGD_IDFTN { get; set; }
    public DateTime DATE_CRTD { get; set; }
    public DateTime DATE_LAST_CHNGD { get; set; }
    public FlowPath FlowPath { get; set; }
public CustomerGroup CustomerGroup { get; set; }
  }
`

on 06/02 I got this error. 
Oracle.ManagedDataAccess.Client.OracleException: ORA-00904: "p"."BookingBlockCUST_GROUP_IDFTN": invalid identifier

After some class adjustments I now get the 00936
`      using (var context = new DaleContext())
      {
        var customer = context.CustomerGroups.Where(cg => cg.CUST_GROUP_IDFTN == 275 && cg.BookingBlocks.FirstOrDefault().RPTNG_FLOW_PATH_ID == 2).ToList();
        Assert.AreEqual(1, customer.Count);
      }`

 Test method 
    Oracle.ManagedDataAccess.Client.OracleException: ORA-00936: missing expression

I have no issues running this the filter w/ just the cust identifer:
`
using (var context = new DaleContext())
      {
        var customer = context.CustomerGroups.Where(cg => cg.CUST_GROUP_IDFTN == 275).ToList();
        customer.ForEach(c => Console.WriteLine(c.CUST_GROUP_NAME));

        Assert.AreEqual(1, customer.Count);
      }
`

**Comment by alexkeh** [comment]
Can you provide more in the test case? I don't have enough here to understand how the problem occurs.

**Comment by JQ-IOWA** [comment]
I've tried to clarify the post and clean up the example. Apologies, I don't do this often and my linq is a little rusty. It very much could be me but I can't get to the logger and debugging doesn't let me step in.

**Comment by JQ-IOWA** [comment]
Message: 
    Test method Arconic.UnitTest.Core.DaleUnitTest.Get_AmCastleCompany_FlowPath_27NFT_BookingWeeks threw exception: 
    Oracle.ManagedDataAccess.Client.OracleException: ORA-00936: missing expression
  Stack Trace: 
    OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
    OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
    OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
    OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
    DbCommand.ExecuteReader()
    OracleRelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
    Enumerator.InitializeReader(DbContext _, Boolean result)
    OracleExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
    Enumerator.MoveNext()
    List`1.ctor(IEnumerable`1 collection)
    Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by JQ-IOWA** [comment]
Oracle Database 10g Enterprise Edition Release 10.2.0.5.0 - Prod
PL/SQL Release 10.2.0.5.0 - Production
CORE	10.2.0.5.0	Production
TNS for Linux: Version 10.2.0.5.0 - Production
NLSRTL Version 10.2.0.5.0 - Production

**Comment by SIkebe** [comment]
https://medium.com/oracledevs/beta-release-oracle-entity-framework-core-3-1-eb0b4d3c93b1
>The beta supports Oracle Database server 11.2.0.4 and higher

**Comment by JQ-IOWA** [comment]
> https://medium.com/oracledevs/beta-release-oracle-entity-framework-core-3-1-eb0b4d3c93b1
> 
> > The beta supports Oracle Database server 11.2.0.4 and higher

Thanks, I can respect that. However, I do get results with for the parent level but I do not get the list of child objects from the related class. I would think, even though we're on 10.2 that a seemingly straight forward one to many would also work.

**Comment by alexkeh** [comment]
@JQ-IOWA 
My team at Oracle hasn't tested Oracle 10.2 DBs with Oracle EF Core 3.1 since it's not a supported combination. It's not totally unexpected that some straightforward use cases will fail.

**Comment by JQ-IOWA** [comment]
Ok, I'll have access to v11 to test this friday and over the weekend. if it fails, mind if i re-open? @alexkeh If it works, i'll share my results.

**Comment by JQ-IOWA** [comment]
Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - Production
PL/SQL Release 11.2.0.4.0 - Production
CORE	11.2.0.4.0	Production
TNS for Linux: Version 11.2.0.4.0 - Production
NLSRTL Version 11.2.0.4.0 - Production

`  public class DaleContext : DbContext
  {
    public DaleContext()
    {
      ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
    }

    public DaleContext(DbContextOptions options) : base(options)
    {
      ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
    }

    public DaleContext(DbContextOptions<SecurityContext> options) : base(options)
    {
      ChangeTracker.QueryTrackingBehavior = QueryTrackingBehavior.NoTracking;
    }
    public DbSet<BookingBlock> BookingBlocks { get; set; }
    public DbSet<CustomerGroup> CustomerGroups { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      //leaving this for now to use for direct db integration/validation in unit test
      if (!optionsBuilder.IsConfigured)
      {
        //if this does remain, then pull data source string from json file where it's NOT stored in git
        optionsBuilder
          .UseLoggerFactory(ConsoleLoggerFactory)
          .UseOracle("Data Source = xxxx;"
          , b => b.UseOracleSQLCompatibility("11"));
      }
    }

    public static readonly ILoggerFactory ConsoleLoggerFactory =
      LoggerFactory.Create(builder =>
      {
        builder.AddFilter((category, level) =>
          category == DbLoggerCategory.Database.Command.Name && level == LogLevel.Information).AddConsole();
      });

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
      modelBuilder.Entity<BookingBlock>().ToTable("PDF_BOOKING_BLOCK");
      modelBuilder.Entity<BookingLimit>().ToTable("PDF_BOOKING_LIMIT");
      modelBuilder.Entity<CustomerGroup>().ToTable("PDF_CUST_GROUP");

      //one to many
      modelBuilder.Entity<CustomerGroup>().HasMany(cg => cg.BookingBlocks).WithOne(bb => bb.CustomerGroup);

      //tables w/ composite keys
      modelBuilder.Entity<BookingBlock>()
          .HasKey(pk => new { pk.RPTNG_FLOW_PATH_ID, pk.CUST_GROUP_IDFTN });

    }`

`  public class CustomerGroup
  {
    public CustomerGroup()
    {
      BookingBlocks = new List<BookingBlock>();
    }
    [Key]
    public int CUST_GROUP_IDFTN { get; set; }
    public string CUST_GROUP_NAME { get; set; }
    public string CUST_GROUP_DESC { get; set; }
    public string ENABLED_INDIC { get; set; }
    public string LAST_CHNGD_IDFTN { get; set; }
    public DateTime DATE_CRTD { get; set; }
    public DateTime DATE_LAST_CHNGD { get; set; }
    public List<BookingBlock> BookingBlocks { get; set; }
  }`

`  public class BookingBlock
  {
    public int RPTNG_FLOW_PATH_ID { get; set; }
    public int CUST_GROUP_IDFTN { get; set; }
    public int BLOCK_MIN_LEAD_TIME { get; set; }
    public int BLOCK_BKNG_WEEKS { get; set; }
    public string ENABLED_INDIC { get; set; }
    public int SORT_SEQ { get; set; }
    public string LAST_CHNGD_IDFTN { get; set; }
    public DateTime DATE_CRTD { get; set; }
    public DateTime DATE_LAST_CHNGD { get; set; }
    public CustomerGroup CustomerGroup { get; set; }
  }`

This test method used to work but after upgrade to 11G, it no longer does a simple count:
` [TestMethod]
    public void GetBookBlockCountExample()
    {
      using (var context = new DaleContext())
      {
        var bookingBlocks = context.BookingBlocks.ToList();
        Console.WriteLine($"count {bookingBlocks.Count}");
      }
    }`

This is the test method I used w/ 10G and it responds the same in 11G. Could it be the composite key of the child class BookBlock?
`    [TestMethod]
    public void Get_AmCastleCompany_FlowPath_27NFT_BookingWeeks()
    {
      //relationships not working in 10G because ODP
      using (var context = new DaleContext())
      {
        var customer = context.CustomerGroups.Where(cg => cg.CUST_GROUP_IDFTN == 275 && cg.BookingBlocks.FirstOrDefault().RPTNG_FLOW_PATH_ID == 2).ToList();
        Assert.AreEqual(1, customer.Count);
      }
    }`

**Comment by JQ-IOWA** [comment]
> Yes, please re-open if it fails with DB 11.2.0.4 or higher.

I can't reopen when close by repo collaborator.
