### ISSUE TITLE
Does Oracle.EntityFramework version 2.19.70 support  MapToStoredProcedures?

### ISSUE THREAD

**Issue by aarzayus** [oracle/dotnet-db-samples#72]

**Comment by aarzayus** [comment]
I 'm trying to use a stored stored procedure to insert values in the multiple table, and I want to map my entity to stored procedure in the dbcontext

**Comment by alexkeh** [comment]
Are you asking about Oracle.EntityFrameworkCore 2.19.70 or Oracle.EntityFramework 19.7?
