### ISSUE TITLE
Decimal overflow: bug of Oracle .NET Managed driver

### ISSUE THREAD

**Issue by giuliohome** [oracle/dotnet-db-samples#75]
The `Decimal ` column from Oracle DB can produce an overflow of the corresponding .NET `decimal`.

```
Eccezione non gestita: System.InvalidCastException: Cast specificato non valido.
   in Oracle.ManagedDataAccess.Client.OracleDataReader.GetDecimal(Int32 i)
   in Oracle.ManagedDataAccess.Client.OracleDataReader.GetValue(Int32 i)
   in Sql2Xlsx.Oracle.<Read>d__3.MoveNext() in C:\dev\SqlServer\Sql2Xlsx\Oracle.cs:riga 102
```

A workaround is needed.

```
// decimal overflow workaround 
field.ObjValue =
    field.DataType == "Decimal"?
    DR.GetDouble(i) :
    DR.GetValue(i);
```

Please forward and fix the code in the Oracle .NET Managed driver, thanks

**Comment by alexkeh** [comment]
In the next DB release, ODP.NET will introduce a new SuppressGetDecimalInvalidCastException property that will allow suppressing this error and round off the result automatically.

If you wish to preserve the entire NUMBER value, you can do so today with [Safe Type Mapping](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/featSafeType.html#GUID-A5600A8D-273A-4BAE-9591-193A43E7E2C6).

**Comment by giuliohome** [comment]
Thank you very much for your immediate and very interesting answer! 
Please close the issue as you prefer.

**Comment by giuliohome** [comment]
Just a marginal note, so called Oracle driver "safe tape mapping" seems not
practical and usable IMO. Having a list of column names defeats the purpose
of general programming and using `byte` or `string` is not a consistent
choice in a managed .net solution. I found interesting your anticipation
about the exception suppression and the automatic rounding. For the rest, I
confirm my workaround as today's solution for my business case.

**Comment by zak-nye** [comment]
I just wanted to post a note that I have set this SuppressGetDecimalInvalidCastException property and still get the issue.

```
Value = reader.GetValue(i) // i is the field index to the offending column
```

The Value property being assigned to is of type ```object```. The value being read is -

-8.621E+41
or
-862100000000000000000000000000000000000000

The source system I'm reading from is notoriously unreliable in terms of values so I have to code defensively all over but unfortunately in this case the fix does not work. I'm not sure about more "sensible" values.

**Comment by alexkeh** [comment]
@zak-nye Isn't that number too large to be stored in a .NET Decimal? It would be out or range.

**Comment by zak-nye** [comment]
@alexkeh Yes it is. I have the new SuppressGetDecimalInvalidCastException property set to true so I thought this would be rounded but is instead still throwing an exception. Unless I'm missing the point of the fix?

**Comment by zak-nye** [comment]
@alexkeh actually you're right. I guess if the number could be rounded and fit in to the type it would work but because this number is too large this doesn't make sense. Thanks I can see it now.

**Comment by giuliohome** [comment]
It should be a double, not a decimal, and it should not throw an exception... Indeed this is why I keeped my workaround and not the proposed-above property
