### ISSUE TITLE
DotNet Core3.1 Database Migration

### ISSUE THREAD

**Issue by Shoogn** [oracle/dotnet-db-samples#76]
When I prepare my migration like this
` PM> Add-Migration -Name InitiSchema -Context DataContext`

-------
this my startup class :
```
services.AddDbContext<TestCoreApp.OracleModels.DataContext>(option =>
            option.UseOracle(Configuration.GetConnectionString("ProductInventroyContext")));
```
------
I receive this error:
-------------
`Method 'get_Info' in type 'Oracle.EntityFrameworkCore.Infrastructure.Internal.OracleOptionsExtension' from assembly 'Oracle.EntityFrameworkCore, Version=2.0.19.1, Culture=neutral, PublicKeyToken=89b483f429c47342' does not have an implementation. `
-------------

**Comment by alexkeh** [comment]
Oracle.EntityFrameworkCore version 2.0.19.1 is the .NET Core 2.x version. Use the the 3.19.0 version, which is currently on [NuGet](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/3.19.0-beta1), for use with EF Core 3.1.

**Comment by Shoogn** [comment]
Thanks its working now
 I updated my **entity framework** packages and its all **related** packages
