### ISSUE TITLE
Cast error when changing data type

### ISSUE THREAD

**Issue by Quietscheente** [oracle/dotnet-db-samples#77]
I scaffolded our database with EF Core 3.1 using Oracle.EntityFrameworkCore 3.19.0-beta1

I got properties like this:

```C#
[Column("CODE", TypeName = "NUMBER(4)")]
public byte Code { get; set; }
```

The problem is, that it crashes at every single row I want to load from the database because byte is too small for Number(4)
My next try was to change the Type from byte to short. If I do this I get 
`InvalidCastException: Unable to cast object of type 'System.Int16' to type 'System.Byte'.`

The only way I got this working is to delete the TypeName completely, but then I always have to adjust the migration files and set the data types of affected columns manually.

Is this a bug? Or hidden magic somewhere? And how can I change the type without getting Exceptions?

Stacktrace:
```
StackTrace:
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)

  This exception was originally thrown at this call stack:
    Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer<T>.Equals(object, object)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.LocalDetectChanges(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry)
    Microsoft.EntityFrameworkCore.ChangeTracking.Internal.ChangeDetector.DetectChanges(Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IStateManager)
    Microsoft.EntityFrameworkCore.ChangeTracking.ChangeTracker.DetectChanges()
    Microsoft.EntityFrameworkCore.Internal.InternalDbSet<TEntity>.Local.get()
    AdministrateCoreSheets.CoreSheetsViewModel.CoreSheetsViewModel() in CoreSheetsViewModel.cs
    AdministrateCoreSheets.MainWindowViewModel.MainWindowViewModel() in MainWindowViewModel.cs

Inner Exception 1:
InvalidCastException: Unable to cast object of type 'System.Int16' to type 'System.Byte'.
```

**Comment by alexkeh** [comment]
Why not scaffold to an Int16? Int16 is large enough to fit NUMBER(4).

The reason Oracle EF Core scaffolds NUMBER(4) to a Byte is that EF Core allows providers to use only one set of mappings for both migrations and scaffolding. If the DB data types do not match .NET data type sizes exactly, then there will be a precision mismatch. In one direction, the data type precision will go from smaller to larger. The other direction it will be larger to smaller. There won't be a problem when going from smaller to larger, which is what happens in Oracle EF Core migrations. Unfortunately, that forces scaffolding to from larger to smaller. The current solution is to add Fluent API or Data Annotations to scaffolded models.

**Comment by Quietscheente** [comment]
Thanks for your reply.

Unfortunately I do not understand it yet.
Using an Int16 (or a "short", what I tried) was my intention.

So I changed
`public byte Code { get; set; }`
to
`public short Code { get; set; }`
with the result of getting
`InvalidCastException: Unable to cast object of type 'System.Int16' to type 'System.Byte'.`
when loading entities.

What further possibilities "to add Fluent API or Data Annotations to scaffolded models" did you mean?

**Comment by alexkeh** [comment]
I just tried your scenario myself and I can reproduce your issue. I tried changing the data type to Int16 and the error remained. I filed bug 31548972 on your behalf and my dev team will investigate.

Thanks for providing the details needed to reproduce.

I tested with NUMBER(3) and modifying the data type from byte to short works fine. This looks like a problem specifically with NUMBER(4).

**Comment by Quietscheente** [comment]
Ah, good to know.
i did not expect it to be isolated issues because I tried this one and I tried to change a primary key Number(22) from decimal to long what also ended in a cast error `InvalidCastException: Unable to cast object of type 'System.Func3[System.Decimal,System.Decimal,System.Boolean]' to type 'System.Func3[System.Int64,System.Int64,System.Boolean]'.`

**Comment by alexkeh** [comment]
The change in Fluent API or Data Annotations I was referring to earlier was setting "NUMBER(4)" to "NUMBER(5)" instead. Making that change will avoid the error. In Fluent API, you would have something like:
`.HasColumnType("NUMBER(5)")`

I'm not sure about the Decimal to Long cast. The problem could be the possible loss of data as Decimals would need to be rounded to support an integer data type.

**Comment by Quietscheente** [comment]
Regarding rounds: Yes, maybe the decimal to long cast can be a bit tricky because maybe you cannot get the "history" of the data type easily. But In reality it was never a floating point type but a Number(22) so there is no need to round.

**Comment by alexkeh** [comment]
My dev team has fixed the bug for the next Oracle EF Core release. If you change the entity property's .NET data type, you won't get the InvalidCastException error anymore.

**Comment by alexkeh** [comment]
For your NUMBER(22) from Decimal to Long issue, if you have a test case, I can take a look.

**Comment by Quietscheente** [comment]
It is reproducable with every Number(22, 0) column we have. Scaffold chooses decimal as the data type. If you change it to „long“ the cast error should appear.

**Comment by alexkeh** [comment]
I was able to reproduce your primary key NUMBER(22) error and filed a bug (31608698). My dev team will investigate.

**Comment by alexkeh** [comment]
I got some clarification from my dev team. Both of these issues are expected behavior, not bugs. To avoid getting the cast exception, remove the HasColumnType Fluent API. This will be documented in the production doc as:

=========
When scaffolding, developers may wish to change the default data type mappings between Oracle Database and .NET. When modifying .NET CLR types of the generated entity's property, remove the auto-generated "HasColumnType()" Fluent API in the model. For example, an Oracle NUMBER(4) is scaffolded to a .NET Byte data type by default. If the .NET CLR data type is changed to .NET Short or Int16 data type, an invalid cast exception at runtime may occur until the "HasColumnType("NUMBER(4)")" has been removed.

**Comment by Quietscheente** [comment]
Thank you, even if the solution is not very satisfying.
You have to set the data type manually for each migrate that affects the column, because Oracle assumes the wrong type.

**Comment by alexkeh** [comment]
It's not the wrong type, per se. Rather, it's the least disruptive solution that's possible.

EF Core only allows a single set of data type mappings for both scaffolding and migrations. When the data types between .NET and DB do not align in size, mismatches are unavoidable. Ideally, EF Core should allow provider writers to have a different set of mappings for each. Then, my team would implement mappings for each so that developers wouldn't have to modify data types nor Fluent API due to data size issues.

With this limitation, the provider writer has to choose whether scaffolding or migrations will require developer mapping modifications. Oracle has chosen scaffolding as most developers are using migrations.

**Comment by Quietscheente** [comment]
"The least disruptive solution that's possible" would be if Oracle would use the datatype I specify, I know best which datatype I need.
But ok, you defined it as expected behaviour that I cannot use EF without deleting all data types after scaffolding.
I have to live with it.

**Comment by alexkeh** [comment]
I agree. I don't like this limitation either. EF Core providers should allow developers to choose the data type mapping desired without having to delete HasColumnType.

Unfortunately, EF Core's design prevents the Oracle provider (or any provider) from enabling such a feature. This limitation is part of EF Core's design.
