### ISSUE TITLE
Empty DbContext, Support for version that is not 11.2

### ISSUE THREAD

**Issue by twsl** [oracle/dotnet-db-samples#78]
When I execute the `dotnet ef dbcontext scaffold` command an empty DbContext gets created. Upon checking the logs I found a message saying `Server Version: NOT 11.2`. what exactly is blocking other versions? Or is this totally unrelated and caused by permissions, as hinted in an other issue?

**Comment by alexkeh** [comment]
If you are not using DB version 11.2, then ignore this message. This is a check whether the version is 11.2. The SQL needed to scaffold between 11.2 and higher versions is different.

**Comment by twsl** [comment]
I do not know the exact version and do not own the database. What can I do to ensure, the scaffold works correctly?

**Comment by alexkeh** [comment]
You can execute the following query:
`SELECT BANNER FROM V$VERSION`

It will tell you the DB server version. If it's below 11.2.0.4, there isn't support. Versions older than 11.2 are no longer certified for newer Oracle clients..

You will need at least SELECT privileges on the schema.
