### ISSUE TITLE
Oracle.EntityFrameworkCore support for .NET 5.0

### ISSUE THREAD

**Issue by bholbrook** [oracle/dotnet-db-samples#81]
I understand there's a .NET Core 3.1 beta currently available right now but .NET Core 5.0 is releasing in November.
Are there plans to support .NET Core 5.0?

**Comment by alexkeh** [comment]
In our current ODP.NET Core .NET 5 testing, we haven't encountered any significant issues yet. So far, so good.

We've done some initial EF Core 5 testing. No issues yet there either. We'll perform more extensive testing once the Oracle EF Core 3.1 provider goes production. There aren't major provider changes required in EF Core 5 as there was in the transition from EF Core 2 to 3. As such, it should theoretically be akin to a certification effort with mostly bug fixing.

As you may remember, ODP.NET Core certified on .NET Core 3 soon after its release as there were no major ADO.NET provider related changes between .NET Core 2 and 3.

My personal expectation is that Oracle EF Core should be able to do the same as both .NET 5 and EF Core 5 do not have major ADO.NET and  EF Core provider changes either.

**Comment by mannok** [comment]
Is there any planned release date for .NET 5.0?   Will it be released within 2020?

**Comment by alexkeh** [comment]
@mannok We don't have an exact release date, but it should not be more than a month or two at the most after .NET 5's release. We have to test the final .NET 5 bits to certify our latest driver available. If we find a problem, we have to release a new provider. The inability to predict whether we'll find a showstopper is what makes it difficult to predict a more precise date. With that said, we've done quite a bit of ODP.NET testing with the .NET 5 previews and have not found any major problems yet.

**Comment by alexkeh** [comment]
I blogged today with an update on [Oracle's plans to certify with .NET 5 and EF Core 5](https://medium.com/@alex.keh/oracle-net-5-and-ef-core-5-status-update-2f5c508c6d7b). It's not a whole lot different from what I posted a couple months ago.

We feel more confident certifying with .NET 5 quickly. EF Core 5 will require some provider changes, but nowhere as extensive as EF Core 3.1 required. We're working on that and will provide an update on EF Core 5 release timing after making some more progress.

**Comment by mannok** [comment]
> I blogged today with an update on [Oracle's plans to certify with .NET 5 and EF Core 5](https://medium.com/@alex.keh/oracle-net-5-and-ef-core-5-status-update-2f5c508c6d7b). It's not a whole lot different from what I posted a couple months ago.
> 
> We feel more confident certifying with .NET 5 quickly. EF Core 5 will require some provider changes, but nowhere as extensive as EF Core 3.1 required. We're working on that and will provide an update on EF Core 5 release timing after making some more progress.

Thank @alexkeh for reporting the progress. I kept watching Oracle EFCore update on Nuget, haha, and I saw a stable version of 3.x has been released on it "3 hours ago" yesterday. Thanks for the work!

**Comment by alexkeh** [comment]
@mannok A preview Oracle EF Core 5 version is unlikely. Right now, the plan is to go straight to production. The changes needed to support EF Core 5 are not so extensive as needing a preview/beta.

**Comment by mannok** [comment]
@alexkeh May I know if there any way to use EF Core 5 features with `Oracle.EntityFrameworkCore` at this moment?

In my case, I want to use `--namespaces` option which has been introduced from [here](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet#dotnet-ef-dbcontext-scaffold).

**Comment by alexkeh** [comment]
@mannok Since the namespaces option is an EF Core 5 feature, it's not possible to use yet.

**Comment by bholbrook** [comment]
@alexkeh Very glad to hear the update is coming along reasonably smoothly.
Do you have any idea as to when the release will go public?
Would be great to have a RC2 preview version so that we can start to trial it on our own systems. Microsoft have said they'll support RC2 in production right now.

**Comment by mannok** [comment]
Waiting for a early RC2 preview version too!

**Comment by alexkeh** [comment]
@bholbrook 
We're targeting the Oracle EF Core 5 for January. .NET 5 support will be November. We won't have an Oracle beta for either. For all intents and purposes, you can "beta" test the current ODP.NET Core drivers with .NET 5. The first Oracle provider releases for .NET 5 and EF Core 5 will be production support.

I'll provide more details in a couple weeks in a blog post.

**Comment by barbinbrad** [comment]
Hi @alexkeh any updates on this?

**Comment by alexkeh** [comment]
@barbinbrad 
My last blog post on [Oracle .NET 5 and EF Core 5 availability is here](https://medium.com/@alex.keh/end-game-update-oracle-net-5-and-ef-core-5-35bd81d71843).

.NET 5 support is imminent. It could be today. When that happens, I'll have an EF Core 5 update too. The short version is that we're still on track for a December/January Oracle EF Core 5 release.

**Comment by mpierre0220** [comment]
@alexkeh Is there any update as to the availability of EF Core on .Net 5? I tried it and it is not working. Am I missing something, please?

**Comment by alexkeh** [comment]
Oracle EF Core 5 is not supported yet. Right now, it's looking like mid to late January for availability. We'll announce when it goes out on Twitter: [OracleDotNET](https://twitter.com/oracledotnet).

**Comment by FransBouma** [comment]
@alexkeh is there a beta we can subscribe to? We'd like to add Oracle support for Entity Framework Core 5 in our designer LLBLGen Pro but we currently can't move forward with that as we don't have any information what's supported (we used the v3 docs for now, which likely are sufficient but just in case). TIA

**Comment by alexkeh** [comment]
@FransBouma No beta is planned. We're going straight to production with delivery planned around the end of this month.

In terms of API changes, there are just a few new ones with EFC 5:

- an additional UseOracle overload
- ToQueryString
- IsOracle in MigrationBuilder

Is there any functionality you're wondering about in particular?

**Comment by FransBouma** [comment]
@alexkeh Sounds good. Was only wondering if e.g. type mappings would have changed/adjusted, new modelbuilder oriented extension methods would have been added, but this list looks like we can first try to get our code running with EF Core 3.1 and the current provider and then move to EF Core 5 when that releases at the end of the month. thanks!

**Comment by mariohik** [comment]
Sorry guys to ask that again, but it's already the last week of January.
Are you sure that the new version will be released later this month?

**Comment by alexkeh** [comment]
@mariohik We found one significant blocking issue in our EF Core 5 testing this week, which we need to fix before release. We'll provide the new expected delivery time frame on [Twitter](https://twitter.com/oracledotnet) by end of this week once we understand the solution better.

Sorry to miss the expected release date. We are very close.

**Comment by MohamedRDwedar** [comment]
Sorry Is there any update or expected date for the  EF Core 5 release ?

**Comment by Giorgi** [comment]
This is what twitter says:

Oracle Entity Framework 5 release is being delayed until mid-February. We encountered some issues this past week and will hold the release. We hope to release by February 15 on NuGet Gallery.

**Comment by MohamedRDwedar** [comment]
@Giorgi  Thanks 
It seems we will gave to wait .

**Comment by alexkeh** [comment]
[Oracle EF Core 5](https://www.nuget.org/packages/Oracle.EntityFrameworkCore/5.21.1) is now available.

**Comment by darkguy2008** [comment]
@alexkeh unfortunately it seems it's not compatible anymore? I'm trying to add it and it's not working:
![image](https://user-images.githubusercontent.com/6304136/117184954-8c91d800-ad96-11eb-9cb8-61d663247396.png)
```
error: NU1100: Unable to resolve 'Oracle.EntityFrameworkCore (>= 5.21.1)' for 'net5.0'.
error: Package 'Oracle.EntityFrameworkCore' is incompatible with 'all' frameworks in project 'API.csproj'.
```
Any ideas?

**Comment by Azumith86** [comment]
Hello, I am just trying to migrate to Net 5 and I have encountered a problem regarding properties inherited from abstract base classes, which in case of a new entity are initialized in a default value. Resulting that when performing the Add operation I get the error: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-01400: unable to perform NULL insert in ("BD". "TABLE". "FIELD")
However when I do the same but in SQL Server insert the default value in that field properly.

This would be the property in my base class:
private string _userCode;
public virtual string UserCode
        {
            get {return string.IsNullOrEmpty (_userCode) ? "ADMGDE": _userCode; }
            set {_userCode= value; }
        }

Which is mapped like this:
builder.Property (t => t.UserCode)
                .HasMaxLength (30)
                .HasColumnName ("USERCODE")
                .IsRequired ();

Inspecting the entity in the repository before inserting I verify that it has the correct value in that property, however I get the mentioned exception.

Is this a problem with Oracle or should it be done differently? Since at least in SQL Server it works correctly.
I've been reading about New pattern for store-generated defaults and I see that it would be fine that way, I don't understand what happens.
I appreciate any clarification in this regard, thank you very much.

**Comment by x545** [comment]
When will a ef7-compatible version be available?
