### ISSUE TITLE
EF Core 3.1 Beta 2 ORA-06512

### ISSUE THREAD

**Issue by samuelrvg** [oracle/dotnet-db-samples#83]
Error:
Microsoft.EntityFrameworkCore.DbUpdateException: 'An error occurred while updating the entries. See the inner exception for details.'

OracleException: ORA-32795: cannot insert into a generated always identity column
ORA-06512: em line 3

Oracle 19c 

`
    create table inpasa.blog(
    blogid number GENERATED ALWAYS AS IDENTITY
    ,title varchar(80)
    ,"url" varchar(80)
     )`

    public class BloggingContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        //public DbSet<Post> Posts { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseOracle(@"....");
        }
    }
    [Table(name: "BLOG", Schema = "INPASA")]
    public class Blog
    {
        [Column(name: "BLOGID")]
        public decimal BlogId { get; set; }
        [Column(name: "TITLE")]
        public string Title { get; set; }
        [Column(name: "url")]
        public string Url { get; set; }
        //public List<Post> Posts { get; set; }
    }
    using (var db = new BloggingContext())
    {
         var blog = new Blog { Url = "blogs.oracle.com", Title = "Funcionou ?" };
         db.Blogs.Add(blog);
         db.SaveChanges();
     }

- if test in database is correct insert:

insert into inpasa.blog (title, "url") values ('asdasdasd', 'xxxxx') -- Correct in Database, but not EF Core

**Comment by alexkeh** [comment]
I can reproduce this error. Try adding the following data annotation so that Oracle EF Core knows that the DB will be providing the value automatically.

            [Column(name: "BLOGID")]
            [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

With this annotation added, I was able to successfully run your sample.

**Comment by samuelrvg** [comment]
Thank you.
