### ISSUE TITLE
Passing User defined Data type to Oracle SP

### ISSUE THREAD

**Issue by larikrishnan** [oracle/dotnet-db-samples#85]
Team, we have created one oracle SP which has user defined data type as input and we are facing issue in executing that sp from asp.net core 3.1 using Oracle.ManagedDatAccess.Core. 

If anyone has implemented this scenario please help us on this.

**Comment by alexkeh** [comment]
UDTs are not yet supporting in ODP.NET Core. The feature request is being tracked here:
https://github.com/oracle/dotnet-db-samples/issues/56
