### ISSUE TITLE
Oracle.ManagedDataAccess - Intermittent Connection Request Timed out

### ISSUE THREAD

**Issue by sachinsu** [oracle/dotnet-db-samples#88]
Hi, 

**Environment** 
Oracle.ManagedDataAccess - 19.8.0
.NET framework  - 4.6.1
Oracle database - 12.2.0.2 Standard Edition, running on Oracle Linux 
Firewall exists between Windows servers and Oracle Database with TCP Idle session timeout set to 30 Min and 
UDP idle session timeout set to 1 Min.

With above, we have cluster of IIS Servers connecting to the database. We are experiencing intermittent timeout errors i.e. `Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Connection request timed out`. 

To fix this, we have set "Validate connection=true" in the connection string. However Oracle's [documentation](https://docs.oracle.com/en/database/oracle/oracle-database/12.2/odpnt/featConnecting.html#GUID-1152D13D-464C-4FE7-9949-32FCA9572B59) prefers creating event handler over setting this attribute,

> The Validate Connection attribute validates connections coming out of the pool. This attribute should be used only when absolutely necessary, because it causes a round-trip to the database to validate each connection immediately before it is provided to the application. If invalid connections are uncommon, developers can create their own event handler to retrieve and validate a new connection, rather than using the Validate Connection attribute. This generally provides better performance. 

Is their a sample of this event handler available?

**Comment by alexkeh** [comment]
Sorry, that was a typo. It should say "developers can create their own **error/exception** handler to retrieve...". You could use try/catch to retry the connection. Here's a code snippet example of how to use an ODP.NET exception handler.

```
 catch (OracleException ex) // catches only Oracle errors
 {
 switch (ex.Number)
 {
 case 1:
 MessageBox.Show("Error attempting to insert duplicate data.");
 break;
 case 12545:
 MessageBox.Show("The database is unavailable.");
 break;
 default:
 MessageBox.Show("Database error: " + ex.Message.ToString());
 break;
 }
 }
 catch (Exception ex) // catches any error
 {
 MessageBox.Show(ex.Message.ToString());
 }
```

If the fundamental problem is the firewall is sniping idle connections, an alternative way to fix the connection errors is using KeepAlive.

**Comment by sachinsu** [comment]
Thanks for clarification.
