### ISSUE TITLE
Timeout doesn't work

### ISSUE THREAD

**Issue by Pradhyo** [oracle/dotnet-db-samples#9]
I tried what's [here](https://msdn.microsoft.com/en-us/library/system.data.oracleclient.oraclecommand.commandtimeout(v=vs.110).aspx) but it fetched data beyond the timeout I set in seconds.

```c#
      using (OracleConnection connection = new OracleConnection(connectionString))
      {
        OracleCommand command = new OracleCommand(selectStatement, connection);
        command.Connection.Open();

        using (OracleDataAdapter da = new OracleDataAdapter(command))
        {
          da.SelectCommand.CommandTimeout = 30;
          da.Fill(dataTable);
          command.Connection.Close();
          da.Dispose();
        }
      }
```

**Comment by alexkeh** [comment]
The command timeout is the [minimum time allowed before terminating with an exception](https://docs.oracle.com/cd/E85694_01/ODPNT/CommandCommandTimeout.htm#GUID-F3B678B5-60E3-453D-B7D4-5ADE8082E1ED). That means that it's not guaranteed to occur at 30 seconds in your example. It could be 30 seconds or longer.

This command timeout is the same implementation between managed ODP.NET and ODP.NET Core. You should see the same behavior under the same conditions.

Just curious what you are trying to timeout. Is it a SQL statement or some form of PL/SQL? I would guess you're using just SQL.

**Comment by Pradhyo** [comment]
Thanks for the clarification. 

I'm running a simple Select query.. but I want to cancel it if it runs for more than 30 seconds so I can throw an exception.. and ask my users to further refine their filters so it doesn't take as long to return.

I guess I was looking for a maximum time allowed before terminating with an exception.

**Comment by Pradhyo** [comment]
I'm a bit confused now.  
This remark in the link seems to be exactly what I want but is different from your explanation. Maybe the command attempted to cancel but couldn't? How would I know if this is the case. Thanks again.

When the specified timeout value expires before a command execution finishes, the command attempts to cancel. If cancellation is successful, an exception is thrown with the message of ORA-01013: user requested cancel of current operation.

**Comment by Pradhyo** [comment]
Ok thanks again for clarifying.
