### ISSUE TITLE
Oracle.EntityFrameworkCore Sharing a transaction between several DbContext

### ISSUE THREAD

**Issue by g7ed6e** [oracle/dotnet-db-samples#91]
Hi,

I'm posting here since i did not find anything related to my question in ODP .NET documentation [https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/ODPEFCore.html#GUID-80B07B35-46C9-408F-A688-F98CE1A4CD6C](https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/ODPEFCore.html#GUID-80B07B35-46C9-408F-A688-F98CE1A4CD6C).

Does the Oracle.EntityFrameworkCore 2.19.80 support sharing transaction between several DbContext as described here 
[https://docs.microsoft.com/fr-fr/ef/core/saving/transactions](https://docs.microsoft.com/fr-fr/ef/core/saving/transactions).

Thanks,

**Comment by g7ed6e** [comment]
Hi @alexkeh any advice related to this topic ? Thanks

**Comment by alexkeh** [comment]
My team hasn't tested this functionality specifically. Have you tried it yourself?

**Comment by alexkeh** [comment]
@g7ed6e 
We tried a test that shares a transaction across multiple DbContext. Do you have a test case to share that you would like us to verify?

**Comment by alexkeh** [comment]
I tried the sample EF Core sample on the Microsoft doc page you link to and was able to successfully commit the transaction that used two DbContexts with the same connection and transaction.

**Comment by g7ed6e** [comment]
@alexkeh thanks for feedback.
